export default {
  id: '05',
  title: 'Datos y dominio',
  subtitle: 'Del problema real a un modelo de información que pueda sostener un sistema',
  ficha: {
    proposito: 'Diseñar, consultar y proteger la capa de información de un sistema a partir de su dominio.',
    publico: 'Estudiantes que ya cursaron o están cursando bases de datos. No parte de cero: cada capítulo abre con un refresco de los conceptos que usa.',
    competencias: 'Conocer, aplicar y analizar: dominio y lenguaje; entidades, relaciones y reglas; modelo relacional; normalización; SQL; transacciones y concurrencia; índices; seguridad; exposición de datos en APIs.',
    casoTransversal: 'Turnify. El modelo de dominio del Vol. 04 (figura 7.1) se convierte en una base de datos que hace cumplir las reglas de los volúmenes anteriores.',
    metodo: 'Cada capítulo empieza con un refresco de conceptos, los aplica a Turnify y termina con una práctica.',
    lugarEnElTronco: '05 · Fundamentos. Requiere los Vol. 01 a 04.',
    nivel: 'Inicial a intermedio',
    requiere: 'Vol. 01 a 04',
    preparaPara: 'APIs · integración · arquitectura',
  },
  recorrido: [
    { chapterId: '01', title: 'Pensar en datos antes que en tablas', pregunta: '¿Qué tiene que saber el sistema?' },
    { chapterId: '02', title: 'Descubrir el dominio', pregunta: '¿Qué significan las palabras del negocio?' },
    { chapterId: '03', title: 'Entidades, valores y relaciones', pregunta: '¿Qué tiene identidad propia y cómo se relaciona?' },
    { chapterId: '04', title: 'Reglas e invariantes', pregunta: '¿Qué estados deben ser imposibles?' },
    { chapterId: '05', title: 'Del dominio al modelo relacional', pregunta: '¿Cómo se traduce todo eso a tablas y claves?' },
    { chapterId: '06', title: 'Diseñar una base desde un caso real', pregunta: '¿Cómo se juntan los pasos en un proceso?' },
    { chapterId: '07', title: 'Normalización desde los problemas', pregunta: '¿Por qué no alcanza con una sola planilla?' },
    { chapterId: '08', title: 'SQL: hablar con los datos', pregunta: '¿Cómo le hacemos preguntas a la base?' },
    { chapterId: '09', title: 'Modificar con consistencia', pregunta: '¿Cómo evitamos la doble reserva?' },
    { chapterId: '10', title: 'Rendimiento', pregunta: '¿Qué hacemos cuando una consulta se vuelve lenta?' },
    { chapterId: '11', title: 'Seguridad y ciclo de vida', pregunta: '¿Cómo protegemos los datos personales?' },
    { chapterId: '12', title: 'Datos, APIs e integración', pregunta: '¿Qué datos salen del sistema y cuáles no?' },
  ],
  intro: {
    title: 'Sobre este volumen',
    body: [
      { type: 'p', text: 'Este cuadernillo no parte de una tabla ni de una sentencia SELECT. Parte de una pregunta: ¿qué información necesita conocer un sistema para hacer lo que el negocio necesita? El recorrido conecta análisis, modelado, bases de datos y desarrollo: dominio → modelo → datos → consultas → consistencia → rendimiento → seguridad → API.' },
      { type: 'box', kind: 'idea-clave', title: null, text: 'No aprendés SQL para aprobar SQL. Aprendés a trabajar con información porque los sistemas viven de información.' },
      { type: 'h3', text: 'El recorrido' },
      { type: 'p', text: 'Los capítulos 01 a 04 trabajan el dominio; del 05 al 07, el modelo; del 08 al 11, los datos; el 12 mira cómo salen del sistema.' },
      { type: 'h3', text: 'Cómo leer este cuadernillo' },
      { type: 'p', text: 'Los recuadros cumplen la misma función que en los volúmenes anteriores. Este volumen suma una sección fija, Refresco de conceptos, al comienzo de cada capítulo.' },
      { type: 'table', headers: ['Recuadro', 'Función'], rows: [
        ['IDEA CLAVE', 'La idea que tenés que llevarte del capítulo. Hay una sola por capítulo.'],
        ['EL CASO', 'Turnify y el lavadero: el ejemplo que acompaña toda la colección.'],
        ['PRACTICÁ', 'Un ejercicio, marcado con su nivel: conocer, aplicar o analizar. Las respuestas orientativas están al final.'],
        ['ATENCIÓN', 'Un error frecuente o una confusión que conviene evitar.'],
      ] },
      { type: 'p', text: 'Los ejemplos SQL usan PostgreSQL y se ejecutaron sobre una base de prueba de Turnify, incluidos los errores y los planes de ejecución que se muestran. Las definiciones remiten a una fuente citada al final de cada capítulo; los ejemplos y ejercicios son elaboración didáctica propia.' },
    ],
  },
  chapters: [
    {
      id: '01',
      title: 'Pensar en datos antes que en tablas',
      refrescoConceptos: {
        intro: 'Elmasri y Navathe definen los datos como hechos conocidos que pueden registrarse y que tienen un significado implícito. La información aparece cuando esos datos se interpretan en un contexto: “AB123CD” es un dato; “el Gol gris de Ana tiene turno a las 9” es información.',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Base de datos y SGBD', 'Una base de datos es una colección de datos relacionados con un propósito; el SGBD es el software que permite definirla, construirla, manipularla y compartirla (por ejemplo, PostgreSQL).'],
          ['Modelo conceptual', 'Describe qué información existe en el negocio, sin pensar en tecnología. Es el de los capítulos 02 a 04.'],
          ['Modelo lógico', 'Traduce el conceptual a un modelo de datos concreto, como el relacional: tablas, columnas y claves (cap. 05).'],
          ['Modelo físico', 'Decide cómo se almacena y se accede: tipos exactos, índices, particiones (cap. 10).'],
          ['Persistido o derivado', 'Un dato persistido se guarda porque no puede obtenerse de otro modo (la fecha de un turno); uno derivado se calcula a partir de otros (la edad, desde la fecha de nacimiento).'],
        ],
      },
      body: [
        { type: 'p', text: 'En el Vol. 04 dibujamos el sistema. Ahora la pregunta es otra: ¿qué tiene que recordar para funcionar?' },
        { type: 'p', text: 'Ante “una app para sacar turnos”, es tentador crear una tabla de turnos. Antes hay que saber qué información existe, quién la necesita y qué reglas cumple.' },
        { type: 'box', kind: 'el-caso', title: null, text: '“¿Qué turnos están disponibles mañana?” Para responder, Turnify necesita saber: el horario de atención del lavadero, qué recursos existen (los boxes, la máquina de tapizados), qué servicios puede hacer cada recurso, cuánto dura cada servicio y qué turnos ya están tomados y en qué estado.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La disponibilidad no es un dato: es una conclusión que se deriva de otros datos.' },
        { type: 'box', kind: 'atencion', title: null, text: 'guardar una tabla de “horarios libres” parece simple, pero cada reserva, cancelación o cambio de duración obliga a actualizarla, y cualquier error deja dos versiones de la verdad.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Guardado o derivado', text: '¿Qué datos necesita Turnify para responder “¿cuántos turnos atendió cada empleado este mes?”? ¿Cuáles se guardan y cuáles se derivan? ¿Falta alguno en la lista del caso?' },
      ],
      fuentes: ['Elmasri, R. y Navathe, S. B. — Fundamentals of Database Systems, caps. 1 y 3.'],
    },
    {
      id: '02',
      title: 'Descubrir el dominio',
      refrescoConceptos: {
        subtitulo: 'Diseño guiado por el dominio',
        intro: 'Eric Evans propuso dos ideas que ayudan mucho en esta etapa:',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Lenguaje ubicuo', 'Un vocabulario compartido entre quienes conocen el negocio y quienes construyen el sistema, que se usa igual en las conversaciones, en el modelo y en el código.'],
          ['Contexto delimitado', 'El límite dentro del cual un modelo y su lenguaje tienen un significado consistente. Fuera de ese límite, la misma palabra puede significar otra cosa.'],
          ['Ciclo de vida', 'Los estados por los que pasa un concepto desde que aparece hasta que deja de importar, como la máquina de estados del Vol. 04 (figura 8.1).'],
        ],
      },
      body: [
        { type: 'p', text: 'Antes de decidir cómo guardar, hay que ponerse de acuerdo sobre qué significan las palabras.' },
        { type: 'p', text: 'El dominio es el área de actividad del negocio que el sistema tiene que representar. En Turnify, el dominio no es “una app”: es la organización del trabajo de un lavadero.' },
        { type: 'box', kind: 'el-caso', title: 'Tres significados de “turno”', text: 'Para el cliente, un turno es un horario. Para el encargado, es un trabajo asignado a un box y a un empleado. En la planilla actual, es una fila. Si el equipo no acuerda un significado, el modelo va a tener tres verdades.' },
        { type: 'h3', text: '2.1 Un glosario mínimo' },
        { type: 'table', headers: ['Término', 'Definición acordada', 'No confundir con'], rows: [
          ['Turno', 'La reserva de un recurso, para un servicio y un vehículo, en un intervalo de tiempo.', 'El horario disponible (que es derivado).'],
          ['Servicio', 'Un trabajo que ofrece el lavadero, con una duración conocida.', 'El precio o la promoción.'],
          ['Recurso', 'Lo que un turno ocupa y no puede compartirse: un box o una máquina.', 'El empleado, que se asigna aparte.'],
          ['Vehículo', 'Un auto identificado por su patente, que pertenece a un cliente.', 'El modelo de auto.'],
          ['Cancelación', 'El cambio de estado de un turno a cancelado. El turno no se borra.', 'La eliminación de datos.'],
        ] },
        { type: 'p', text: 'En el Vol. 04 el recurso apareció como algo especial (la máquina de tapizados). Al modelar datos conviene generalizarlo: todo turno ocupa un recurso, y los boxes también lo son.' },
        { type: 'h3', text: '2.2 Lo que queda afuera' },
        { type: 'p', text: 'El pago existe en el negocio, pero “reportar ingresos” quedó fuera de la primera versión cuando priorizamos en el Vol. 02 (cap. 08). Dejarlo afuera es una decisión de límite, la misma que tomamos en el Vol. 01 (cap. 08), y conviene registrarla.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Si el equipo usa una palabra con dos significados, el modelo va a tener dos verdades.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Palabras del dominio', text: 'Separá las palabras del dominio de las que describen la interfaz: turno, botón reservar, patente, calendario, box, notificación push, cancelación, pantalla de inicio de sesión, recurso, estado. Después escribí la definición acordada de “estado”.' },
      ],
      fuentes: ['Evans, E. — Domain-Driven Design.', 'Fowler, M. — “Ubiquitous Language” y “Bounded Context”, martinfowler.com.'],
    },
    {
      id: '03',
      title: 'Entidades, valores y relaciones',
      refrescoConceptos: {
        subtitulo: 'Modelo entidad-relación',
        intro: 'El modelo entidad-relación, propuesto por Peter Chen, sigue siendo la herramienta clásica para el modelo conceptual:',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Entidad', 'Una cosa del dominio que se distingue de las demás (el Gol de Ana). El tipo de entidad es la categoría (Vehículo).'],
          ['Atributo', 'Una propiedad de la entidad. Puede ser simple o compuesto, monovaluado o multivaluado, almacenado o derivado.'],
          ['Identificador', 'El atributo o conjunto de atributos que distingue a cada entidad (la patente).'],
          ['Relación', 'Una asociación entre entidades (un cliente posee vehículos). El grado es la cantidad de entidades que participan.'],
          ['Cardinalidad', 'Cuántas entidades pueden relacionarse con cuántas: 1:1, 1:N o M:N.'],
          ['Participación', 'Si la relación es obligatoria (total) u opcional (parcial) para una entidad.'],
          ['Entidad débil', 'La que no puede identificarse sin otra entidad, su propietaria.'],
        ],
      },
      body: [
        { type: 'p', text: 'Con el vocabulario acordado, podemos darle forma: qué tiene identidad propia y cómo se relaciona con lo demás.' },
        { type: 'p', text: 'Evans agrega una distinción útil: una entidad tiene identidad y continuidad en el tiempo (un vehículo sigue siendo el mismo aunque lo pinten), mientras que un objeto de valor se define solo por sus atributos y es intercambiable (un rango horario de 9:00 a 10:00 es igual a cualquier otro de 9:00 a 10:00).' },
        { type: 'h3', text: '3.1 El modelo conceptual de Turnify' },
        { type: 'p', text: 'La figura usa la notación “pata de gallo”: dos rayas son “uno y solo uno”, un círculo con patas es “cero o muchos”, una raya con patas es “uno o muchos” y un círculo con una raya es “cero o uno”. Expresa lo mismo que las multiplicidades UML del Vol. 04.' },
        { type: 'p', text: 'Figura 3.1 — Modelo conceptual de Turnify.' },
        { type: 'p', text: 'Hay una relación nueva respecto del Vol. 04: Servicio y Recurso tienen una relación M:N (un servicio puede hacerse en varios recursos y un recurso admite varios servicios).' },
        { type: 'box', kind: 'el-caso', title: '¿El vehículo es atributo o entidad?', text: 'Es entidad. Tiene identidad propia (la patente), un ciclo de vida (puede cambiar de dueño), se relaciona con turnos y un cliente puede tener varios. Un atributo “vehículos del cliente” sería multivaluado, y eso es casi siempre la señal de que falta una entidad.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La pregunta no es “¿esto es una tabla?”, sino “¿esto tiene identidad propia en el negocio?”.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Empleados habilitados', text: 'Si cada empleado solo sabe operar algunos recursos, ¿qué relación agregarías a la figura 3.1? ¿Con qué cardinalidad y qué participación?' },
      ],
      fuentes: ['Elmasri y Navathe — modelo ER.', 'Evans, E. — Domain-Driven Design.'],
    },
    {
      id: '04',
      title: 'Reglas e invariantes',
      refrescoConceptos: {
        subtitulo: 'Restricciones de integridad',
        intro: 'En el Vol. 01 (cap. 07) vimos que una regla de negocio puede existir aunque nadie la haya escrito. Una invariante es una regla que tiene que ser verdadera siempre: antes y después de cada operación. El modelo relacional ofrece varios tipos de restricciones para hacerlas cumplir:',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['De dominio', 'Qué valores puede tomar una columna: su tipo y condiciones como CHECK (duracion_min > 0).'],
          ['NOT NULL', 'La columna siempre tiene que tener un valor.'],
          ['De clave (UNIQUE)', 'No puede haber dos filas con el mismo valor en esas columnas.'],
          ['De entidad', 'La clave primaria no puede ser nula ni repetirse.'],
          ['Referencial', 'Una clave foránea tiene que apuntar a una fila que exista.'],
          ['Sobre varias filas', 'Condiciones que comparan filas entre sí, como que dos turnos no se superpongan. Requieren mecanismos específicos (cap. 09).'],
        ],
      },
      body: [
        { type: 'p', text: 'Un modelo con entidades y relaciones todavía permite estados imposibles. Las reglas los prohíben.' },
        { type: 'h3', text: '4.1 Las reglas de Turnify' },
        { type: 'table', headers: ['Regla del negocio', 'Tipo', 'Cómo se hace cumplir'], rows: [
          ['Una patente identifica un único vehículo.', 'Clave', 'UNIQUE (patente)'],
          ['Todo turno tiene vehículo, servicio y recurso.', 'Obligatoriedad y referencial', 'NOT NULL + FOREIGN KEY'],
          ['El fin de un turno es posterior a su inicio.', 'Dominio', 'CHECK (fin > inicio)'],
          ['El estado es uno de los seis del Vol. 04.', 'Dominio', 'CHECK (estado IN (…))'],
          ['Un servicio solo se hace en recursos habilitados.', 'Referencial compuesta', 'FOREIGN KEY (servicio_id, recurso_id)'],
          ['Un recurso no tiene dos turnos activos superpuestos.', 'Sobre varias filas', 'EXCLUDE en PostgreSQL (cap. 09)'],
          ['El cliente cancela solo si faltan más de X horas.', 'Regla de proceso', 'Aplicación'],
          ['Las transiciones de estado siguen la figura 8.1 del Vol. 04.', 'Regla de proceso', 'Aplicación'],
        ] },
        { type: 'p', text: 'La regla de superposición es TRN-FR-002 del Vol. 02: la que desde entonces venimos marcando como capaz de cambiar la arquitectura.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una invariante que solo vive en la interfaz no es una invariante: es una sugerencia.' },
        { type: 'box', kind: 'atencion', title: null, text: 'No toda regla es una restricción de datos. La de las X horas depende del momento en que se ejecuta la operación, no de los datos guardados. Esa regla vive en la aplicación.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Clasificar reglas', text: 'Clasificá y decidí dónde se hace cumplir: “un cliente no puede tener dos turnos al mismo tiempo”; “el teléfono del cliente es obligatorio”; “un turno pendiente debe revisarse dentro de las 24 horas”.' },
      ],
      fuentes: ['Elmasri y Navathe — restricciones del modelo relacional.', 'PostgreSQL Documentation — Constraints.'],
    },
    {
      id: '05',
      title: 'Del dominio al modelo relacional',
      refrescoConceptos: {
        subtitulo: 'El modelo relacional',
        intro: 'Edgar Codd propuso en 1970 representar los datos como relaciones matemáticas. De ahí viene el vocabulario:',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Relación, tupla, atributo', 'Tabla, fila y columna, en el vocabulario formal.'],
          ['Dominio', 'El conjunto de valores posibles de un atributo.'],
          ['Clave candidata', 'Un conjunto mínimo de atributos que identifica cada fila. Puede haber varias.'],
          ['Clave primaria (PK)', 'La candidata elegida como identificador principal. Las demás son claves alternativas.'],
          ['Clave foránea (FK)', 'Columnas que referencian la clave de otra tabla y garantizan la integridad referencial.'],
          ['Clave natural o sustituta', 'La natural sale del negocio (la patente); la sustituta es un identificador técnico sin significado (un número generado).'],
          ['NULL', 'La ausencia de valor. Introduce una lógica de tres valores: NULL = NULL no es verdadero, es desconocido; por eso se pregunta IS NULL.'],
        ],
      },
      body: [
        { type: 'p', text: 'Tenemos conceptos, relaciones y reglas. Ahora hay que traducirlos al modelo que entienden las bases de datos relacionales.' },
        { type: 'h3', text: '5.1 Reglas de traducción' },
        { type: 'table', headers: ['En el modelo conceptual', 'En el modelo relacional'], rows: [
          ['Entidad', 'Una tabla con su clave primaria.'],
          ['Relación 1:N', 'Una clave foránea del lado N (vehiculo.cliente_id).'],
          ['Relación 1:1', 'Una clave foránea con UNIQUE en uno de los lados, preferentemente el de participación obligatoria.'],
          ['Relación M:N', 'Una tabla intermedia con clave primaria compuesta (servicio_recurso).'],
          ['Atributo multivaluado', 'Una tabla aparte.'],
          ['Entidad débil', 'Una tabla cuya clave primaria incluye la de su propietaria.'],
        ] },
        { type: 'p', text: 'Figura 5.1 — Esquema relacional de Turnify.' },
        { type: 'h3', text: '5.2 Decisiones de la traducción' },
        { type: 'p', text: 'El turno no guarda cliente_id. Se obtiene desde el vehículo. Guardarlo en los dos lados permitiría que no coincidan. Costo: si un vehículo cambia de dueño, sus turnos viejos pasan a mostrarse con el dueño nuevo. Es una decisión a validar con el negocio.' },
        { type: 'p', text: 'Claves sustitutas más patente única. Una patente mal cargada puede corregirse sin tocar las claves foráneas que la referencian.' },
        { type: 'p', text: 'Clave foránea compuesta hacia servicio_recurso. Hace cumplir, en la base, que un servicio solo se preste en recursos habilitados.' },
        { type: 'p', text: 'El fin se guarda aunque se pueda calcular. Si mañana cambia la duración de un servicio, los turnos pasados conservan la que tenían (cap. 07).' },
        { type: 'box', kind: 'atencion', title: null, text: 'La base no hace cumplir por sí sola el “1..*” del lado “uno”. Que todo cliente tenga al menos un vehículo (figura 3.1) no se expresa con una clave foránea: hay que resolverlo en la aplicación, por ejemplo registrando cliente y vehículo en la misma transacción.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Cada decisión de traducción debería poder explicarse con una regla o una pregunta del negocio.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Traducir una relación', text: 'Traducí la relación entre Empleado y Recurso de la práctica del cap. 03: ¿qué tabla agregarías, con qué claves y qué restricción nueva podría usar la tabla turno?' },
      ],
      fuentes: ['Elmasri y Navathe — traducción del modelo ER al relacional.', 'Silberschatz, Korth y Sudarshan — Database System Concepts.'],
    },
    {
      id: '06',
      title: 'Diseñar una base desde un caso real',
      refrescoConceptos: {
        subtitulo: 'El proceso de diseño',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Requisitos de datos', 'Qué información necesita el negocio. Sale de los Vol. 01 a 03.'],
          ['Diseño conceptual', 'Entidades, relaciones y reglas, independientes de la tecnología (caps. 02 a 04).'],
          ['Diseño lógico', 'La traducción al modelo relacional (cap. 05).'],
          ['Diseño físico', 'Tipos, índices y parámetros del motor concreto (cap. 10).'],
          ['DDL y DML', 'El lenguaje de definición (CREATE, ALTER) y el de manipulación (SELECT, INSERT, UPDATE, DELETE) de SQL.'],
        ],
      },
      body: [
        { type: 'p', text: 'Los capítulos anteriores fueron pasos sueltos. Juntémoslos en un proceso que se pueda repetir.' },
        { type: 'p', text: 'El proceso es iterativo: los datos de prueba y las primeras consultas suelen obligar a volver al modelo conceptual.' },
        { type: 'h3', text: '6.1 El DDL de Turnify' },
        { type: 'table', headers: ['DDL'], rows: [
          ["CREATE EXTENSION IF NOT EXISTS btree_gist;  -- necesaria para EXCLUDE (cap. 09) CREATE TABLE cliente (   id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   nombre    text NOT NULL,   telefono  text NOT NULL UNIQUE,   email     text ); CREATE TABLE vehiculo (   id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   cliente_id  bigint NOT NULL REFERENCES cliente (id),   patente     text NOT NULL UNIQUE,   descripcion text ); CREATE TABLE servicio (   id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   nombre            text NOT NULL UNIQUE,   duracion_min      integer NOT NULL CHECK (duracion_min > 0),   requiere_revision boolean NOT NULL DEFAULT false ); CREATE TABLE recurso (   id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   nombre  text NOT NULL UNIQUE ); CREATE TABLE servicio_recurso (   servicio_id bigint REFERENCES servicio (id),   recurso_id  bigint REFERENCES recurso (id),   PRIMARY KEY (servicio_id, recurso_id) ); CREATE TABLE empleado (   id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   nombre  text NOT NULL );"],
        ] },
        { type: 'table', headers: ['DDL'], rows: [
          ["CREATE TABLE turno (   id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   vehiculo_id  bigint NOT NULL REFERENCES vehiculo (id),   servicio_id  bigint NOT NULL,   recurso_id   bigint NOT NULL,   empleado_id  bigint REFERENCES empleado (id),   inicio       timestamptz NOT NULL,   fin          timestamptz NOT NULL,   estado       text NOT NULL CHECK (estado IN                  ('pendiente', 'confirmado', 'rechazado',                   'cancelado', 'atendido', 'no_presentado')),   creado_en    timestamptz NOT NULL DEFAULT now(),   CHECK (fin > inicio),   FOREIGN KEY (servicio_id, recurso_id)     REFERENCES servicio_recurso (servicio_id, recurso_id),   CONSTRAINT turno_sin_superposicion EXCLUDE USING gist (     recurso_id WITH =,     tstzrange(inicio, fin) WITH &&   ) WHERE (estado IN ('pendiente', 'confirmado')) );"],
        ] },
        { type: 'p', text: 'Cada línea del DDL se puede rastrear hasta una regla de la tabla 4.1. La última restricción la explicamos en el capítulo 09.' },
        { type: 'h3', text: '6.2 Datos de prueba que prueban algo' },
        { type: 'p', text: 'Los datos de prueba no son relleno: cada fila debería poner a prueba una regla o una consulta. Para Turnify conviene incluir un cliente con dos vehículos, un cliente sin turnos, un servicio que requiere revisión, un turno cancelado en un horario que después se vuelve a ocupar y turnos simultáneos en recursos distintos.' },
        { type: 'h3', text: '6.3 Decisiones documentadas' },
        { type: 'table', headers: ['Decisión', 'Alternativa descartada', 'Qué la haría cambiar'], rows: [
          ['El turno no guarda cliente_id.', 'Guardarlo y validar con una FK compuesta.', 'Que el negocio necesite conservar el dueño histórico.'],
          ['Estado como texto con CHECK.', 'Una tabla de estados.', 'Que los estados cambien seguido o tengan atributos propios.'],
          ['Cancelar cambia el estado; no se borra.', 'DELETE de la fila.', 'Una política de retención que exija eliminar (cap. 11).'],
          ['Un turno ocupa un solo recurso.', 'Una tabla turno_recurso.', 'El desafío del Vol. 04: servicios con varios recursos.'],
        ] },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un esquema es una hipótesis: los datos de prueba son la forma de ponerla a prueba antes que los usuarios.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Inserciones que deben fallar', text: 'Escribí tres INSERT que deberían fallar en este esquema y explicá qué restricción rechaza cada uno.' },
      ],
      fuentes: ['Elmasri y Navathe — proceso de diseño de bases de datos.', 'PostgreSQL Documentation — Data Definition; Identity Columns.'],
    },
    {
      id: '07',
      title: 'Normalización entendida desde los problemas',
      refrescoConceptos: {
        subtitulo: 'Dependencias y formas normales',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Redundancia', 'El mismo hecho guardado en más de un lugar.'],
          ['Anomalías', 'Problemas que causa la redundancia al insertar, actualizar o eliminar (ver 7.1).'],
          ['Dependencia funcional', 'X → Y: si dos filas coinciden en X, coinciden en Y. Por ejemplo, patente → cliente.'],
          ['1FN', 'Cada celda tiene un único valor atómico; no hay grupos repetidos.'],
          ['2FN', '1FN, y ningún atributo que no sea clave depende de solo una parte de una clave compuesta.'],
          ['3FN', '2FN, y ningún atributo que no sea clave depende de otro atributo que no sea clave (no hay dependencias transitivas).'],
          ['FNBC', 'Una versión más estricta de la 3FN: todo determinante es clave candidata.'],
          ['Desnormalización', 'Introducir redundancia a propósito, por ejemplo para acelerar lecturas, aceptando el costo de mantenerla.'],
        ],
      },
      body: [
        { type: 'p', text: '¿Por qué siete tablas y no una sola planilla, como la que usa hoy el lavadero? La normalización responde esa pregunta.' },
        { type: 'h3', text: '7.1 La planilla del lavadero' },
        { type: 'table', headers: ['fecha_hora', 'cliente', 'teléfono', 'patente', 'servicio', 'duración', 'box'], rows: [
          ['05/10 09:00', 'Ana Pérez', '2615550001', 'AB123CD', 'Lavado completo', '60', 'Box 1'],
          ['05/10 09:00', 'Bruno Díaz', '2615550002', 'AC456EF', 'Lavado exterior', '30', 'Box 2'],
          ['06/10 11:00', 'Ana Pérez', '2615550001', 'AB123CD', 'Lavado exterior', '30', 'Box 1'],
        ] },
        { type: 'p', text: 'Anomalía de actualización: si Ana cambia de teléfono, hay que corregir todas sus filas; si se olvida una, hay dos teléfonos.' },
        { type: 'p', text: 'Anomalía de inserción: no se puede registrar un servicio nuevo, con su duración, hasta que alguien reserve un turno.' },
        { type: 'p', text: 'Anomalía de eliminación: si se borra el único turno de tapizados, se pierde la duración del servicio.' },
        { type: 'p', text: 'Las dependencias explican por qué: patente → cliente, cliente → teléfono y servicio → duración. Son dependencias transitivas respecto del turno, y la 3FN pide separarlas en tablas propias. Eso es exactamente lo que hace el esquema de la figura 5.1.' },
        { type: 'p', text: 'Un ejemplo de 2FN: si servicio_recurso tuviera también la columna nombre_recurso, ese nombre dependería solo de recurso_id, que es parte de la clave compuesta.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Normalizar es poner cada hecho en un solo lugar.' },
        { type: 'box', kind: 'atencion', title: null, text: 'Desnormalizar puede ser razonable, pero no es gratis. Para reportes o lecturas muy frecuentes puede convenir copiar datos; alguien tiene que mantener esas copias sincronizadas.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: '¿El fin viola la 3FN?', text: 'La tabla turno guarda fin, que podría calcularse con inicio + duración del servicio. ¿Es redundancia? ¿Por qué decidimos guardarlo?' },
      ],
      fuentes: ['Elmasri y Navathe — dependencias funcionales y normalización.', 'Date, C. J. — An Introduction to Database Systems.'],
    },
    {
      id: '08',
      title: 'SQL: hablar con los datos',
      refrescoConceptos: {
        subtitulo: 'Cómo piensa una consulta',
        intro: 'SQL es declarativo: describe qué resultado se quiere, no cómo obtenerlo. El motor decide el cómo (cap. 10). Aunque se escriba empezando por SELECT, una consulta se evalúa lógicamente en este orden:\nFROM y JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT\nPor eso un alias definido en el SELECT no puede usarse en el WHERE: todavía no existe.',
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['INNER JOIN', 'Devuelve solo las filas que tienen pareja en las dos tablas.'],
          ['LEFT JOIN', 'Conserva todas las filas de la izquierda, aunque no tengan pareja; las columnas de la derecha quedan en NULL.'],
          ['Agregación', 'count, sum, avg… resumen varias filas en una. count(*) cuenta filas; count(columna) ignora los NULL.'],
          ['GROUP BY y HAVING', 'Agrupan filas; HAVING filtra grupos, después de agregar.'],
          ['Subconsulta y CTE', 'Una consulta dentro de otra. La CTE (WITH) le pone nombre para leerla mejor.'],
          ['Función de ventana', 'Calcula sobre un grupo de filas relacionadas (OVER, PARTITION BY) sin colapsarlas en una, como hace GROUP BY.'],
        ],
      },
      body: [
        { type: 'p', text: 'Con el esquema listo, podemos hacerle preguntas. SQL es el idioma para hacerlas.' },
        { type: 'h3', text: '8.1 Preguntas del negocio' },
        { type: 'p', text: 'El encargado: ¿qué turnos activos hay hoy, en qué recurso y con qué empleado?' },
        { type: 'table', headers: ['SQL'], rows: [
          ["SELECT t.inicio, r.nombre AS recurso, s.nombre AS servicio,        v.patente, e.nombre AS empleado, t.estado FROM turno t JOIN servicio s ON s.id = t.servicio_id JOIN recurso  r ON r.id = t.recurso_id JOIN vehiculo v ON v.id = t.vehiculo_id LEFT JOIN empleado e ON e.id = t.empleado_id   -- el pendiente no tiene empleado WHERE t.inicio >= '2026-10-05' AND t.inicio < '2026-10-06'   AND t.estado IN ('pendiente', 'confirmado') ORDER BY t.inicio, r.nombre;"],
        ] },
        { type: 'p', text: 'El dueño: ¿qué servicios tuvieron cancelaciones?' },
        { type: 'table', headers: ['SQL'], rows: [
          ["SELECT s.nombre, count(*) AS cancelaciones FROM turno t JOIN servicio s ON s.id = t.servicio_id WHERE t.estado = 'cancelado' GROUP BY s.nombre HAVING count(*) >= 1;"],
        ] },
        { type: 'p', text: 'Marketing: ¿qué clientes todavía no sacaron ningún turno?' },
        { type: 'table', headers: ['SQL'], rows: [
          ["SELECT c.nombre FROM cliente c LEFT JOIN vehiculo v ON v.cliente_id = c.id LEFT JOIN turno t    ON t.vehiculo_id = v.id GROUP BY c.id, c.nombre HAVING count(t.id) = 0;          -- count(t.id) ignora los NULL del LEFT JOIN"],
        ] },
        { type: 'p', text: 'El dueño: ¿cada cuánto vuelve cada cliente?' },
        { type: 'table', headers: ['SQL'], rows: [
          ["WITH turnos_cliente AS (   SELECT v.cliente_id, t.inicio,          lag(t.inicio) OVER (PARTITION BY v.cliente_id                              ORDER BY t.inicio) AS anterior   FROM turno t   JOIN vehiculo v ON v.id = t.vehiculo_id   WHERE t.estado IN ('confirmado', 'atendido') ) SELECT c.nombre, tc.inicio, tc.inicio - tc.anterior AS desde_el_anterior FROM turnos_cliente tc JOIN cliente c ON c.id = tc.cliente_id ORDER BY c.nombre, tc.inicio;"],
        ] },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Primero escribí la pregunta del negocio; después, la consulta.' },
        { type: 'box', kind: 'atencion', title: null, text: "Con fechas y horas, usá rangos semiabiertos. BETWEEN '2026-10-05' AND '2026-10-06' incluye la medianoche del día 6. La forma segura es inicio >= '2026-10-05' AND inicio < '2026-10-06'." },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Dos consultas', text: 'Escribí una consulta para cada pregunta: (a) turnos pendientes de revisión creados hace más de 24 horas; (b) tiempo ocupado de cada recurso por día durante octubre.' },
      ],
      fuentes: ['PostgreSQL Documentation — Queries; Table Expressions; Window Functions.', 'Silberschatz, Korth y Sudarshan — SQL.'],
    },
    {
      id: '09',
      title: 'Modificar información con consistencia',
      refrescoConceptos: {
        subtitulo: 'Transacciones y concurrencia',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Transacción', 'Una unidad de trabajo: un conjunto de operaciones que se confirman juntas (COMMIT) o se deshacen juntas (ROLLBACK).'],
          ['Atomicidad', 'Todo o nada: no quedan operaciones a medias.'],
          ['Consistencia', 'La transacción lleva la base de un estado válido a otro válido; las restricciones se respetan.'],
          ['Aislamiento', 'Las transacciones concurrentes no deberían ver los efectos intermedios de las otras.'],
          ['Durabilidad', 'Lo confirmado sobrevive a fallas.'],
          ['Anomalías', 'Lectura sucia, lectura no repetible, lectura fantasma y actualización perdida: lo que puede salir mal con poco aislamiento.'],
          ['Niveles de aislamiento', 'El estándar define cuatro: read uncommitted, read committed, repeatable read y serializable. PostgreSQL usa read committed por defecto.'],
        ],
      },
      body: [
        { type: 'p', text: 'Consultar no rompe nada. Modificar sí puede, sobre todo cuando dos personas lo hacen al mismo tiempo.' },
        { type: 'h3', text: '9.1 La doble reserva' },
        { type: 'p', text: 'Esta es la situación que venimos siguiendo desde el Vol. 02 (TRN-FR-002), el desvío 6b del CU-01 y el criterio CA-01.2 del Vol. 03. Una aplicación que primero verifica y después inserta tiene un problema de “verificar y actuar”:' },
        { type: 'p', text: 'Figura 9.1 — Dos transacciones reservan el mismo horario.' },
        { type: 'p', text: 'Las dos leen “no hay turnos” porque ninguna ve lo que la otra todavía no confirmó. Una transacción, por sí sola, no evita el problema.' },
        { type: 'table', headers: ['Estrategia', 'Cómo funciona', 'Cuándo conviene'], rows: [
          ['Restricción en la base', 'EXCLUDE rechaza la segunda inserción aunque la aplicación no haya visto el conflicto.', 'Cuando la regla se puede expresar como restricción. Es la más robusta.'],
          ['Bloqueo explícito', 'SELECT … FOR UPDATE sobre la fila del recurso hace que las reservas de ese recurso se hagan de a una.', 'Cuando la verificación es más compleja que una restricción.'],
          ['SERIALIZABLE y reintento', 'La base aborta una de las transacciones en conflicto; la aplicación la reintenta.', 'Cuando hay muchas reglas cruzadas.'],
          ['Validar solo en la aplicación', 'No alcanza: es exactamente la figura 9.1.', 'Nunca como única defensa.'],
        ] },
        { type: 'h3', text: '9.2 La restricción de exclusión' },
        { type: 'p', text: 'La restricción turno_sin_superposicion del DDL dice: no puede haber dos filas con el mismo recurso_id (=) cuyos rangos [inicio, fin) se superpongan (&&), considerando solo los turnos pendientes o confirmados. Es una restricción propia de PostgreSQL. Si la segunda transacción de la figura 9.1 intenta insertar, recibe este error:' },
        { type: 'table', headers: ['Error'], rows: [
          ['ERROR:  conflicting key value violates exclusion constraint "turno_sin_superposicion" -- SQLSTATE 23P01: la aplicación lo traduce al mensaje de CA-01.2 -- ("el horario ya no está disponible")'],
        ] },
        { type: 'p', text: 'Y como la condición solo mira los estados activos, cancelar un turno (un UPDATE del estado, no un DELETE) libera el horario automáticamente.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Verificar y después escribir no alcanza cuando dos personas hacen lo mismo al mismo tiempo.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Reprogramar sin perder el turno', text: 'Reprogramar un turno implica cancelar el actual y crear uno nuevo. Escribí la transacción. ¿Qué pasa con el turno original si el nuevo horario ya está ocupado?' },
      ],
      fuentes: ['PostgreSQL Documentation — Transactions; Transaction Isolation; Exclusion Constraints.', 'Silberschatz, Korth y Sudarshan — transacciones y control de concurrencia.'],
    },
    {
      id: '10',
      title: 'Rendimiento: cuando la consulta deja de ser gratis',
      refrescoConceptos: {
        subtitulo: 'Índices y planes',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Índice', 'Una estructura auxiliar que permite encontrar filas sin recorrer toda la tabla, como el índice de un libro.'],
          ['B-tree', 'El tipo de índice por defecto en PostgreSQL. Sirve para igualdades, rangos y ordenamientos.'],
          ['Selectividad', 'Qué proporción de filas devuelve un filtro. Un índice ayuda cuando el filtro es selectivo (pocas filas).'],
          ['Índice compuesto', 'Sobre varias columnas. El orden importa: (recurso_id, inicio) sirve para filtrar por recurso, o por recurso e inicio, pero no solo por inicio.'],
          ['Costo de escribir', 'Cada índice se actualiza en cada INSERT, UPDATE o DELETE y ocupa espacio.'],
          ['EXPLAIN', 'Muestra el plan que el motor piensa usar y su costo estimado, en unidades relativas.'],
          ['EXPLAIN ANALYZE', 'Ejecuta la consulta y muestra los tiempos reales.'],
        ],
      },
      body: [
        { type: 'p', text: 'Con cinco turnos, todo es rápido. Con tres años de historia, ya no.' },
        { type: 'h3', text: '10.1 Una medición real' },
        { type: 'p', text: 'Cargamos 65.717 turnos (tres años de historia) y consultamos la agenda de un día. Sin índice sobre inicio, el motor recorre la tabla entera:' },
        { type: 'table', headers: ['Plan'], rows: [
          ["Seq Scan on turno  (cost=0.00..1862.76 rows=11 width=33)   Filter: ((inicio >= '2026-10-05') AND (inicio < '2026-10-06'))"],
        ] },
        { type: 'p', text: 'Después de CREATE INDEX turno_inicio_idx ON turno (inicio):' },
        { type: 'table', headers: ['Plan'], rows: [
          ["Index Scan using turno_inicio_idx on turno  (cost=0.29..8.73 rows=17 width=33)   Index Cond: ((inicio >= '2026-10-05') AND (inicio < '2026-10-06')) Execution Time: 0.014 ms"],
        ] },
        { type: 'p', text: 'La restricción EXCLUDE ya había creado un índice GiST sobre (recurso_id, rango), pero no sirve para esta consulta, que filtra solo por inicio. Tampoco hay índices automáticos sobre las claves foráneas: PostgreSQL indexa las claves primarias y las columnas UNIQUE, pero no las columnas que referencian a otra tabla.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un índice es una hipótesis de rendimiento: se confirma con EXPLAIN, no con intuición.' },
        { type: 'box', kind: 'atencion', title: null, text: 'EXPLAIN ANALYZE ejecuta la consulta. Sobre un UPDATE o un DELETE, modifica datos de verdad. Para probar, envolvelo en BEGIN y ROLLBACK.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Antes de crear un índice', text: 'La consulta “clientes sin turnos” del cap. 08 tarda cada vez más. ¿Qué evidencia pedirías antes de crear un índice? ¿Sobre qué columnas lo considerarías?' },
      ],
      fuentes: ['PostgreSQL Documentation — Indexes; Using EXPLAIN.', 'Elmasri y Navathe — indexación.'],
    },
    {
      id: '11',
      title: 'Seguridad y ciclo de vida de los datos',
      refrescoConceptos: {
        subtitulo: 'Riesgos y controles',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['Inyección SQL', 'Ocurre cuando un dato que viene del usuario se concatena en el texto de una consulta y termina interpretándose como código SQL.'],
          ['Consulta parametrizada', 'La consulta y los datos viajan separados: el motor nunca interpreta el dato como código. Es la defensa principal que recomienda OWASP.'],
          ['Mínimo privilegio', 'Cada usuario de la base tiene solo los permisos que necesita.'],
          ['Minimización', 'Guardar solo los datos necesarios para el propósito.'],
          ['Auditoría', 'Registrar quién hizo qué y cuándo (el Vol. 02 pedía registrar quién cancela).'],
          ['Retención', 'Cuánto tiempo se conserva cada dato y qué pasa después.'],
        ],
      },
      body: [
        { type: 'p', text: 'Turnify guarda nombres, teléfonos y patentes. Eso lo vuelve responsable de protegerlos.' },
        { type: 'h3', text: '11.1 Parametrizar' },
        { type: 'table', headers: ['Código'], rows: [
          ["// Mal: el teléfono se concatena en el SQL db.query(\"SELECT * FROM cliente WHERE telefono = '\" + telefono + \"'\"); // Bien: el teléfono viaja como parámetro (node-postgres) db.query(\"SELECT id, nombre FROM cliente WHERE telefono = $1\", [telefono]);"],
        ] },
        { type: 'p', text: 'Fijate que la versión buena también deja de pedir *: devuelve solo las columnas que necesita.' },
        { type: 'h3', text: '11.2 Mínimo privilegio' },
        { type: 'table', headers: ['Código'], rows: [
          ['CREATE ROLE turnify_app LOGIN; GRANT SELECT, INSERT, UPDATE ON turno, cliente, vehiculo TO turnify_app; GRANT SELECT ON servicio, recurso, servicio_recurso, empleado TO turnify_app; -- Sin DELETE: cancelar es cambiar el estado. -- Sin permisos de DDL: la aplicación no crea ni modifica tablas.'],
        ] },
        { type: 'h3', text: '11.3 Datos personales' },
        { type: 'p', text: 'En Argentina, la Ley 25.326 de Protección de los Datos Personales regula cómo se recolectan, usan y conservan datos como el nombre, el teléfono o el email de los clientes. Para el análisis alcanza con hacerse tres preguntas por cada dato: ¿para qué lo necesito?, ¿quién puede verlo? y ¿cuándo deja de hacer falta?' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'El dato que no se guarda no se puede filtrar.' },
        { type: 'box', kind: 'atencion', title: null, text: 'Parametrizar no reemplaza la autorización. Una consulta perfectamente parametrizada puede devolver los turnos de otro cliente si nadie verifica quién la pide.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Una política de retención', text: 'Proponé qué hacer con los datos de un cliente que no saca turnos hace dos años y con los turnos atendidos hace más de cinco. ¿Qué preguntas le harías al dueño antes de decidir?' },
      ],
      fuentes: ['OWASP — SQL Injection Prevention Cheat Sheet; Query Parameterization Cheat Sheet; Database Security Cheat Sheet.', 'PostgreSQL Documentation — Database Roles; Privileges.', 'Ley 25.326 (Argentina).'],
    },
    {
      id: '12',
      title: 'Datos, APIs e integración',
      refrescoConceptos: {
        subtitulo: 'Exponer datos',
        intro: null,
        headers: ['Concepto', 'Qué significa'],
        rows: [
          ['DTO', 'Un objeto de transferencia de datos: la forma en que los datos salen del sistema, separada de cómo se guardan.'],
          ['Serialización', 'Convertir datos en un formato que puede viajar, como JSON.'],
          ['Identificadores expuestos', 'Los ids secuenciales permiten adivinar otros (el 42, el 43…). Esto obliga a verificar permisos siempre, uses o no identificadores aleatorios.'],
          ['Paginación', 'Devolver los resultados por partes: por desplazamiento (offset) o por cursor, que escala mejor en tablas grandes.'],
          ['Contrato de datos', 'El acuerdo sobre qué campos, tipos y significados devuelve la API. Cambiarlo afecta a quien la consume.'],
        ],
      },
      body: [
        { type: 'p', text: 'Los datos no se quedan en la base: viajan. El próximo volumen trata ese viaje; acá miramos qué datos salen.' },
        { type: 'h3', text: '12.1 Dos vistas del mismo turno' },
        { type: 'p', text: 'El encargado necesita la agenda con patentes y empleados. Un visitante que consulta disponibilidad no necesita saber nada de otros clientes:' },
        { type: 'table', headers: ['Respuesta'], rows: [
          ['GET /turnos?fecha=2026-10-05          (encargado autenticado) { "id": 1, "inicio": "2026-10-05T09:00:00-03:00", "estado": "confirmado",   "servicio": "Lavado completo", "recurso": "Box 1",   "patente": "AB123CD", "empleado": "Diego" } GET /disponibilidad?servicio=2&fecha=2026-10-05      (público) { "horarios": ["10:00", "10:30", "11:00"] }'],
        ] },
        { type: 'table', headers: ['Dato interno', '¿Se expone?', 'Por qué'], rows: [
          ['teléfono y email del cliente', 'Nunca en listados', 'Son datos personales; solo en el detalle, para quien tiene permiso.'],
          ['creado_en', 'No por defecto', 'Es un dato técnico; útil para auditoría, no para la agenda.'],
          ['empleado', 'Solo al encargado', 'El cliente no lo necesita para su turno.'],
          ['turnos de otros clientes', 'Nunca al público', 'La disponibilidad se deriva sin mostrarlos.'],
        ] },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La API expone un contrato, no la base de datos. Renombrar una columna no debería romper a nadie.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'El turno del cliente', text: 'Definí qué devuelve GET /mis-turnos para un cliente autenticado. ¿Qué campos incluís, cuáles no y qué pasa si pide un turno que no es suyo?' },
      ],
      fuentes: ['Fowler, M. — Patterns of Enterprise Application Architecture, Data Transfer Object.', 'OWASP — API Security Top 10.'],
    },
  ],
  cierre: {
    desafioIntegrador: {
      title: 'Desafío integrador: la capa de información de Turnify',
      body: [
        { type: 'p', text: 'La empresa ya tiene usuarios y servicios, pero los turnos se registran en una planilla. Hay que diseñar la primera versión de la capa de información.' },
        { type: 'p', text: 'Partí del dominio, no de las tablas: cada entregable debería poder justificarse con una regla, una pregunta del negocio o una decisión documentada.' },
        { type: 'h3', text: 'Preguntas de defensa' },
        { type: 'p', text: '¿Por qué existe cada entidad?' },
        { type: 'p', text: '¿Qué regla justifica cada restricción?' },
        { type: 'p', text: '¿Qué información se deriva y qué información se persiste?' },
        { type: 'p', text: '¿Qué ocurre si dos usuarios ejecutan la misma operación al mismo tiempo?' },
        { type: 'p', text: '¿Qué consulta podría volverse costosa cuando crezca el sistema?' },
        { type: 'p', text: '¿Qué datos no necesitás exponer aunque existan en la base?' },
      ],
      entregables: [
        { text: 'Un glosario mínimo del dominio.', capRef: '02' },
        { text: 'Un modelo conceptual con entidades, relaciones y cardinalidades.', capRef: '03' },
        { text: 'El listado de reglas e invariantes, con dónde se hace cumplir cada una.', capRef: '04' },
        { text: 'El modelo relacional con claves y restricciones.', capRef: '05' },
        { text: 'El DDL inicial, datos de prueba y decisiones documentadas.', capRef: '06' },
        { text: 'La justificación de las decisiones de normalización.', capRef: '07' },
        { text: 'Ocho consultas que respondan preguntas del negocio.', capRef: '08' },
        { text: 'Una operación crítica dentro de una transacción y el análisis de dos reservas concurrentes.', capRef: '09' },
        { text: 'Una consulta problemática, su plan y una hipótesis de optimización.', capRef: '10' },
        { text: 'Los riesgos de seguridad y sus controles.', capRef: '11' },
        { text: 'El mapa de datos que expondría una API.', capRef: '12' },
        { text: 'Preguntas abiertas y decisiones pendientes.', capRef: null },
      ],
      autoevaluacion: {
        headers: ['Nivel', 'Podés…', 'Indicador'],
        rows: [
          ['Conocer', 'explicar conceptos', 'Explicás entidad, atributo, PK, FK, JOIN, transacción e índice.'],
          ['Aplicar', 'construir', 'Construís un modelo, su DDL y consultas a partir de un caso.'],
          ['Analizar', 'justificar y detectar', 'Justificás decisiones, detectás inconsistencias y riesgos, y reconocés cuándo hace falta un especialista.'],
        ],
      },
    },
    mapaDeSalida: {
      ideas: [
        { text: 'La disponibilidad no se guarda: se deriva de otros datos.', capRef: '01' },
        { text: 'Un lenguaje compartido evita que el modelo tenga dos verdades.', capRef: '02' },
        { text: 'Lo que tiene identidad propia es entidad; lo que se define por sus atributos es valor.', capRef: '03' },
        { text: 'Una invariante que solo vive en la interfaz es una sugerencia.', capRef: '04' },
        { text: 'Cada decisión de traducción se explica con una regla del negocio.', capRef: '05' },
        { text: 'Normalizar es poner cada hecho en un solo lugar.', capRef: '07' },
        { text: 'Verificar y después escribir no alcanza con usuarios concurrentes.', capRef: '09' },
        { text: 'Un índice se justifica con EXPLAIN, no con intuición.', capRef: '10' },
        { text: 'La API expone un contrato, no la base de datos.', capRef: '12' },
      ],
      puente: {
        title: 'Puente al próximo volumen',
        text: 'Cuando el dato atraviesa una frontera del sistema aparecen contratos, APIs, integración, errores, idempotencia y consistencia distribuida. De eso trata el Vol. 06.',
      },
    },
    respuestasOrientativas: [
      { capId: '01', titulo: 'Guardado o derivado', nivel: 'Aplicar', respuesta: ['Se guardan los turnos, su estado, el empleado asignado y la fecha. Se deriva la cantidad por empleado y por mes. Falta un dato en la lista del caso: el empleado asignado a cada turno, que no hace falta para calcular disponibilidad pero sí para esta pregunta.'] },
      { capId: '02', titulo: 'Palabras del dominio', nivel: 'Aplicar', respuesta: ['Del dominio: turno, patente, box, cancelación, recurso, estado. De la interfaz: botón reservar, calendario, notificación push, pantalla de inicio de sesión. Estado: la etapa del ciclo de vida de un turno, que determina qué operaciones se permiten sobre él y si ocupa o no el recurso.'] },
      { capId: '03', titulo: 'Empleados habilitados', nivel: 'Analizar', respuesta: ['Una relación M:N “está habilitado para” entre Empleado y Recurso. Del lado del empleado, la participación probablemente sea obligatoria (todo empleado opera algo); del lado del recurso, depende: ¿puede existir un recurso que nadie sepa usar?'] },
      { capId: '04', titulo: 'Clasificar reglas', nivel: 'Aplicar', respuesta: [
        '“Un cliente no puede tener dos turnos al mismo tiempo”: sobre varias filas; como el turno no guarda cliente_id, requiere unir con vehículo, así que se resuelve en la aplicación con bloqueo o en un trigger. Además hay que validar si es una regla real: ¿y si trae dos autos?',
        '“El teléfono es obligatorio”: NOT NULL.',
        '“Un pendiente debe revisarse en 24 horas”: regla de proceso dependiente del tiempo; aplicación o tarea programada.',
      ] },
      { capId: '05', titulo: 'Traducir una relación', nivel: 'Aplicar', respuesta: ['Una tabla empleado_recurso (empleado_id, recurso_id) con clave primaria compuesta y dos claves foráneas. La tabla turno podría tener una clave foránea compuesta (empleado_id, recurso_id) hacia ella, para que no se asigne un empleado a un recurso que no sabe operar.'] },
      { capId: '06', titulo: 'Inserciones que deben fallar', nivel: 'Aplicar', respuesta: ['Una patente repetida (viola UNIQUE); un turno con fin anterior al inicio (viola el CHECK); un turno de tapizados en el Box 1 (viola la clave foránea compuesta hacia servicio_recurso). Las tres se probaron y fallan con esos errores.'] },
      { capId: '07', titulo: '¿El fin viola la 3FN?', nivel: 'Analizar', respuesta: ['No es redundancia real: el fin guardado registra la duración que tenía el servicio cuando se tomó el turno. Si se calculara con la duración actual, cambiar la duración de un servicio reescribiría el pasado. Es un hecho histórico, no una copia.'] },
      { capId: '08', titulo: 'Dos consultas', nivel: 'Aplicar', respuesta: ["-- (a) Pendientes creados hace más de 24 horas SELECT t.id, t.inicio, v.patente, t.creado_en FROM turno t JOIN vehiculo v ON v.id = t.vehiculo_id WHERE t.estado = 'pendiente'   AND t.creado_en < now() - interval '24 hours' ORDER BY t.creado_en; -- (b) Tiempo ocupado por recurso y por día, en octubre SELECT r.nombre AS recurso, t.inicio::date AS dia,        sum(t.fin - t.inicio) AS tiempo_ocupado FROM turno t JOIN recurso r ON r.id = t.recurso_id WHERE t.estado IN ('pendiente', 'confirmado', 'atendido')   AND t.inicio >= '2026-10-01' AND t.inicio < '2026-11-01' GROUP BY r.nombre, t.inicio::date ORDER BY dia, recurso;"] },
      { capId: '09', titulo: 'Reprogramar sin perder el turno', nivel: 'Analizar', respuesta: [
        "BEGIN; UPDATE turno SET estado = 'cancelado' WHERE id = 1 AND estado = 'confirmado'; INSERT INTO turno (vehiculo_id, servicio_id, recurso_id, empleado_id,                    inicio, fin, estado) VALUES (1, 2, 1, 1, '2026-10-05 11:00-03', '2026-10-05 12:00-03', 'confirmado'); COMMIT;",
        'Si el nuevo horario está ocupado, el INSERT falla por la restricción de exclusión, la transacción se deshace y el turno original sigue confirmado. Sin la transacción, el cliente se quedaría sin ninguno de los dos.',
      ] },
      { capId: '10', titulo: 'Antes de crear un índice', nivel: 'Analizar', respuesta: ['El plan con EXPLAIN (ANALYZE), cuántas filas tienen las tablas, cada cuánto se ejecuta la consulta y cuánto tarda. Como PostgreSQL no indexa las claves foráneas automáticamente, los candidatos naturales son vehiculo.cliente_id y turno.vehiculo_id, que son las columnas de los JOIN.'] },
      { capId: '11', titulo: 'Una política de retención', nivel: 'Aplicar', respuesta: ['Preguntas: ¿para qué se usan los datos de clientes inactivos?, ¿hay obligaciones contables que exijan conservar los turnos?, ¿alcanza con anonimizar (conservar el turno sin nombre ni teléfono) para las estadísticas? Una propuesta posible: anonimizar clientes inactivos a los dos años y conservar los turnos atendidos anonimizados.'] },
      { capId: '12', titulo: 'El turno del cliente', nivel: 'Aplicar', respuesta: ['Id, inicio, fin, estado, servicio y patente. Sin empleado, sin creado_en y sin datos de otros clientes. Si pide un turno que no es suyo, la API responde como si no existiera, para no confirmar que ese id es válido.'] },
    ],
    bibliografia: [
      'Elmasri, R. y Navathe, S. B. Fundamentals of Database Systems. Pearson.',
      'Silberschatz, A., Korth, H. F. y Sudarshan, S. Database System Concepts. McGraw-Hill.',
      'Date, C. J. An Introduction to Database Systems. Addison-Wesley.',
      'Evans, E. (2003). Domain-Driven Design: Tackling Complexity in the Heart of Software. Addison-Wesley.',
      'PostgreSQL Documentation 18: Data Definition; Constraints; Queries; Table Expressions; Window Functions; Transactions; Transaction Isolation; Indexes; Using EXPLAIN; Database Roles.',
      'OWASP. SQL Injection Prevention Cheat Sheet; Query Parameterization Cheat Sheet; Database Security Cheat Sheet.',
      'Fowler, M. “Ubiquitous Language”; “Bounded Context”. martinfowler.com.',
      'Chen, P. (1976). “The Entity-Relationship Model—Toward a Unified View of Data”. ACM Transactions on Database Systems.',
      'Codd, E. F. (1970). “A Relational Model of Data for Large Shared Data Banks”. Communications of the ACM.',
      'Fowler, M. (2002). Patterns of Enterprise Application Architecture. Addison-Wesley.',
      'Ley 25.326 de Protección de los Datos Personales (Argentina).',
      'OWASP. API Security Top 10.',
      'Object Management Group. Unified Modeling Language (UML), recursos y especificaciones oficiales.',
      'Los ejemplos, casos, consultas y ejercicios son elaboración didáctica propia. Las reglas de Turnify no deben leerse como requisitos de un sistema real.',
    ],
  },
}
