export default {
  id: '02',
  title: 'Ingeniería de requisitos',
  subtitle: 'De la necesidad a una especificación que se pueda construir, verificar y discutir',

  ficha: {
    proposito: 'Aprender a descubrir, expresar, analizar, validar y gestionar requisitos sin confundir necesidades con soluciones.',
    publico: 'Personas que recién empiezan a transformar conversaciones y problemas en especificaciones útiles.',
    competencias: 'Conocer, aplicar y analizar: necesidad, requisito y diseño; tipos de requisitos; funcionales y no funcionales; elicitación; redacción; criterios de aceptación; priorización y trazabilidad.',
    casoTransversal: 'Turnify, retomado del Vol. 01. Ahora pasamos de comprender el sistema a especificar qué debería cambiar.',
    metodo: 'Cada capítulo parte de una situación, introduce un concepto, lo aplica al caso y termina con una práctica.',
    lugarEnElTronco: '02 · Fundamentos. Requiere el Vol. 01. La salida del volumen es una primera especificación defendible y verificable.',
    nivel: null,
    requiere: 'Vol. 01',
    preparaPara: 'casos de uso · historias · criterios de aceptación · modelado · testing',
  },

  recorrido: [
    { chapterId: '01', title: 'De la necesidad al requisito', pregunta: '¿Qué estamos representando cuando decimos “requisito”?' },
    { chapterId: '02', title: 'Descubrir antes de escribir', pregunta: '¿Cómo obtenemos conocimiento que todavía no tenemos?' },
    { chapterId: '03', title: 'Preguntar bien', pregunta: '¿Cómo elicitar sin convertir la conversación en un interrogatorio?' },
    { chapterId: '04', title: 'Tipos de requisitos', pregunta: '¿Qué clase de necesidad estamos expresando?' },
    { chapterId: '05', title: 'Funcionales y no funcionales', pregunta: '¿Qué debe hacer el sistema y bajo qué condiciones?' },
    { chapterId: '06', title: 'Escribir requisitos claros', pregunta: '¿Cómo evitamos ambigüedad, mezcla y soluciones prematuras?' },
    { chapterId: '07', title: 'De la frase al criterio verificable', pregunta: '¿Cómo sabemos si un requisito se cumple?' },
    { chapterId: '08', title: 'Priorizar y negociar', pregunta: '¿Qué hacemos cuando no todo puede hacerse?' },
    { chapterId: '09', title: 'Trazabilidad y cambio', pregunta: '¿De dónde sale cada requisito y qué afecta si cambia?' },
    { chapterId: '10', title: 'Especificación inicial de Turnify', pregunta: '¿Podemos producir un conjunto coherente de requisitos?' },
  ],

  intro: {
    title: 'Antes de empezar',
    body: [
      { type: 'h3', text: 'Cómo leer este cuadernillo' },
      { type: 'p', text: 'Los recuadros cumplen la misma función que en el Vol. 01:' },
      {
        type: 'table',
        headers: [],
        rows: [
          ['IDEA CLAVE', 'La idea que tenés que llevarte del capítulo. Hay una sola por capítulo.'],
          ['EL CASO', 'Turnify y el lavadero: el ejemplo que acompaña toda la colección.'],
          ['PRACTICÁ', 'Un ejercicio, marcado con su nivel: conocer, aplicar o analizar. Las respuestas orientativas están al final.'],
          ['ATENCIÓN', 'Un error frecuente o una confusión que conviene evitar.'],
        ],
      },
      { type: 'p', text: 'Algunos términos de las fuentes se usan en inglés en la industria. La primera vez que aparecen, van entre paréntesis junto a su traducción. Las definiciones conceptuales remiten siempre a una fuente citada al final de cada capítulo; los ejemplos y ejercicios son elaboración didáctica propia.' },
      { type: 'p', text: 'En el Vol. 01 aprendimos a mirar un sistema antes de construir. Identificamos problema, contexto, stakeholders, procesos, reglas, información y frontera, y terminamos con una primera visión de Turnify.' },
      { type: 'p', text: 'Ahora aparece una pregunta inevitable: ¿cómo convertimos todo eso en algo que permita diseñar y construir una solución sin que cada persona entienda algo distinto? Ahí entran los requisitos.' },
      { type: 'box', kind: 'idea-clave', title: null, text: 'Un requisito no es simplemente una frase que alguien dijo. Es una representación utilizable de una necesidad: suficientemente clara para orientar decisiones y suficientemente verificable para discutir si fue satisfecha.' },
      { type: 'p', text: 'Este volumen no pretende enseñarte a “redactar frases lindas”. Pretende enseñarte a descubrir qué debe decirse, por qué, para quién, con qué nivel de detalle y cómo comprobar que lo entendimos.' },
      { type: 'box', kind: 'el-caso', title: 'Dónde retomamos a Turnify', text: 'Al final del Vol. 01 llegamos a esta visión: “Un sistema que permita gestionar la disponibilidad y asignación de turnos del lavadero, reduciendo conflictos de agenda y proporcionando a clientes, empleados y encargados la información necesaria para operar el proceso.” También quedaron preguntas abiertas: duraciones, recursos, cancelaciones, notificaciones, permisos. Este volumen las convierte, de a una, en requisitos.' },
    ],
  },

  chapters: [
    {
      id: '01',
      title: 'De la necesidad al requisito',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Una visión dice hacia dónde vamos. Un requisito dice qué tiene que ser cierto cuando lleguemos.' },
        { type: 'p', text: 'En el volumen anterior, el dueño decía: “Necesito una aplicación para gestionar los turnos”. Esa frase expresaba una solución propuesta. Detrás había una necesidad: un proceso confiable para gestionar disponibilidad y asignación. Ahora hay que representarla de una forma útil.' },
        { type: 'h3', text: '1.1 ¿Qué es un requisito?' },
        { type: 'p', text: 'IIBA define requisito (requirement) como una representación utilizable de una necesidad. Puede adoptar diferentes formas: un documento, un modelo, una historia, una regla, un criterio u otro artefacto apropiado al contexto. Lo importante es su función: representar qué necesita lograrse, no describir cómo construirlo. Por eso IIBA distingue entre requisitos, que representan necesidades, y diseños, que representan soluciones.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un requisito dice qué debe lograrse; un diseño, cómo lograrlo.' },
        { type: 'h3', text: '1.2 Necesidad, requisito y diseño' },
        {
          type: 'table',
          headers: ['Nivel', 'En Turnify', 'Pregunta que responde'],
          rows: [
            ['Necesidad', 'Reducir los conflictos de agenda.', '¿Qué problema o valor queremos abordar?'],
            ['Requisito', 'El sistema no deberá confirmar un turno si el recurso requerido ya está ocupado.', '¿Qué debe garantizarse?'],
            ['Diseño', 'Usar una tabla de disponibilidad con bloqueo transaccional.', '¿Cómo lo vamos a implementar?'],
          ],
        },
        { type: 'box', kind: 'atencion', title: null, text: 'Un requisito puede condicionar el diseño, pero no debe contenerlo.' },
        { type: 'h3', text: '1.3 La escalera de precisión' },
        { type: 'p', text: 'Una conversación puede empezar con “queremos menos conflictos” y terminar en requisitos verificables. El análisis consiste en reducir la ambigüedad sin inventar detalles:' },
        { type: 'p', text: 'Necesidad → objetivo → requisito → criterio de aceptación → verificación' },
        { type: 'p', text: 'Este volumen sube esa escalera: los capítulos 02 a 06 llegan al requisito bien escrito; el 07, al criterio y la verificación.' },
        { type: 'box', kind: 'practica', nivel: 'CONOCER', title: '¿Necesidad, requisito o diseño?', text: 'Clasificá estas frases: “quiero saber cuántos turnos tengo mañana”; “la aplicación tendrá un calendario mensual”; “el sistema deberá mostrar al encargado los turnos confirmados del día”.' },
      ],
      fuentes: [
        'IIBA — The Business Analysis Standard, 4.4 Understanding Requirements and Designs.',
        'IIBA — Global Business Analysis Core Standard, Requirements Classification Schema.',
      ],
    },
    {
      id: '02',
      title: 'Descubrir antes de escribir',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Para representar una necesidad, primero hay que conocerla. Y casi nunca la conocemos del todo al empezar.' },
        { type: 'p', text: 'Los requisitos no aparecen mágicamente cuando abrimos un documento. Primero necesitamos descubrir información: qué ocurre hoy, qué necesitan las personas, qué reglas existen, qué restricciones hay y qué cambio se busca. A esa actividad se la llama elicitación (elicitation).' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Elicitar no es pedirle al stakeholder que nos dicte requisitos. Es investigar para descubrir conocimiento que muchas veces nadie tiene ordenado.' },
        { type: 'h3', text: '2.1 Fuentes de conocimiento' },
        { type: 'p', text: 'Entrevistas y talleres; observación del trabajo real; documentación existente, formularios y planillas; sistemas actuales y sus reportes; métricas y análisis de datos; reclamos y tickets; prototipos. Cada fuente muestra una parte distinta de la realidad.' },
        { type: 'h3', text: '2.2 La evidencia importa' },
        { type: 'p', text: 'Si el encargado dice “todos quieren poder reservar 24/7”, todavía tenemos una afirmación que investigar. ¿Todos quiénes? ¿Hay datos que lo respalden? ¿Qué ocurre de madrugada? ¿Hay servicios que no pueden reservarse? ¿La disponibilidad es real o solo deseada?' },
        { type: 'h3', text: '2.3 Triangulación' },
        { type: 'p', text: 'Una práctica útil consiste en contrastar tres fuentes: lo que las personas dicen, lo que hacen y lo que los registros muestran. Cuando no coinciden, no elegimos una versión automáticamente: investigamos la diferencia. Es la misma actitud que en el Vol. 01 aplicamos a las perspectivas (cap. 09).' },
        { type: 'box', kind: 'el-caso', title: 'Tres versiones del mismo problema', text: 'El dueño dice que los empleados olvidan cargar turnos. Los empleados dicen que los clientes cambian horarios. La planilla muestra modificaciones frecuentes. Las tres piezas pueden ser verdaderas y describir partes distintas del problema.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Buscar evidencia', text: 'Elegí una funcionalidad de Turnify y proponé tres fuentes de evidencia que consultarías antes de convertirla en requisito.' },
      ],
      fuentes: [
        'IIBA — The Business Analysis Standard, prácticas de elicitación y trabajo con stakeholders.',
        'Sommerville, I. — Software Engineering, capítulo de ingeniería de requisitos.',
      ],
    },
    {
      id: '03',
      title: 'Preguntar bien',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'La entrevista es la fuente más usada y la más fácil de hacer mal. Vale la pena detenerse en ella.' },
        { type: 'p', text: 'Una buena entrevista no consiste en hacer veinte preguntas seguidas. Consiste en construir una conversación que permita descubrir objetivos, hechos, reglas, excepciones y criterios.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una pregunta útil abre información; una pregunta sesgada empuja al stakeholder hacia una solución.' },
        { type: 'h3', text: '3.1 Preguntas que abren y preguntas que empujan' },
        { type: 'p', text: 'Las preguntas de la izquierda son cerradas y, además, ya traen una solución adentro. Las de la derecha invitan a describir la situación.' },
        {
          type: 'table',
          headers: ['Empuja hacia una solución', 'Abre información'],
          rows: [
            ['¿Querés una app móvil?', '¿Cómo realizan hoy esta tarea y qué problema aparece?'],
            ['¿Te sirve recibir un email?', '¿Cómo te enterás actualmente de los cambios?'],
            ['¿Necesitás un botón para cancelar?', '¿En qué situaciones se cancela un turno y quién decide?'],
          ],
        },
        { type: 'h3', text: '3.2 Preguntas de profundización' },
        { type: 'p', text: '¿Podés darme un ejemplo?' },
        { type: 'p', text: '¿Qué pasa después?' },
        { type: 'p', text: '¿Siempre ocurre así? ¿Qué excepciones existen?' },
        { type: 'p', text: '¿Quién toma esa decisión y qué información necesita?' },
        { type: 'p', text: '¿Qué ocurre si no se puede hacer?' },
        { type: 'p', text: '¿Cómo sabríamos que esto funcionó bien?' },
        { type: 'p', text: 'La última pregunta es especial: su respuesta ya es el germen de un criterio de aceptación, que vamos a trabajar en el capítulo 07.' },
        { type: 'h3', text: '3.3 El silencio también informa' },
        { type: 'p', text: 'Cuando una persona tarda en responder “¿qué pasa si…?”, probablemente encontramos una zona poco definida. No hay que rellenarla con una suposición: hay que registrarla como incertidumbre y decidir cómo resolverla.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: '“Vemos qué hacemos”', text: 'El encargado dice: “Si un cliente llega tarde, vemos qué hacemos.” Escribí seis preguntas de profundización sin proponer todavía una solución.' },
      ],
      fuentes: [
        'IIBA — The Business Analysis Standard, técnica de entrevistas.',
        'Sommerville, I. — Software Engineering, ingeniería de requisitos.',
      ],
    },
    {
      id: '04',
      title: 'Tipos de requisitos',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ya sabemos cómo obtener información. Ahora necesitamos ordenarla: no todo lo que descubrimos es el mismo tipo de requisito.' },
        { type: 'p', text: 'Clasificar requisitos ayuda a no mezclar objetivos de negocio con capacidades del sistema y condiciones de calidad. El esquema de clasificación de IIBA distingue cuatro grandes categorías:' },
        {
          type: 'table',
          headers: ['Tipo', 'Qué representa', 'En Turnify'],
          rows: [
            ['De negocio (business)', 'Los objetivos y resultados que explican por qué se inicia el cambio.', 'Reducir los conflictos de asignación.'],
            ['De stakeholders', 'Las necesidades de los stakeholders para alcanzar los requisitos de negocio.', 'El encargado necesita conocer la agenda actualizada.'],
            ['De la solución (solution)', 'Las capacidades y cualidades de la solución. Incluye funcionales y no funcionales.', 'El sistema no deberá confirmar un turno ocupado.'],
            ['De transición (transition)', 'Capacidades temporales necesarias para pasar del estado actual al futuro.', 'Migrar los turnos futuros desde la planilla.'],
          ],
        },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Clasificar sirve para no mezclar el porqué, el qué y el cómo del cambio. Es una herramienta para ordenar el pensamiento, no una plantilla obligatoria. Un proyecto puede usar distintos artefactos y niveles de detalle.' },
        { type: 'box', kind: 'atencion', title: null, text: '“Requisito funcional” y “requisito de negocio” no son sinónimos. El primero describe un comportamiento o capacidad de la solución; el segundo explica por qué se inició el cambio.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Clasificar', text: 'Clasificá: “reducir un 20 % los conflictos”; “el encargado deberá poder reasignar un turno”; “la respuesta deberá producirse en menos de 2 segundos”; “capacitar a los encargados antes de la puesta en marcha”.' },
      ],
      fuentes: [
        'IIBA — Global Business Analysis Core Standard, Requirements Classification Schema.',
      ],
    },
    {
      id: '05',
      title: 'Funcionales y no funcionales',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Dentro de los requisitos de la solución hay una segunda distinción que vas a usar todos los días.' },
        { type: 'p', text: 'Los requisitos de la solución pueden describir capacidades funcionales o las cualidades y condiciones bajo las cuales la solución debe funcionar. IIBA ubica ambos dentro de los requisitos de la solución.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Lo funcional dice qué hace el sistema; lo no funcional, bajo qué condiciones debe hacerlo.' },
        { type: 'h3', text: '5.1 Funcional' },
        { type: 'p', text: 'Describe comportamiento o capacidad: qué debe hacer el sistema, qué información debe gestionar o qué respuesta debe producir ante una situación. En Turnify: crear un turno, consultar disponibilidad, cancelar una reserva, notificar un cambio, registrar una ausencia.' },
        { type: 'h3', text: '5.2 No funcional o de calidad' },
        { type: 'p', text: 'Describe condiciones o cualidades: rendimiento, disponibilidad, seguridad, usabilidad, compatibilidad, mantenibilidad u otras propiedades relevantes. ISO/IEC 25010 organiza estas cualidades en un modelo de calidad de producto. En Turnify: tiempo de respuesta, disponibilidad del servicio, control de acceso, registro de cambios, capacidad, protección de datos.' },
        { type: 'box', kind: 'atencion', title: null, text: '“No funcional” no significa “menos importante”. Un requisito de seguridad o de disponibilidad puede determinar la arquitectura, el costo y la viabilidad del proyecto.' },
        { type: 'h3', text: '5.3 La relación entre ambos' },
        { type: 'p', text: 'Una funcionalidad puede necesitar requisitos de calidad para ser útil. “Consultar turnos” es funcional; “la consulta deberá responder en X tiempo bajo Y condiciones” agrega una condición de rendimiento. En el próximo capítulo vamos a ver cómo escribir esa X y esa Y.' },
        { type: 'box', kind: 'practica', nivel: 'CONOCER', title: 'F o NF', text: 'Marcá F o NF: registrar un turno; respuesta en ≤ 2 s; autenticación con MFA para administradores; cancelar un turno; disponibilidad mensual del 99,5 %; exportar la agenda a CSV.' },
      ],
      fuentes: [
        'IIBA — Requirements Classification Schema.',
        'ISO/IEC 25010:2023 — Product quality model.',
      ],
    },
    {
      id: '06',
      title: 'Escribir requisitos claros',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Sabemos qué tipo de requisito tenemos entre manos. Falta escribirlo de modo que todos lo entiendan igual.' },
        { type: 'p', text: 'Un requisito mal escrito puede parecer preciso y, sin embargo, dejar varias interpretaciones posibles. La calidad del requisito depende tanto de su formulación como del análisis que lo sustenta. INCOSE señala que un enunciado puede estar bien formado y aun así no ser correcto ni factible: escribir requisitos es una actividad de ingeniería, no solo de redacción.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Claro no significa corto. Significa que personas diferentes pueden leerlo y llegar a la misma interpretación relevante.' },
        { type: 'h3', text: '6.1 Señales de alarma' },
        { type: 'p', text: 'Estas expresiones suelen esconder ambigüedad: “rápido”, “fácil de usar”, “intuitivo”, “cuando corresponda”, “adecuadamente”, “preferentemente”, “etc.” y “el usuario podrá gestionar…” sin decir qué significa gestionar.' },
        { type: 'h3', text: '6.2 De débil a verificable' },
        {
          type: 'table',
          headers: ['Débil', 'Más verificable'],
          rows: [
            ['El sistema debe ser rápido.', 'Para una consulta de disponibilidad, el sistema deberá devolver el resultado en ≤ 2 s bajo la carga definida para la operación.'],
            ['El usuario podrá gestionar turnos.', 'El encargado deberá poder crear, modificar, cancelar y consultar turnos dentro de su ámbito de permisos.'],
            ['La interfaz debe ser intuitiva.', 'Las tareas definidas como críticas deberán poder completarse por el perfil objetivo sin asistencia, en la prueba de aceptación definida.'],
          ],
        },
        { type: 'p', text: 'Fijate que las versiones verificables remiten a cosas que hay que definir (“la carga definida”, “las tareas críticas”). Eso no es un defecto: hace visible qué falta decidir, en lugar de esconderlo detrás de un adjetivo.' },
        { type: 'h3', text: '6.3 Un requisito, una idea comprobable' },
        { type: 'p', text: 'Cuando una frase contiene cinco comportamientos diferentes, conviene separarla. Esto facilita identificar quién lo necesita, cómo se verifica y qué cambia si una parte se modifica. Por la misma razón, conviene usar siempre la misma forma verbal: en esta colección, “deberá”.' },
        { type: 'h3', text: '6.4 Características de un buen requisito' },
        { type: 'p', text: 'ISO/IEC/IEEE 29148 propone características que cada requisito individual debería cumplir. Sirven como lista de revisión:' },
        {
          type: 'table',
          headers: ['Característica', 'Pregunta de revisión'],
          rows: [
            ['Necesario', '¿Qué se pierde si lo sacamos?'],
            ['Apropiado', '¿Tiene el nivel de detalle adecuado para su tipo?'],
            ['No ambiguo', '¿Admite una sola interpretación relevante?'],
            ['Completo', '¿Se entiende sin información que falta?'],
            ['Singular', '¿Expresa una sola idea comprobable?'],
            ['Factible', '¿Se puede lograr con las restricciones conocidas?'],
            ['Verificable', '¿Sabemos cómo comprobarlo?'],
            ['Correcto', '¿Representa fielmente la necesidad?'],
            ['Conforme', '¿Respeta el formato y las convenciones acordadas?'],
          ],
        },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Reescribir', text: 'Reescribí: “El sistema debe permitir gestionar turnos de forma rápida, fácil e intuitiva, enviando notificaciones cuando sea necesario.” Identificá al menos cuatro problemas de precisión.' },
      ],
      fuentes: [
        'INCOSE — Guide to Writing Requirements, v4 (2023).',
        'ISO/IEC/IEEE 29148:2018 — Requirements engineering.',
        'NASA — Systems Engineering Handbook, Appendix C: How to Write a Good Requirement.',
      ],
    },
    {
      id: '07',
      title: 'De la frase al criterio verificable',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Un requisito bien escrito todavía necesita algo más: una forma acordada de saber si se cumplió.' },
        { type: 'p', text: 'Un requisito útil necesita una forma de comprobarlo. NASA distingue verificación —comprobar que el producto cumple los requisitos— de validación —comprobar que se está produciendo el sistema correcto para las necesidades y expectativas del cliente—.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Si no podemos imaginar cómo comprobar un requisito, probablemente todavía no lo entendemos lo suficiente.' },
        { type: 'h3', text: '7.1 Criterios de aceptación' },
        { type: 'p', text: 'Un criterio de aceptación expresa una condición observable que permite determinar si una necesidad o un comportamiento fue satisfecho. No tiene que ser necesariamente un test automatizado, pero sí debe ser suficientemente concreto para que exista acuerdo sobre el resultado.' },
        { type: 'box', kind: 'el-caso', title: null, text: 'Requisito: el encargado deberá poder cancelar un turno confirmado. Criterios posibles: Solo los usuarios con permiso de gestión pueden cancelarlo. Al cancelarlo, el turno deja de ocupar disponibilidad. El sistema registra quién realizó la cancelación y cuándo. Si el cliente tiene un medio de contacto registrado, el sistema intenta notificarlo y registra el resultado del envío.' },
        { type: 'h3', text: '7.2 Verificación no es lo mismo que validación' },
        {
          type: 'table',
          headers: ['Concepto', 'Pregunta', 'En Turnify'],
          rows: [
            ['Verificación', '¿Construimos el producto de acuerdo con lo especificado?', '¿La cancelación registra usuario y fecha?'],
            ['Validación', '¿Lo construido resuelve la necesidad real?', '¿El proceso de cancelación le sirve al encargado y al cliente?'],
          ],
        },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Criterios para un aviso', text: 'Tomá “el sistema deberá avisar al cliente cuando se cancela un turno” y escribí cuatro criterios de aceptación.' },
      ],
      fuentes: [
        'NASA Software Engineering Handbook — Requirements Validation.',
        'NASA — Systems Engineering Handbook, Appendix D: Requirements Verification Matrix.',
      ],
    },
    {
      id: '08',
      title: 'Priorizar y negociar',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ahora tenemos requisitos claros y verificables. El problema es que casi nunca se pueden hacer todos a la vez.' },
        { type: 'p', text: 'En un proyecto real, descubrir requisitos no significa que todos puedan implementarse al mismo tiempo. La priorización conecta valor, riesgo, esfuerzo, dependencias y restricciones.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Priorizar no es decidir qué requisito “es más lindo”. Es decidir qué necesita atención primero, dadas las condiciones del proyecto.' },
        { type: 'h3', text: '8.1 ¿Qué podemos considerar?' },
        { type: 'p', text: 'Algunos criterios habituales: valor para el negocio, impacto en usuarios, riesgo, urgencia, dependencias, costo o esfuerzo, obligaciones legales o contractuales, impacto operacional e incertidumbre. Lo importante no es usarlos todos, sino hacer explícitos los que se usaron.' },
        { type: 'h3', text: '8.2 Negociar no es borrar' },
        { type: 'p', text: 'Cuando dos stakeholders piden cosas incompatibles, el analista no debería inventar un ganador. Debe hacer explícito el conflicto, investigar el objetivo detrás de cada pedido y ayudar a comparar alternativas.' },
        { type: 'box', kind: 'el-caso', title: 'Dos clics o revisión manual, otra vez', text: 'El conflicto que analizamos en el Vol. 01 (cap. 09) reaparece como requisito: el cliente quiere reservas sin revisión y el encargado necesita revisar servicios complejos. Una alternativa es separar tipos de servicio y aplicar revisión solo donde exista una regla operacional que la justifique.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Cinco de seis', text: 'Turnify tiene presupuesto para implementar solo cinco capacidades en la primera versión. Elegí criterios de priorización y justificá cómo ordenarías estas seis: reservar, cancelar, reprogramar, notificar, reportar ingresos y administrar disponibilidad.' },
      ],
      fuentes: [
        'IIBA — The Business Analysis Standard, priorización de requisitos.',
        'Sommerville, I. — Software Engineering.',
      ],
    },
    {
      id: '09',
      title: 'Trazabilidad y cambio',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Priorizar implica que algunos requisitos llegan más tarde, y mientras tanto otros cambian. Hace falta poder seguirles el rastro.' },
        { type: 'p', text: 'Los requisitos cambian. Una nueva regla puede afectar una historia, una API, una prueba, una tabla de datos y una decisión arquitectónica. La trazabilidad permite relacionar el origen y las consecuencias de esos cambios.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La trazabilidad no consiste en llenar planillas por obligación. Sirve para responder dos preguntas: “¿de dónde salió esto?” y “¿qué se rompe si cambia?”.' },
        { type: 'h3', text: '9.1 Una cadena posible' },
        { type: 'p', text: 'Objetivo → necesidad → requisito → diseño → implementación → prueba → resultado' },
        { type: 'p', text: 'NASA, por ejemplo, utiliza matrices de verificación que identifican cada requisito con un código único y lo relacionan con su fuente y con su método de verificación: inspección, análisis, demostración o prueba.' },
        { type: 'h3', text: '9.2 Identificadores' },
        { type: 'p', text: 'Para trazar hace falta nombrar. En Turnify usamos el formato TRN-[tipo]-[número], con las siglas en inglés que vas a encontrar en la industria: BR (negocio), SR (stakeholders), FR (funcional), NFR (no funcional) y TR (transición).' },
        {
          type: 'table',
          headers: ['ID', 'Requisito', 'Origen', 'Verificación'],
          rows: [
            ['TRN-FR-002', 'El sistema no deberá confirmar un turno cuando el recurso requerido esté ocupado.', 'Regla de negocio (Vol. 01, cap. 07)', 'Prueba'],
            ['TRN-FR-003', 'El encargado deberá poder cancelar turnos confirmados.', 'Stakeholder: encargado', 'Demostración y prueba'],
            ['TRN-FR-004', 'El sistema deberá registrar el usuario y la fecha de cada cancelación.', 'Necesidad de trazabilidad', 'Inspección y prueba'],
          ],
        },
        { type: 'h3', text: '9.3 Cambiar un requisito' },
        { type: 'p', text: 'Ante un cambio, preguntamos: ¿qué necesidad lo originó?, ¿qué stakeholders afecta?, ¿qué otros requisitos dependen de él?, ¿qué diseño podría cambiar?, ¿qué pruebas deben actualizarse?, ¿qué datos o integraciones están involucrados?' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Un turno, dos vehículos', text: 'La empresa decide que ahora un turno puede involucrar dos vehículos. Identificá al menos cinco elementos del sistema que podrían verse afectados.' },
      ],
      fuentes: [
        'NASA — Systems Engineering Handbook, Appendix D: Requirements Verification Matrix.',
        'ISO/IEC/IEEE 29148:2018 — Requirements engineering.',
      ],
    },
    {
      id: '10',
      title: 'Especificación inicial de Turnify',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Tenemos todas las herramientas. Es momento de usarlas juntas sobre el caso.' },
        { type: 'p', text: 'No buscamos una especificación gigantesca, sino que otra persona entienda qué problema se aborda, qué debe lograr la solución y cómo comprobaremos que cumple. La secuencia recorre el volumen completo: contexto → objetivos → stakeholders → requisitos → reglas → criterios → prioridades → trazabilidad.' },
        { type: 'h3', text: '10.1 Requisitos iniciales' },
        {
          type: 'table',
          headers: ['ID', 'Tipo', 'Requisito', 'Verificación'],
          rows: [
            ['TRN-BR-001', 'Negocio', 'Reducir los conflictos de asignación de turnos.', 'Validación con el dueño'],
            ['TRN-SR-001', 'Stakeholder', 'El encargado necesita consultar la agenda actualizada del día.', 'Validación con el encargado'],
            ['TRN-FR-001', 'Funcional', 'El sistema deberá permitir registrar un turno con cliente, servicio, horario y estado.', 'Prueba'],
            ['TRN-FR-002', 'Funcional', 'El sistema no deberá confirmar un turno cuando el recurso requerido esté ocupado.', 'Prueba'],
            ['TRN-FR-003', 'Funcional', 'El encargado deberá poder cancelar turnos confirmados.', 'Demostración y prueba'],
            ['TRN-NFR-001', 'No funcional', 'El 95 % de las consultas de disponibilidad deberá responder en ≤ 2 s con hasta [N] usuarios concurrentes. Valor de N a confirmar.', 'Prueba de carga'],
            ['TRN-TR-001', 'Transición', 'Antes de la puesta en marcha deberán migrarse los turnos futuros acordados desde la planilla.', 'Inspección'],
          ],
        },
        { type: 'h3', text: '10.2 Lo que todavía no sabemos' },
        { type: 'p', text: 'Duraciones exactas por servicio; reglas de disponibilidad de cada empleado; políticas de cancelación y de reprogramación; canales de notificación; roles y permisos definitivos; valores de rendimiento (por ejemplo, el N de TRN-NFR-001); política de migración de datos.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una especificación responsable también registra lo que todavía no sabemos. Inventar precisión para que parezca terminada es peor que dejar una pregunta explícita.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Revisar la especificación', text: 'Tomá el conjunto anterior y marcá qué requisitos necesitan más información, cuáles pueden verificarse ya y cuáles podrían cambiar la arquitectura.' },
      ],
      fuentes: [
        'IIBA — The Business Analysis Standard, requisitos y diseños.',
        'ISO/IEC/IEEE 29148:2018.',
        'NASA — Systems Engineering Handbook.',
      ],
    },
  ],

  cierre: {
    desafioIntegrador: {
      title: 'Desafío integrador: de la conversación a la especificación',
      body: [
        { type: 'p', text: 'La empresa del desafío del Vol. 01 vuelve con un pedido nuevo.' },
        { type: 'box', kind: 'el-caso', title: '“Que sea fácil, rápida, que mande avisos… y que tenga IA”', text: '“Queremos una app para gestionar turnos, que sea fácil de usar, rápida y que mande avisos. Además queremos que tenga IA para predecir los horarios con más demanda.”' },
        { type: 'box', kind: 'atencion', title: 'No copies la consigna.', text: 'Convertí la conversación en un conjunto de necesidades, requisitos, criterios y preguntas abiertas.' },
      ],
      entregables: [
        { text: 'Identificá las necesidades detrás de la consigna.', capRef: '01' },
        { text: 'Proponé las fuentes y preguntas con las que las confirmarías.', capRef: '02 y 03' },
        { text: 'Separá requisitos de negocio, de stakeholders, de la solución y de transición.', capRef: '04' },
        { text: 'Escribí al menos diez requisitos de la solución, funcionales y no funcionales.', capRef: '05' },
        { text: 'Detectá las expresiones ambiguas y reescribilas.', capRef: '06' },
        { text: 'Escribí criterios de aceptación para cinco requisitos.', capRef: '07' },
        { text: 'Priorizá los requisitos con criterios explícitos.', capRef: '08' },
        { text: 'Armá una matriz simple de trazabilidad con identificadores.', capRef: '09' },
        { text: 'Identificá al menos diez preguntas pendientes.', capRef: '10' },
        { text: 'Señalá qué decisiones no deberían tomarse todavía, por ejemplo sobre la IA, porque requieren análisis adicional.', capRef: null },
      ],
      autoevaluacion: {
        headers: ['Nivel', 'Podés…', 'Indicador'],
        rows: [
          ['Conocer', 'distinguir categorías', 'No confundís necesidad, requisito y diseño.'],
          ['Aplicar', 'redactar y estructurar', 'Producís requisitos con criterios verificables.'],
          ['Analizar', 'negociar y cuestionar', 'Detectás ambigüedad, conflictos, dependencias e incertidumbre.'],
        ],
      },
    },

    mapaDeSalida: {
      ideas: [
        { text: 'Un requisito representa una necesidad; no es un diseño.', capRef: '01' },
        { text: 'Elicitar es descubrir conocimiento, no pedirle al stakeholder que redacte la solución.', capRef: '02' },
        { text: 'Las buenas preguntas descubren hechos, reglas, objetivos, excepciones y criterios.', capRef: '03' },
        { text: 'Los requisitos existen en distintos niveles y categorías.', capRef: '04' },
        { text: 'Los requisitos funcionales describen capacidades; los no funcionales, cualidades y condiciones.', capRef: '05' },
        { text: 'Un requisito claro se interpreta de forma consistente y expresa una sola idea comprobable.', capRef: '06' },
        { text: 'Verificación y validación responden preguntas diferentes; los criterios de aceptación convierten expectativas en condiciones observables.', capRef: '07' },
        { text: 'Priorizar implica comparar valor, riesgo, esfuerzo, dependencias y restricciones.', capRef: '08' },
        { text: 'La trazabilidad conecta necesidades, requisitos, diseño y verificación.', capRef: '09' },
        { text: 'Una especificación responsable también hace visibles las incertidumbres.', capRef: '10' },
      ],
      puente: {
        title: 'Puente al próximo volumen',
        text: 'Ahora que podemos transformar necesidades en requisitos, el siguiente paso es convertirlos en comportamiento que se pueda discutir y verificar: historias de usuario, casos de uso y criterios de aceptación. Los modelos visuales (UML y BPMN) llegan en el Vol. 04.',
      },
    },

    respuestasOrientativas: [
      {
        capId: '01',
        titulo: '¿Necesidad, requisito o diseño?',
        nivel: 'Conocer',
        respuesta: [
          '“Quiero saber cuántos turnos tengo mañana”: necesidad (expresada por un stakeholder).',
          '“La aplicación tendrá un calendario mensual”: diseño; es una forma de presentar la información.',
          '“El sistema deberá mostrar al encargado los turnos confirmados del día”: requisito. Fijate que dice “del día” y la necesidad habla de mañana: vale la pena preguntar si alcanza.',
        ],
      },
      {
        capId: '02',
        titulo: 'Buscar evidencia',
        nivel: 'Aplicar',
        respuesta: [
          'Para “reservar en línea”, por ejemplo: entrevista al encargado, observación de cómo se toman los turnos hoy y análisis de la planilla histórica (cuántos turnos, en qué horarios, cuántas modificaciones).',
        ],
      },
      {
        capId: '03',
        titulo: '“Vemos qué hacemos”',
        nivel: 'Analizar',
        respuesta: [
          '¿Qué significa llegar tarde? ¿Hay una tolerancia?',
          '¿Quién decide qué hacer?',
          '¿Depende del servicio o del día?',
          '¿Qué pasa con el cliente: espera, se reprograma, pierde el turno?',
          '¿Se libera el recurso para otro cliente?',
          '¿Cómo sabrían que la forma de resolverlo funcionó bien?',
        ],
      },
      {
        capId: '04',
        titulo: 'Clasificar',
        nivel: 'Aplicar',
        respuesta: [
          '“Reducir un 20 % los conflictos”: de negocio.',
          '“El encargado deberá poder reasignar un turno”: de la solución, funcional. Si estuviera escrito como “el encargado necesita reasignar turnos”, sería de stakeholders: la forma de redacción importa.',
          '“La respuesta deberá producirse en menos de 2 segundos”: de la solución, no funcional.',
          '“Capacitar a los encargados antes de la puesta en marcha”: de transición.',
        ],
      },
      {
        capId: '05',
        titulo: 'F o NF',
        nivel: 'Conocer',
        respuesta: [
          'Funcionales: registrar un turno, cancelar un turno, exportar la agenda a CSV. No funcionales: respuesta en ≤ 2 s, MFA para administradores, disponibilidad del 99,5 %.',
        ],
      },
      {
        capId: '06',
        titulo: 'Reescribir',
        nivel: 'Analizar',
        respuesta: [
          '“Rápida”, “fácil”, “intuitiva” y “cuando sea necesario” son ambiguos; “gestionar” no dice qué acciones incluye; mezcla varios comportamientos en un solo enunciado; no define quién recibe las notificaciones, por qué medio ni en qué situaciones.',
        ],
      },
      {
        capId: '07',
        titulo: 'Criterios para un aviso',
        nivel: 'Aplicar',
        respuesta: [
          'El aviso se envía cuando el estado del turno pasa a cancelado.',
          'Incluye fecha, hora y servicio del turno cancelado.',
          'Se envía por el medio de contacto registrado del cliente.',
          'Se registra si el envío fue exitoso o falló.',
        ],
      },
      {
        capId: '08',
        titulo: 'Cinco de seis',
        nivel: 'Analizar',
        respuesta: [
          'No existe un orden universal. Una respuesta defendible explicita los criterios: por ejemplo, “administrar disponibilidad” va primero porque las demás dependen de ella, y “reportar ingresos” queda afuera porque no ataca el problema de negocio (los conflictos de agenda).',
        ],
      },
      {
        capId: '09',
        titulo: 'Un turno, dos vehículos',
        nivel: 'Aplicar',
        respuesta: [
          'Reglas de disponibilidad, modelo de datos, interfaz de reserva, API, criterios de aceptación y pruebas, reportes y la regla de definición “un turno corresponde a un único vehículo” del Vol. 01.',
        ],
      },
      {
        capId: '10',
        titulo: 'Revisar la especificación',
        nivel: 'Analizar',
        respuesta: [
          'Necesitan más información: TRN-NFR-001 (falta N) y TRN-FR-002 (qué es un “recurso”). Pueden verificarse ya: TRN-FR-001 y TRN-FR-003. Podrían cambiar la arquitectura: TRN-NFR-001 y TRN-FR-002, por la concurrencia.',
        ],
      },
    ],

    bibliografia: [
      'IIBA — The Business Analysis Standard.',
      'IIBA — Global Business Analysis Core Standard, Requirements Classification Schema.',
      'INCOSE — Guide to Writing Requirements, v4 (2023).',
      'ISO/IEC 25010:2023 — Systems and software Quality Requirements and Evaluation (SQuaRE) — Product quality model.',
      'ISO/IEC/IEEE 29148:2018 — Systems and software engineering — Life cycle processes — Requirements engineering.',
      'NASA — Systems Engineering Handbook, Appendix C: How to Write a Good Requirement, y Appendix D: Requirements Verification Matrix.',
      'NASA — Software Engineering Handbook, Requirements Validation.',
      'Sommerville, I. Software Engineering, 10.ª ed. Pearson.',
      'INCOSE Requirements Management Working Group — Characteristics of Good Requirements.',
    ],
  },
}
