export default {
  id: "07",
  title: "Arquitectura",
  subtitle: "Las decisiones que sostienen un sistema en el tiempo",
  ficha: {
    proposito: "Reconocer, tomar, comunicar y documentar decisiones arquitectónicas a partir de los atributos de calidad que el negocio necesita.",
    publico: "Estudiantes que ya pasaron por requisitos, modelado, datos y APIs. Cada capítulo abre con un refresco de los conceptos que usa.",
    competencias: "Conocer, aplicar y analizar: atributos de calidad y escenarios; vistas y C4; estilos; capas y puertos; modularidad; datos y comunicación; despliegue; observabilidad; seguridad; registros de decisiones.",
    casoTransversal: "Turnify completo. El volumen reúne las decisiones de los Vol. 01 a 06 y las ordena en una arquitectura.",
    metodo: "Cada capítulo empieza con un refresco de conceptos, los aplica a Turnify y termina con una práctica.",
    lugarEnElTronco: "07 · Fundamentos. Requiere los Vol. 01 a 06 y cierra el tronco.",
    nivel: 'Intermedio',
    requiere: 'Vol. 01 a 06',
    preparaPara: null,
    cierraTronco: true,
  },
  recorrido: [
    { chapterId: "01", title: "¿Qué es arquitectura?", pregunta: "¿Qué decisiones son arquitectónicas y cuáles no?" },
    { chapterId: "02", title: "Atributos de calidad", pregunta: "¿Qué tiene que hacer bien el sistema, y cómo lo medimos?" },
    { chapterId: "03", title: "Vistas y el modelo C4", pregunta: "¿Cómo mostramos la arquitectura a distintas personas?" },
    { chapterId: "04", title: "Estilos arquitectónicos", pregunta: "¿Monolito o microservicios?" },
    { chapterId: "05", title: "Capas, puertos y adaptadores", pregunta: "¿Dónde viven las reglas de negocio?" },
    { chapterId: "06", title: "Modularidad", pregunta: "¿Cómo dividimos el sistema para que cada parte cambie sola?" },
    { chapterId: "07", title: "Los datos en la arquitectura", pregunta: "¿Una base o varias?" },
    { chapterId: "08", title: "Comunicación entre componentes", pregunta: "¿Cuándo esperar y cuándo avisar?" },
    { chapterId: "09", title: "Despliegue y escalabilidad", pregunta: "¿Dónde corre el sistema y cómo crece?" },
    { chapterId: "10", title: "Observabilidad y operación", pregunta: "¿Cómo sabemos si funciona?" },
    { chapterId: "11", title: "Seguridad como propiedad", pregunta: "¿Cómo se protege el sistema entero, no solo cada parte?" },
    { chapterId: "12", title: "Decisiones y evolución", pregunta: "¿Cómo registramos lo que decidimos y cómo lo cambiamos?" },
  ],
  intro: {
    title: "Sobre este volumen",
    body: [
      { type: "p", text: "A lo largo de la colección tomamos muchas decisiones sobre Turnify: qué entra en el sistema, qué requisitos importan, cómo se comporta, cómo se guardan los datos y qué contrato expone. Algunas de esas decisiones son fáciles de cambiar; otras condicionan todo lo demás. Este volumen trata de estas últimas: la arquitectura." },
      { type: "box", kind: "idea-clave", title: null, text: "La arquitectura no es un diagrama de cajas. Es el conjunto de decisiones que, si hubiera que cambiarlas, costarían mucho. El diagrama solo las comunica." },
      { type: "h3", text: "El recorrido" },
      { type: "p", text: "Los capítulos 01 a 03 definen qué es la arquitectura y cómo se comunica; del 04 al 08, las decisiones de estructura; del 09 al 11, las de operación; el 12 enseña a registrarlas y a hacerlas evolucionar." },
      { type: "h3", text: "Cómo leer este cuadernillo" },
      { type: "p", text: "Los recuadros cumplen la misma función que en los volúmenes anteriores, y cada capítulo abre con un Refresco de conceptos, como en los Vol. 05 y 06." },
      {
        type: "table",
        headers: [],
        rows: [
          ["IDEA CLAVE", "La idea que tenés que llevarte del capítulo. Hay una sola por capítulo."],
          ["EL CASO", "Turnify y el lavadero: el ejemplo que acompaña toda la colección."],
          ["PRACTICÁ", "Un ejercicio, marcado con su nivel: conocer, aplicar o analizar. Las respuestas orientativas están al final."],
          ["ATENCIÓN", "Un error frecuente o una confusión que conviene evitar."],
        ],
      },
      { type: "p", text: "Las definiciones remiten a una fuente citada al final de cada capítulo; los ejemplos, diagramas y ejercicios son elaboración didáctica propia." },
    ],
  },
  chapters: [
    {
      id: "01",
      title: "¿Qué es arquitectura?",
      refrescoConceptos: {
        intro: "No hay una única definición, pero las más citadas coinciden en lo esencial. Para Bass, Clements y Kazman, la arquitectura de un sistema es el conjunto de estructuras necesarias para razonar sobre él: elementos de software, las relaciones entre ellos y las propiedades de ambos.",
        subtitulo: null,
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Arquitectura (ISO 42010)", "Los conceptos o propiedades fundamentales de un sistema en su entorno, y los principios que guían su construcción y su evolución."],
          ["Decisión arquitectónica", "Una decisión que afecta la estructura del sistema o sus atributos de calidad y que es costosa de revertir."],
          ["Diseño", "Las decisiones de menor alcance, que pueden cambiarse sin afectar al resto del sistema."],
          ["Compromiso (trade-off)", "Mejorar una cualidad suele empeorar otra. Elegir una arquitectura es elegir qué compromisos se aceptan."],
        ],
      },
      body: [
        { type: "p", text: "En el Vol. 02 marcamos dos requisitos como capaces de cambiar la arquitectura. Es hora de explicar qué quería decir eso." },
        { type: "p", text: "Richards y Ford lo resumen en una frase que conviene recordar: en arquitectura de software, todo es un compromiso." },
        { type: "box", kind: "el-caso", title: "Decisiones de Turnify, grandes y chicas", text: "Usar una restricción de exclusión en PostgreSQL para impedir la doble reserva (Vol. 05) es arquitectónica: ata la regla de negocio más importante a un motor de base de datos concreto y a tener una sola base. Llamar a una columna duracion_min en lugar de duracion es de diseño: cambiarla cuesta poco. Exponer los identificadores como texto en la API (Vol. 06) está en el medio: es fácil hoy, pero cada consumidor nuevo la vuelve más difícil de cambiar." },
        { type: "box", kind: "idea-clave", title: null, text: "Una decisión es arquitectónica si cambiarla después cuesta mucho." },
        { type: "box", kind: "practica", nivel: "CONOCER", title: "¿Arquitectura o diseño?", text: "Clasificá estas decisiones de Turnify: usar PostgreSQL; nombrar el endpoint /turnos; cancelar cambiando el estado en lugar de borrar; usar React en el panel; usar claves de idempotencia en POST /turnos." },
      ],
      fuentes: [
        "ISO/IEC/IEEE 42010:2022 — Architecture description.",
        "Bass, L., Clements, P. y Kazman, R. — Software Architecture in Practice.",
        "Richards, M. y Ford, N. — Fundamentals of Software Architecture.",
      ],
    },
    {
      id: "02",
      title: "Atributos de calidad y escenarios",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Calidad",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Atributo de calidad", "Una propiedad medible del sistema que indica qué tan bien satisface a sus stakeholders: rendimiento, disponibilidad, seguridad, facilidad de cambio. ISO/IEC 25010 las organiza en un modelo (Vol. 02, cap. 05)."],
          ["Requisito significativo para la arquitectura", "Un requisito que tiene un efecto profundo en la arquitectura. Suelen ser requisitos de calidad, pero también restricciones del negocio o del equipo."],
          ["Restricción", "Una decisión ya tomada que no se discute: el presupuesto, el equipo disponible, una tecnología obligatoria."],
          ["Escenario de calidad", "Una forma de volver medible un atributo, con seis partes: fuente, estímulo, entorno, artefacto, respuesta y medida de la respuesta."],
        ],
      },
      body: [
        { type: "p", text: "Si la arquitectura consiste en elegir compromisos, primero hay que saber qué cualidades importan y cuánto." },
        { type: "h3", text: "2.1 Un escenario para Turnify" },
        { type: "p", text: "La plantilla de escenarios de calidad obliga a convertir “tiene que ser rápido” en algo que se pueda comprobar. Tomemos TRN-NFR-001 del Vol. 02, que dejó abierto el valor de N:" },
        {
          type: "table",
          headers: ["Parte", "En Turnify"],
          rows: [
            ["Fuente", "Clientes desde la app."],
            ["Estímulo", "Consultan disponibilidad y reservan."],
            ["Entorno", "Sábado de 9 a 11, la hora pico: hasta N = 30 usuarios simultáneos (valor acordado con el dueño)."],
            ["Artefacto", "La API de Turnify y su base de datos."],
            ["Respuesta", "Devuelve la disponibilidad y confirma las reservas sin doble asignación."],
            ["Medida", "El 95 % de las consultas responde en 2 segundos o menos; cero turnos superpuestos."],
          ],
        },
        { type: "box", kind: "atencion", title: null, text: "El N = 30 es un ejemplo. En un proyecto real sale de los datos del negocio (¿cuántos turnos se toman un sábado?), no de una suposición del analista." },
        { type: "h3", text: "2.2 Las cualidades que importan en Turnify" },
        {
          type: "table",
          headers: ["Atributo", "Por qué importa", "Prioridad"],
          rows: [
            ["Integridad de datos", "Una doble reserva es el problema que originó todo el proyecto (Vol. 01).", "Alta"],
            ["Facilidad de cambio", "El equipo es chico y el negocio todavía está descubriendo sus reglas (las X horas, el N).", "Alta"],
            ["Disponibilidad", "Si Turnify no responde, el lavadero vuelve a WhatsApp; es molesto, pero no grave.", "Media"],
            ["Rendimiento", "El volumen es bajo: decenas de usuarios, no miles.", "Media"],
            ["Escalabilidad", "Un lavadero no crece de 30 a 30.000 clientes en un año.", "Baja"],
          ],
        },
        { type: "box", kind: "idea-clave", title: null, text: "Una arquitectura se juzga contra los atributos que el negocio prioriza, no contra una lista ideal." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "Un escenario de disponibilidad", text: "Escribí un escenario de calidad completo para esta situación: el servicio de mensajería deja de responder durante una hora." },
      ],
      fuentes: [
        "Bass, L., Clements, P. y Kazman, R. — Software Architecture in Practice, escenarios de calidad.",
        "ISO/IEC 25010:2023 — Product quality model.",
      ],
    },
    {
      id: "03",
      title: "Vistas y el modelo C4",
      refrescoConceptos: {
        intro: "En el Vol. 01 (cap. 09) vimos que cada stakeholder mira el sistema desde una perspectiva. ISO/IEC/IEEE 42010 formaliza esa idea:",
        subtitulo: "Vistas",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Interés (concern)", "Algo que le importa a un stakeholder: el costo, la seguridad, cuánto tarda una reserva."],
          ["Punto de vista (viewpoint)", "Las convenciones para construir un tipo de vista: qué se muestra y con qué notación."],
          ["Vista (view)", "Una representación del sistema desde un punto de vista, que responde a ciertos intereses."],
          ["Modelo C4", "Una propuesta de Simon Brown para mostrar la arquitectura en cuatro niveles de zoom: contexto, contenedores, componentes y código."],
        ],
      },
      body: [
        { type: "p", text: "Las decisiones solo sirven si se pueden explicar. Y cada persona necesita verlas desde un lugar distinto." },
        { type: "h3", text: "3.1 Nivel 1: el contexto" },
        { type: "p", text: "Muestra el sistema como una caja, rodeado de las personas y los sistemas con los que interactúa. Es el diagrama para el dueño del lavadero." },
        { type: "p", text: "Figura 3.1 — Diagrama de contexto de Turnify (C4, nivel 1)." },
        { type: "h3", text: "3.2 Nivel 2: los contenedores" },
        { type: "p", text: "Abre la caja de Turnify y muestra sus partes ejecutables: aplicaciones, procesos y bases de datos. Es el diagrama para el equipo técnico." },
        { type: "p", text: "Figura 3.2 — Contenedores de Turnify (C4, nivel 2)." },
        { type: "box", kind: "atencion", title: null, text: "En C4, “contenedor” no significa contenedor de Docker. Es cualquier cosa que se ejecuta o guarda datos por separado: una aplicación web, una API, un proceso, una base." },
        { type: "p", text: "Los niveles 3 (componentes) y 4 (código) se usan solo cuando hacen falta. El capítulo 05 muestra algo parecido a un nivel 3 para la API." },
        { type: "box", kind: "idea-clave", title: null, text: "Un buen diagrama de arquitectura tiene un público y una pregunta, igual que cualquier modelo del Vol. 04." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "¿Qué diagrama para quién?", text: "¿Qué diagrama le mostrarías a cada uno? El dueño, que quiere saber si puede cobrar seña; un desarrollador nuevo; alguien de seguridad que revisa por dónde entran los datos." },
      ],
      fuentes: [
        "ISO/IEC/IEEE 42010:2022.",
        "Brown, S. — The C4 model for visualising software architecture, c4model.com.",
      ],
    },
    {
      id: "04",
      title: "Estilos arquitectónicos",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Estilos",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Monolito", "El sistema se construye y despliega como una sola unidad. Simple de desarrollar, probar y operar; puede volverse difícil de cambiar si nadie cuida sus límites internos."],
          ["Monolito modular", "Una sola unidad de despliegue, pero dividida en módulos con límites claros y dependencias controladas (cap. 06)."],
          ["Microservicios", "Servicios pequeños, desplegables por separado, cada uno con sus propios datos, que se comunican por la red."],
          ["Monolito distribuido", "El peor de los dos mundos: servicios separados que igual tienen que desplegarse juntos porque dependen fuertemente entre sí."],
          ["Ley de Conway", "Las organizaciones diseñan sistemas que copian su estructura de comunicación (Conway, 1968)."],
        ],
      },
      body: [
        { type: "p", text: "La figura 3.2 dice “monolito modular”. Es una elección, y hay otras." },
        { type: "h3", text: "4.1 El compromiso" },
        {
          type: "table",
          headers: ["Cualidad", "Monolito modular", "Microservicios"],
          rows: [
            ["Simplicidad de operación", "Alta: un despliegue, una base.", "Baja: muchos despliegues, red, monitoreo distribuido."],
            ["Consistencia de datos", "Transacciones locales (Vol. 05, cap. 09).", "Consistencia eventual entre servicios."],
            ["Despliegue independiente", "No: se despliega todo junto.", "Sí: cada servicio por separado."],
            ["Escalar partes por separado", "No.", "Sí."],
            ["Equipos independientes", "Difícil con muchos equipos.", "Pensado para eso."],
          ],
        },
        { type: "p", text: "Las ventajas de los microservicios aparecen cuando hay muchos equipos, partes con cargas muy distintas o necesidad de desplegar por separado. Martin Fowler sugiere empezar por un monolito y separar servicios solo cuando los límites están claros y la necesidad es real." },
        { type: "box", kind: "el-caso", title: "¿Y Turnify?", text: "Un equipo chico, carga baja, reglas todavía en descubrimiento y una regla central (la no superposición) que depende de una transacción en una sola base. Todos los atributos priorizados en el cap. 02 apuntan a un monolito modular." },
        { type: "box", kind: "idea-clave", title: null, text: "Elegí el estilo por los atributos que el negocio necesita, no por el que está de moda." },
        { type: "box", kind: "practica", nivel: "ANALIZAR", title: "¿Cuándo separar?", text: "Imaginá que Turnify se vende a 200 lavaderos. ¿Qué módulo sería el primer candidato para convertirse en un servicio aparte? ¿Qué señal te lo indicaría?" },
      ],
      fuentes: [
        "Richards, M. y Ford, N. — Fundamentals of Software Architecture, estilos.",
        "Lewis, J. y Fowler, M. (2014). “Microservices”, martinfowler.com.",
        "Conway, M. E. (1968). “How Do Committees Invent?”.",
      ],
    },
    {
      id: "05",
      title: "Capas, puertos y adaptadores",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Organizar el interior",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Arquitectura en capas", "El código se divide en capas (presentación, aplicación, dominio, infraestructura) y cada una solo depende de las de abajo."],
          ["Puertos y adaptadores", "También llamada hexagonal (Alistair Cockburn). El núcleo define interfaces (puertos) para lo que necesita del exterior; los adaptadores las implementan con una tecnología concreta."],
          ["Regla de dependencia", "Las dependencias del código apuntan hacia el núcleo: el dominio no conoce la base de datos ni HTTP (Robert C. Martin, Clean Architecture)."],
          ["Caso de uso (aplicación)", "Orquesta una operación: recibe la intención, usa el dominio y los puertos, y devuelve un resultado. Es el CU-01 del Vol. 03 hecho código."],
        ],
      },
      body: [
        { type: "p", text: "Dentro de la API, ¿dónde vive la regla “no confirmar un horario ocupado”? La respuesta organiza todo el código." },
        { type: "p", text: "Figura 5.1 — Puertos y adaptadores en la API de Turnify." },
        { type: "p", text: "El caso de uso ReservarTurno no sabe si los turnos se guardan en PostgreSQL ni si los avisos salen por una bandeja de salida: habla con dos puertos. Eso permite probar la lógica de reserva sin base de datos y cambiar la tecnología sin tocar las reglas." },
        { type: "box", kind: "el-caso", title: "¿Dónde vive la regla de no superposición?", text: "En dos lugares, a propósito. El dominio la conoce y la verifica para dar un buen mensaje (CA-01.2). La base la garantiza con la restricción de exclusión, porque es la única que ve las transacciones concurrentes (Vol. 05, cap. 09). Es una defensa en profundidad, no una duplicación accidental." },
        { type: "box", kind: "atencion", title: null, text: "Las capas no son gratis. Para un CRUD simple (el alta de un empleado), atravesar cuatro capas puede ser burocracia. Aplicá la separación donde hay reglas que proteger." },
        { type: "box", kind: "idea-clave", title: null, text: "Las reglas de negocio no deberían depender de la base de datos ni del framework: son lo que menos debería cambiar." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "Un adaptador nuevo", text: "Turnify empieza a aceptar reservas por WhatsApp con un bot. ¿Qué parte de la figura 5.1 cambia y qué parte queda igual?" },
      ],
      fuentes: [
        "Cockburn, A. — “Hexagonal Architecture”.",
        "Martin, R. C. (2017). Clean Architecture. Prentice Hall.",
      ],
    },
    {
      id: "06",
      title: "Modularidad: cohesión y acoplamiento",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Módulos",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Módulo", "Una parte del sistema con una responsabilidad y una interfaz, que esconde sus detalles al resto."],
          ["Ocultamiento de información", "Cada módulo esconde las decisiones que probablemente cambien (Parnas, 1972). Es el criterio clásico para cortar."],
          ["Cohesión", "Qué tan relacionadas están las cosas dentro de un módulo. Se busca alta."],
          ["Acoplamiento", "Cuánto depende un módulo de los detalles de otro. Se busca bajo."],
          ["Contexto delimitado", "El límite de un modelo con su propio lenguaje (Vol. 05, cap. 02). Es un buen candidato a límite de módulo."],
        ],
      },
      body: [
        { type: "p", text: "Un monolito modular solo es modular si sus módulos están bien cortados. ¿Por dónde se corta?" },
        { type: "p", text: "Figura 6.1 — Módulos de Turnify y sus dependencias." },
        { type: "p", text: "Cada módulo agrupa tablas del esquema del Vol. 05 que cambian juntas. Reservas es el núcleo: depende de Catálogo (duraciones y recursos habilitados), de Clientes y de Personal, pero ninguno de ellos depende de Reservas. Notificaciones no recibe llamadas: escucha eventos (la línea punteada), así que Reservas no sabe quién se entera de una cancelación." },
        { type: "box", kind: "atencion", title: null, text: "Un módulo no debería leer las tablas de otro directamente. Si Reservas consulta la tabla servicio con su propio SQL, cualquier cambio en Catálogo puede romperla. Lo pide a través de la interfaz de Catálogo." },
        { type: "box", kind: "idea-clave", title: null, text: "Cortá donde cambian las cosas: lo que cambia junto va junto." },
        { type: "box", kind: "practica", nivel: "ANALIZAR", title: "Un módulo nuevo", text: "Si en una versión futura se agrega el cobro de seña, ¿es un módulo nuevo o parte de Reservas? ¿De quién dependería y quién dependería de él?" },
      ],
      fuentes: [
        "Parnas, D. L. (1972). “On the Criteria To Be Used in Decomposing Systems into Modules”. Communications of the ACM.",
        "Evans, E. (2003). Domain-Driven Design.",
      ],
    },
    {
      id: "07",
      title: "Los datos en la arquitectura",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Datos distribuidos",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Base compartida", "Varios módulos o servicios usan la misma base. Permite transacciones que abarcan a todos, pero acopla sus esquemas."],
          ["Base por servicio", "Cada servicio es dueño de sus datos y nadie más los toca. Da independencia, pero pierde las transacciones entre servicios."],
          ["Consistencia fuerte", "Después de una escritura, cualquier lectura ve el valor nuevo."],
          ["Consistencia eventual", "Las copias terminan coincidiendo, pero durante un tiempo pueden diferir."],
          ["Saga", "Una secuencia de transacciones locales, cada una con una acción que la compensa si algo falla más adelante."],
        ],
      },
      body: [
        { type: "p", text: "Los módulos separan el código. ¿También hay que separar los datos?" },
        { type: "box", kind: "el-caso", title: "¿Qué pasaría si Reservas y Catálogo tuvieran bases separadas?", text: "La clave foránea compuesta hacia servicio_recurso (Vol. 05, cap. 05) ya no existiría: Reservas tendría que consultar a Catálogo y confiar en la respuesta. Y si alguien deshabilita un recurso mientras se reserva, no hay transacción que proteja las dos cosas a la vez." },
        { type: "p", text: "Por eso la decisión del cap. 04 y la del Vol. 05 están atadas: la regla más importante de Turnify se apoya en una transacción local sobre una base. Separar esa base es posible, pero obliga a reemplazar una restricción de la base por una coordinación entre servicios, que es más difícil de hacer bien." },
        { type: "p", text: "Una solución intermedia, compatible con el monolito modular, es una sola base con esquemas separados por módulo y la regla de que cada módulo solo escribe en su esquema." },
        { type: "box", kind: "idea-clave", title: null, text: "Separar datos es fácil; separar las garantías que daban juntos, no." },
        { type: "box", kind: "practica", nivel: "ANALIZAR", title: "Una lectura desactualizada", text: "El panel muestra la agenda a partir de una copia que se actualiza cada minuto. ¿Qué problema puede ver el encargado? ¿Para qué pantallas es aceptable y para cuáles no?" },
      ],
      fuentes: [
        "Kleppmann, M. — Designing Data-Intensive Applications.",
        "Richardson, C. — “Saga”, microservices.io.",
      ],
    },
    {
      id: "08",
      title: "Comunicación entre componentes",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Síncrono y asíncrono",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Síncrono", "El que llama espera la respuesta (una llamada HTTP). Simple de razonar; acopla en el tiempo (Vol. 06, cap. 09)."],
          ["Asíncrono", "El que envía no espera: deja un mensaje y sigue. Desacopla, pero el resultado llega después."],
          ["Cola de mensajes", "Un intermediario que guarda mensajes hasta que un consumidor los procesa. Cada mensaje lo procesa un solo consumidor."],
          ["Publicar y suscribir", "Un evento se publica una vez y le llega a todos los suscriptores interesados."],
          ["Bandeja de salida (outbox)", "Guardar el mensaje en la misma transacción que el cambio de datos y enviarlo después (Vol. 06, cap. 11)."],
        ],
      },
      body: [
        { type: "p", text: "El Vol. 06 mostró las llamadas síncronas y los webhooks. Acá los miramos como decisión de arquitectura." },
        { type: "box", kind: "el-caso", title: "Los avisos de Turnify", text: "En la figura 3.2, la API no llama a la mensajería: guarda el evento en la base, en la misma transacción que la reserva o la cancelación. El procesador de avisos lo lee y lo envía. Si la mensajería se cae, las reservas siguen funcionando y los avisos salen cuando vuelve." },
        { type: "p", text: "Turnify no necesita todavía un intermediario de mensajes dedicado: con su volumen, una tabla en PostgreSQL y un proceso que la lee alcanzan. Si mañana hubiera muchos consumidores de eventos, la bandeja de salida se podría publicar en un intermediario sin cambiar el módulo de Reservas." },
        { type: "box", kind: "idea-clave", title: null, text: "Usá comunicación síncrona cuando el negocio necesita la respuesta ahora; en los demás casos, avisá." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "¿Síncrono o asíncrono?", text: "Decidí y justificá: verificar la disponibilidad; avisar al encargado de una reserva pendiente; cobrar la seña antes de confirmar; actualizar el calendario externo." },
      ],
      fuentes: [
        "Hohpe, G. y Woolf, B. — Enterprise Integration Patterns.",
        "Richardson, C. — “Transactional Outbox”, microservices.io.",
      ],
    },
    {
      id: "09",
      title: "Despliegue y escalabilidad",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Infraestructura",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Entornos", "Copias separadas del sistema: desarrollo, pruebas y producción. Lo que se prueba en uno debería comportarse igual en otro."],
          ["Plataforma como servicio (PaaS)", "Un proveedor ejecuta la aplicación y se ocupa de los servidores; el equipo solo despliega el código."],
          ["Escalado vertical", "Una máquina más grande."],
          ["Escalado horizontal", "Más instancias iguales detrás de un balanceador. Requiere que la aplicación no guarde estado entre solicitudes."],
          ["Configuración externa", "Lo que cambia entre entornos (credenciales, direcciones) se guarda fuera del código, en variables de entorno (The Twelve-Factor App)."],
          ["Integración y despliegue continuos", "Cada cambio se compila, se prueba y se despliega de forma automática."],
        ],
      },
      body: [
        { type: "p", text: "Hasta ahora, Turnify era un conjunto de decisiones. Para funcionar, tiene que correr en algún lado." },
        { type: "p", text: "Figura 9.1 — Despliegue de Turnify." },
        { type: "p", text: "Hay dos instancias de la API porque HTTP no guarda estado (Vol. 06, cap. 02): cualquier instancia puede atender cualquier solicitud, y si una se cae, la otra sigue. La base es un servicio gestionado, con copias de seguridad automáticas: para un equipo chico, operar su propia base es un riesgo que no hace falta correr." },
        { type: "box", kind: "atencion", title: null, text: "La restricción de exclusión funciona igual con dos instancias. Como las dos escriben en la misma base, la doble reserva sigue siendo imposible. Si cada instancia verificara la disponibilidad en memoria, no lo sería." },
        { type: "box", kind: "idea-clave", title: null, text: "Una API sin estado es la condición para escalar agregando instancias." },
        { type: "box", kind: "practica", nivel: "ANALIZAR", title: "El sábado a la mañana", text: "El dueño lanza una promoción y la carga se multiplica por diez los sábados. ¿Qué escala primero en la figura 9.1? ¿Qué parte podría convertirse en el cuello de botella?" },
      ],
      fuentes: [
        "Wiggins, A. — The Twelve-Factor App, 12factor.net.",
        "Bass, Clements y Kazman — despliegue y escalabilidad.",
      ],
    },
    {
      id: "10",
      title: "Observabilidad y operación",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Observar un sistema",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Registros (logs)", "Mensajes sobre lo que ocurrió, con fecha y contexto; mejor si son estructurados (JSON)."],
          ["Métricas", "Números agregados en el tiempo: solicitudes por minuto, errores, latencia."],
          ["Trazas", "El recorrido de una solicitud por todos los componentes, con cuánto tardó en cada uno."],
          ["SLI", "Indicador de nivel de servicio: una medida concreta, como el porcentaje de reservas que responden en menos de 2 s."],
          ["SLO y presupuesto de error", "El SLO es el valor que el SLI tiene que alcanzar (95 %). El presupuesto de error es lo que permite fallar: un 99,5 % mensual admite unas 3,6 horas sin servicio al mes."],
        ],
      },
      body: [
        { type: "p", text: "Turnify ya está en producción. ¿Cómo sabemos si cumple el escenario del cap. 02?" },
        { type: "h3", text: "10.1 Los SLO de Turnify" },
        {
          type: "table",
          headers: ["SLI", "SLO", "De dónde sale"],
          rows: [
            ["Consultas de disponibilidad que responden en 2 s o menos", "95 % en la hora pico", "TRN-NFR-001 (Vol. 02) y el escenario del cap. 02"],
            ["Solicitudes a la API que no terminan en error 5xx", "99,5 % mensual", "La disponibilidad del Vol. 02 (cap. 05)"],
            ["Avisos enviados dentro de los 5 minutos", "99 %", "El procesador de avisos (cap. 08)"],
          ],
        },
        { type: "p", text: "Cada SLO conecta la operación con un requisito. Si el presupuesto de error se agota, la prioridad pasa de las funciones nuevas a la estabilidad." },
        { type: "box", kind: "atencion", title: null, text: "Alertá por síntomas, no por causas. “La CPU está al 80 %” puede no afectar a nadie; “las reservas tardan 5 segundos”, sí. Conviene alertar cuando un SLO está en riesgo." },
        { type: "box", kind: "idea-clave", title: null, text: "Si no se puede medir, no se puede saber si la arquitectura cumple lo que prometía." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "Una traza", text: "¿Qué pasos debería mostrar la traza de un POST /turnos, desde el balanceador hasta el aviso?" },
      ],
      fuentes: [
        "Beyer, B., Jones, C., Petoff, J. y Murphy, N. R. (eds.) — Site Reliability Engineering.",
        "OpenTelemetry — documentación.",
      ],
    },
    {
      id: "11",
      title: "Seguridad como propiedad del sistema",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Seguridad arquitectónica",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Frontera de confianza", "El punto donde los datos pasan de una zona a otra con distinto nivel de confianza, como del celular del cliente a la API."],
          ["Defensa en profundidad", "Varias capas de control independientes, para que la falla de una no alcance."],
          ["Mínimo privilegio y secretos", "Cada componente tiene solo los permisos que necesita (Vol. 05, cap. 11), y las credenciales no van en el código: se guardan en la configuración del entorno o en un servicio de secretos."],
          ["Modelado de amenazas", "Analizar el diseño buscando qué podría salir mal. STRIDE es una guía de seis categorías: suplantación, manipulación, repudio, divulgación de información, denegación de servicio y elevación de privilegios."],
        ],
      },
      body: [
        { type: "p", text: "El Vol. 05 protegió los datos y el Vol. 06 protegió la API. La arquitectura mira cómo se protegen juntos." },
        { type: "h3", text: "11.1 Las fronteras de Turnify" },
        {
          type: "table",
          headers: ["Frontera", "Amenaza (STRIDE)", "Control"],
          rows: [
            ["App → API", "Suplantación: alguien usa el token de otro.", "HTTPS, tokens con vencimiento (Vol. 06, cap. 06)."],
            ["App → API", "Divulgación: ver turnos ajenos.", "Autorización por objeto (Vol. 06, cap. 06)."],
            ["API → base", "Manipulación: inyección SQL.", "Consultas parametrizadas y rol sin DELETE (Vol. 05, cap. 11)."],
            ["Turnify → calendario", "Suplantación: un tercero envía avisos falsos.", "Firma de los webhooks (Vol. 06, cap. 11)."],
            ["Todo el sistema", "Repudio: nadie sabe quién canceló.", "Registro de quién y cuándo (Vol. 02, TRN-FR-004)."],
          ],
        },
        { type: "p", text: "Casi todos los controles ya estaban en volúmenes anteriores. La arquitectura no los inventa: verifica que cubran todas las fronteras." },
        { type: "box", kind: "idea-clave", title: null, text: "La seguridad de un sistema es la de su frontera más débil." },
        { type: "box", kind: "practica", nivel: "ANALIZAR", title: "Una amenaza más", text: "Aplicá la categoría de denegación de servicio a Turnify. ¿Qué frontera es la más expuesta y qué control propondrías?" },
      ],
      fuentes: [
        "Shostack, A. — Threat Modeling: Designing for Security.",
        "OWASP — Threat Modeling Cheat Sheet.",
      ],
    },
    {
      id: "12",
      title: "Decisiones y evolución",
      refrescoConceptos: {
        intro: null,
        subtitulo: "Registrar y evolucionar",
        headers: ["Concepto", "Qué significa"],
        rows: [
          ["Registro de decisión (ADR)", "Un documento corto que registra una decisión arquitectónica: su contexto, la decisión, su estado y sus consecuencias (Michael Nygard, 2011)."],
          ["Estado", "Propuesta, aceptada, reemplazada. Un ADR no se borra: si la decisión cambia, se escribe uno nuevo que lo reemplaza."],
          ["Deuda técnica", "El costo futuro de una decisión que conviene hoy. Como una deuda financiera, puede ser razonable si se toma a conciencia y se paga."],
          ["Función de aptitud", "Una verificación automática de que la arquitectura sigue cumpliendo un atributo: una prueba de carga, una regla que impide que un módulo lea tablas de otro (Ford, Parsons y Kua)."],
        ],
      },
      body: [
        { type: "p", text: "Tomamos muchas decisiones en este volumen. Dentro de un año, alguien va a preguntar por qué. Hay que dejar la respuesta escrita." },
        { type: "h3", text: "12.1 Dos decisiones de Turnify" },
        {
          type: "box",
          kind: "adr",
          title: "ADR-001 · Monolito modular con una sola base PostgreSQL",
          text: "Estado: aceptada (septiembre de 2026)\nContexto\nEquipo chico, carga baja (N = 30 en la hora pico), reglas todavía en descubrimiento. La regla de no superposición necesita una transacción local (Vol. 05).\nDecisión\nUna API desplegable como unidad, dividida en los módulos de la figura 6.1, con una sola base PostgreSQL y un esquema por módulo.\nConsecuencias\n+ Transacciones locales y una operación simple.\n+ Se puede separar un módulo más adelante si hace falta.\n- No se puede escalar ni desplegar un módulo por separado.\n- Hay que cuidar los límites entre módulos (función de aptitud).",
        },
        {
          type: "box",
          kind: "adr",
          title: "ADR-002 · La base garantiza la no superposición de turnos",
          text: "Estado: aceptada (septiembre de 2026)\nContexto\nTRN-FR-002. Dos clientes pueden confirmar el mismo horario a la vez; la validación en la aplicación no alcanza (Vol. 05, figura 9.1).\nDecisión\nRestricción EXCLUDE sobre (recurso, rango horario) en PostgreSQL. El dominio también la verifica, para dar el mensaje de CA-01.2.\nConsecuencias\n+ La doble reserva es imposible, aunque haya varias instancias.\n- Ata la regla a PostgreSQL y a tener una sola base de turnos.\n- Si ADR-001 cambia, esta decisión tiene que revisarse.",
        },
        { type: "p", text: "Fijate que ADR-002 depende de ADR-001. Los registros hacen visibles esas dependencias, que de otro modo solo estarían en la cabeza de quien las tomó." },
        { type: "box", kind: "idea-clave", title: null, text: "Una decisión que no está escrita se vuelve a discutir cada vez que alguien nuevo llega al equipo." },
        { type: "box", kind: "practica", nivel: "APLICAR", title: "Tu primer ADR", text: "Escribí el ADR de una decisión del Vol. 06: usar claves de idempotencia en POST /turnos. Incluí contexto, decisión y al menos dos consecuencias, una positiva y una negativa." },
      ],
      fuentes: [
        "Nygard, M. — “Documenting Architecture Decisions”.",
        "Ford, N., Parsons, R. y Kua, P. (2017). Building Evolutionary Architectures. O'Reilly.",
      ],
    },
  ],
  cierre: {
    desafioIntegrador: {
      title: "Desafío integrador: Turnify para 200 lavaderos",
      body: [
        { type: "p", text: "Una empresa quiere ofrecer Turnify como servicio a lavaderos de todo el país. Cada lavadero tiene sus propios servicios, recursos y clientes." },
        { type: "p", text: "Partí de los atributos de calidad, no de las tecnologías: cada decisión tiene que poder justificarse con un escenario." },
        { type: "h3", text: "Preguntas de defensa" },
        { type: "p", text: "¿Qué atributo de calidad justifica cada decisión?" },
        { type: "p", text: "¿Qué compromiso aceptaste y qué perdiste a cambio?" },
        { type: "p", text: "¿Qué pasa con la regla de no superposición en tu nueva arquitectura?" },
        { type: "p", text: "¿Cómo impedís que un lavadero vea los datos de otro?" },
        { type: "p", text: "¿Qué decisión sería más costosa de revertir?" },
      ],
      entregables: [
        { text: "Qué decisiones de los ADR-001 y ADR-002 siguen valiendo y cuáles hay que revisar.", capRef: "01 y 12" },
        { text: "Los tres atributos de calidad más importantes ahora y un escenario para cada uno.", capRef: "02" },
        { text: "Los diagramas de contexto y de contenedores actualizados.", capRef: "03" },
        { text: "La elección de estilo, con su compromiso explícito.", capRef: "04" },
        { text: "Cómo se separan los datos de cada lavadero.", capRef: "07" },
        { text: "Qué comunicación pasa a ser asíncrona.", capRef: "08" },
        { text: "Un diagrama de despliegue y qué escala primero.", capRef: "09" },
        { text: "Los SLO del servicio.", capRef: "10" },
        { text: "Las amenazas nuevas que aparecen con muchos lavaderos.", capRef: "11" },
        { text: "Dos ADR nuevos.", capRef: "12" },
      ],
      autoevaluacion: {
        headers: ["Nivel", "Podés…", "Indicador"],
        rows: [
          ["Conocer", "explicar conceptos", "Explicás atributo de calidad, vista, estilo, acoplamiento, consistencia, SLO y ADR."],
          ["Aplicar", "construir", "Escribís escenarios de calidad, diagramas C4 y ADR para un caso real."],
          ["Analizar", "decidir y justificar", "Elegís entre alternativas explicitando compromisos, y reconocés cuándo hace falta un especialista."],
        ],
      },
    },
    cierreTronco: {
      title: "Cierre del tronco: el hilo de la doble reserva",
      body: [
        { type: "p", text: "Este es el último volumen de Fundamentos. Vale la pena mirar hacia atrás." },
        { type: "p", text: "Hay un problema que atravesó los siete volúmenes: que dos clientes reserven el mismo horario. Seguirlo muestra cómo cada disciplina aporta una pieza distinta a la misma solución." },
        {
          type: "table",
          headers: ["Vol.", "La pregunta", "La pieza que aportó"],
          rows: [
            ["01", "¿Cuál es el problema?", "“A veces se asignan dos vehículos al mismo horario”: un síntoma, no un requisito."],
            ["02", "¿Qué tiene que garantizarse?", "TRN-FR-002: no confirmar un turno si el recurso está ocupado."],
            ["03", "¿Cómo se ve en el comportamiento?", "El desvío 6b del CU-01 y el criterio CA-01.2."],
            ["04", "¿Dónde aparece en los modelos?", "La vuelta en el diagrama de actividad y el fragmento alt de la secuencia."],
            ["05", "¿Cómo se garantiza en los datos?", "La restricción de exclusión y el análisis de concurrencia."],
            ["06", "¿Qué pasa al cruzar la red?", "El 409 con Problem Details y la clave de idempotencia."],
            ["07", "¿Qué decisión la sostiene?", "ADR-001 y ADR-002: una base, una transacción, una restricción."],
          ],
        },
        { type: "box", kind: "idea-clave", title: null, text: "Ningún volumen resolvió el problema solo. El análisis lo encontró, los requisitos lo precisaron, los modelos lo hicieron visible, los datos lo garantizaron, la API lo comunicó y la arquitectura lo sostiene. Eso es pensar como analista de sistemas." },
        {
          type: "table",
          headers: ["Vol.", "Tronco de formación · Fundamentos"],
          rows: [
            ["01", "El sistema antes del código"],
            ["02", "Ingeniería de requisitos"],
            ["03", "Casos de uso, historias y criterios"],
            ["04", "Modelado con UML y BPMN"],
            ["05", "Datos y dominio"],
            ["06", "APIs e integración"],
            ["07", "Arquitectura  ← estás acá · tronco completo"],
          ],
        },
      ],
    },
    mapaDeSalida: {
      ideas: [
        { text: "Una decisión es arquitectónica si cambiarla después cuesta mucho.", capRef: "01" },
        { text: "Los atributos de calidad se vuelven medibles con escenarios.", capRef: "02" },
        { text: "Cada diagrama tiene un público y una pregunta; C4 ofrece niveles de zoom.", capRef: "03" },
        { text: "El estilo se elige por los atributos que el negocio necesita.", capRef: "04" },
        { text: "Las reglas de negocio no dependen de la base ni del framework.", capRef: "05" },
        { text: "Lo que cambia junto va junto.", capRef: "06" },
        { text: "Separar datos es fácil; separar sus garantías, no.", capRef: "07" },
        { text: "Síncrono cuando el negocio necesita la respuesta ahora; si no, avisar.", capRef: "08" },
        { text: "Una API sin estado es la condición para escalar horizontalmente.", capRef: "09" },
        { text: "Los SLO conectan la operación con los requisitos.", capRef: "10" },
        { text: "La seguridad de un sistema es la de su frontera más débil.", capRef: "11" },
        { text: "Una decisión que no está escrita se vuelve a discutir.", capRef: "12" },
      ],
      puente: null,
    },
    respuestasOrientativas: [
      {
        capId: "01",
        titulo: "¿Arquitectura o diseño?",
        nivel: "Conocer",
        respuesta: [
          "Usar PostgreSQL: arquitectura (la regla de no superposición depende de él).",
          "Nombrar el endpoint /turnos: diseño, aunque una vez publicado cuesta más (Vol. 06, cap. 12).",
          "Cancelar cambiando el estado: arquitectura; condiciona los datos, la auditoría y la API.",
          "React en el panel: diseño; el panel puede reescribirse sin tocar el resto.",
          "Claves de idempotencia: arquitectura; es parte del contrato y requiere una tabla y un flujo propios.",
        ],
      },
      {
        capId: "02",
        titulo: "Un escenario de disponibilidad",
        nivel: "Aplicar",
        respuesta: [
          "Fuente: El servicio de mensajería.",
          "Estímulo: Deja de responder.",
          "Entorno: Operación normal, durante una hora.",
          "Artefacto: El procesador de avisos.",
          "Respuesta: Las reservas siguen funcionando; los avisos quedan pendientes y se envían al volver el servicio.",
          "Medida: Cero reservas rechazadas por la falla; el 99 % de los avisos pendientes sale dentro de los 10 minutos posteriores a la recuperación.",
        ],
      },
      {
        capId: "03",
        titulo: "¿Qué diagrama para quién?",
        nivel: "Aplicar",
        respuesta: [
          "Al dueño, el de contexto (figura 3.1): muestra que el proveedor de pagos es una integración nueva. Al desarrollador nuevo, el de contenedores y el de módulos (figuras 3.2 y 6.1). A seguridad, el de contenedores y el de despliegue, marcando las fronteras de confianza (cap. 11).",
        ],
      },
      {
        capId: "04",
        titulo: "¿Cuándo separar?",
        nivel: "Analizar",
        respuesta: [
          "Notificaciones: ya se comunica por eventos, no participa en la regla de no superposición y su carga crece con la cantidad de lavaderos. La señal sería que su carga o sus fallas empiecen a afectar a las reservas, o que un equipo distinto necesite desplegarlo por separado.",
        ],
      },
      {
        capId: "05",
        titulo: "Un adaptador nuevo",
        nivel: "Aplicar",
        respuesta: [
          "Se agrega un adaptador de entrada (el bot de WhatsApp) que llama al mismo caso de uso ReservarTurno. El núcleo, los puertos y los adaptadores de salida quedan igual. Es exactamente para lo que sirve la separación.",
        ],
      },
      {
        capId: "06",
        titulo: "Un módulo nuevo",
        nivel: "Analizar",
        respuesta: [
          "Conviene un módulo Pagos: cambia por razones distintas (el proveedor, la normativa) que Reservas. Pagos dependería de Clientes; Reservas dependería de Pagos solo si la seña es condición para confirmar, y en ese caso conviene que se comuniquen por eventos o con un estado “pendiente de pago”.",
        ],
      },
      {
        capId: "07",
        titulo: "Una lectura desactualizada",
        nivel: "Analizar",
        respuesta: [
          "El encargado podría ver libre un horario que ya se reservó. Para reportes y la agenda general es aceptable; para decidir si reasigna o aprueba un turno, no: esas pantallas tienen que leer la base principal, y de todos modos la restricción de exclusión impediría el error.",
        ],
      },
      {
        capId: "08",
        titulo: "¿Síncrono o asíncrono?",
        nivel: "Aplicar",
        respuesta: [
          "Verificar disponibilidad: síncrono (es la respuesta que el cliente espera). Avisar al encargado: asíncrono. Cobrar la seña: síncrono si el negocio exige el pago para confirmar, o asíncrono con un estado “pendiente de pago”. Actualizar el calendario: asíncrono.",
        ],
      },
      {
        capId: "09",
        titulo: "El sábado a la mañana",
        nivel: "Analizar",
        respuesta: [
          "Las instancias de la API escalan primero, porque no tienen estado. El cuello de botella probable es la base: todas las instancias escriben en ella, y las reservas del mismo recurso compiten por la misma restricción. Antes de escalarla, conviene medir (cap. 10).",
        ],
      },
      {
        capId: "10",
        titulo: "Una traza",
        nivel: "Aplicar",
        respuesta: [
          "Balanceador → instancia de la API → autenticación → caso de uso ReservarTurno → consulta de la clave de idempotencia → inserción del turno y del evento (una transacción) → respuesta. Más tarde, en otra traza enlazada: procesador de avisos → lectura del evento → llamada a la mensajería.",
        ],
      },
      {
        capId: "11",
        titulo: "Una amenaza más",
        nivel: "Analizar",
        respuesta: [
          "La frontera más expuesta es la consulta pública de disponibilidad (Vol. 06): no requiere autenticación y cada consulta calcula horarios. Controles: límite de solicitudes por origen (429), caché de corta duración para la disponibilidad y un SLO que avise si la latencia sube.",
        ],
      },
      {
        capId: "12",
        titulo: "Tu primer ADR",
        nivel: "Aplicar",
        respuesta: [
          "ADR-003 · Claves de idempotencia en POST /turnos — Estado: aceptada",
          "Contexto: Si la respuesta de una reserva se pierde, el reintento recibe 409 \"horario ocupado\" por su propio turno (Vol. 06, cap. 10).",
          "Decisión: POST /turnos exige el encabezado Idempotency-Key. El servidor guarda la clave junto con el turno, en la misma transacción, durante 24 horas.",
          "Consecuencias: + Los reintentos son seguros y el cliente recibe su turno. - Los consumidores tienen que generar y conservar las claves. - Hay una tabla más que limpiar periódicamente.",
        ],
      },
    ],
    bibliografia: [
      "Este volumen se escribió de cero para la colección. Todas las referencias están marcadas para verificar ediciones, capítulos y enlaces antes de cerrar la versión.",
      "Bass, L., Clements, P. y Kazman, R. (2021). Software Architecture in Practice, 4.ª ed. Addison-Wesley.",
      "Beyer, B., Jones, C., Petoff, J. y Murphy, N. R. (eds.) (2016). Site Reliability Engineering. O'Reilly.",
      "Evans, E. (2003). Domain-Driven Design. Addison-Wesley.",
      "Ford, N., Parsons, R. y Kua, P. (2017). Building Evolutionary Architectures. O'Reilly.",
      "Hohpe, G. y Woolf, B. (2003). Enterprise Integration Patterns. Addison-Wesley.",
      "Kleppmann, M. (2017). Designing Data-Intensive Applications. O'Reilly.",
      "Martin, R. C. (2017). Clean Architecture. Prentice Hall.",
      "Richards, M. y Ford, N. (2020). Fundamentals of Software Architecture. O'Reilly.",
      "Shostack, A. (2014). Threat Modeling: Designing for Security. Wiley.",
      "ISO/IEC/IEEE 42010:2022 — Software, systems and enterprise — Architecture description.",
      "ISO/IEC 25010:2023 — Product quality model.",
      "Conway, M. E. (1968). “How Do Committees Invent?”. Datamation.",
      "Parnas, D. L. (1972). “On the Criteria To Be Used in Decomposing Systems into Modules”. Communications of the ACM.",
      "Brown, S. — The C4 model for visualising software architecture (c4model.com).",
      "Cockburn, A. (2005). “Hexagonal Architecture”.",
      "Fowler, M. (2015). “MonolithFirst”; Lewis, J. y Fowler, M. (2014). “Microservices” (martinfowler.com).",
      "Nygard, M. (2011). “Documenting Architecture Decisions”.",
      "Richardson, C. — “Saga” y “Transactional Outbox” (microservices.io).",
      "Wiggins, A. — The Twelve-Factor App (12factor.net).",
      "OWASP — Threat Modeling Cheat Sheet.  ·  OpenTelemetry — documentación.",
      "Los ejemplos, diagramas, decisiones y ejercicios son elaboración didáctica propia. Las decisiones de Turnify no deben leerse como recomendaciones para un sistema real sin analizar su contexto.",
    ],
  },
}
