export default {
  id: '01',
  title: 'El sistema antes del código',
  subtitle: 'Pensamiento sistémico y análisis de sistemas para futuros profesionales IT',
  ficha: {
    proposito: 'Construir el mapa mental inicial que permita comprender un sistema antes de pensar en su implementación.',
    publico: 'Personas que quieren aprender, reconstruir fundamentos y conectar conocimientos sobre sistemas y software.',
    competencias: 'Conocer, aplicar y analizar: sistema y contexto, problema/necesidad/solución, stakeholders, procesos, reglas, alcance y perspectivas.',
    casoTransversal: 'Un lavadero de autos ficticio y Turnify, el sistema de turnos que iremos definiendo.',
    metodo: 'Cada capítulo avanza de conocer a aplicar y analizar. El desafío integrador es el lugar para demostrar todo junto.',
    lugarEnElTronco: '01 · Fundamentos. Sin dependencias previas.',
    nivel: null,
    requiere: null,
    preparaPara: 'requisitos · casos de uso · procesos · datos · arquitectura',
  },
  recorrido: [
    { chapterId: '01', title: 'Antes del software, existe un problema', pregunta: '¿Qué nos están pidiendo en realidad?' },
    { chapterId: '02', title: '¿Qué es realmente un sistema?', pregunta: '¿Dónde ocurre el problema?' },
    { chapterId: '03', title: 'Sistemas de información', pregunta: '¿Qué lo compone cuando gira alrededor de la información?' },
    { chapterId: '04', title: 'El contexto importa', pregunta: '¿Por qué la misma solución no sirve en todos lados?' },
    { chapterId: '05', title: '¿Quiénes participan?', pregunta: '¿A quiénes afecta y quiénes saben?' },
    { chapterId: '06', title: 'Los procesos que hacen funcionar al negocio', pregunta: '¿Cómo se hace el trabajo hoy?' },
    { chapterId: '07', title: 'Las reglas que nadie escribió', pregunta: '¿Qué condiciones gobiernan ese trabajo?' },
    { chapterId: '08', title: 'El límite del sistema', pregunta: '¿Qué queda adentro y qué afuera?' },
    { chapterId: '09', title: 'El mismo sistema, diferentes perspectivas', pregunta: '¿Cómo conviven miradas distintas?' },
    { chapterId: '10', title: 'Del problema a una primera visión de solución', pregunta: '¿Cuándo y cómo empezamos a proponer?' },
  ],
  intro: {
    title: 'Antes de empezar',
    body: [
      { type: 'p', text: 'Si estás estudiando Análisis de Sistemas, probablemente te haya pasado algo parecido a esto: sabés qué es una base de datos, qué es una API, qué es un requisito y reconocés un diagrama UML. Quizás incluso podés explicar qué es una arquitectura en capas.' },
      { type: 'p', text: 'Pero alguien te entrega un sistema que nunca viste y te dice: “Necesitamos mejorar esto. ¿Por dónde empezarías?”' },
      { type: 'p', text: 'De repente, todos esos conocimientos que parecían bastante claros por separado dejan de formar una imagen completa. Este cuadernillo intenta darte justamente eso: una forma de mirar que conecte las piezas antes de empezar a construir.' },
      { type: 'box', kind: 'idea-clave', title: null, text: 'Antes de diseñar una solución, necesitamos comprender el sistema y el problema que estamos tratando de resolver.' },
      { type: 'h3', text: '¿Qué significa pensar como analista?' },
      { type: 'p', text: 'Pensar como analista no significa saber responder rápidamente qué tecnología utilizar. Tampoco significa producir muchos diagramas. Significa observar un problema desde diferentes perspectivas y construir progresivamente una comprensión compartida de la situación. Para eso, un analista mira:\nel contexto\nlas personas involucradas\nlos objetivos\nlos procesos\nla información\nlas reglas\nlas restricciones\nlas relaciones entre estos elementos\nlas necesidades que una solución debería satisfacer' },
      { type: 'p', text: 'Cada uno de estos elementos tiene su capítulo en este volumen. El análisis de sistemas comienza mucho antes de que exista una línea de código.' },
      { type: 'h3', text: 'El caso que nos acompaña' },
      { type: 'box', kind: 'el-caso', title: 'Un lavadero que organiza sus turnos por WhatsApp', text: 'Un lavadero de autos administra sus turnos mediante mensajes de WhatsApp y una planilla. Los clientes consultan disponibilidad y el encargado responde a mano. A veces se asignan dos vehículos al mismo horario. Los empleados necesitan saber qué trabajos tienen programados. El dueño quiere reducir esos conflictos. Cada capítulo mira este lavadero desde un ángulo nuevo, hasta que en el capítulo 10 podamos proponer una primera visión de solución. A esa futura solución la vamos a llamar Turnify.' },
    ],
  },
  chapters: [
    {
      id: '01',
      title: 'Antes del software, existe un problema',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Todo empieza con un pedido. La primera tarea del analista es no confundirlo con el problema.' },
        { type: 'box', kind: 'el-caso', title: 'El pedido', text: 'El dueño del lavadero dice: “Necesito una aplicación para gestionar los turnos.”' },
        { type: 'p', text: '¿Parece un requisito? Antes de responder, pensemos. Sabemos que alguien quiere una aplicación. Pero todavía no sabemos:\nqué problema tiene actualmente\nquiénes utilizan el proceso\ncómo se gestionan los turnos hoy\nqué información necesitan\nqué reglas existen\nqué errores ocurren\nqué objetivos persigue la organización\nqué restricciones existen\nqué significa exactamente “gestionar”\nni siquiera si una aplicación es la solución adecuada' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una de las primeras habilidades de un analista consiste en no confundir la solución propuesta con la necesidad que la originó.' },
        { type: 'h3', text: 'Problema, necesidad y solución' },
        { type: 'p', text: 'Podemos pensar inicialmente en tres niveles, que van de lo que ocurre a lo que proponemos hacer: problema u oportunidad → necesidad → solución. Aplicados al lavadero:' },
        { type: 'table', headers: ['Nivel', 'En el lavadero'], rows: [
          ['Problema', 'El proceso actual dificulta conocer y controlar la disponibilidad real, y puede producir conflictos de asignación.'],
          ['Necesidad', 'Contar con un proceso confiable para gestionar la disponibilidad y la asignación de turnos.'],
          ['Solución propuesta', '“Hagamos una aplicación.”'],
        ] },
        { type: 'p', text: 'Fijate que el cliente llegó con la última fila. Nuestro trabajo es recorrer la tabla hacia arriba.' },
        { type: 'h3', text: 'Seis conceptos que se analizan juntos' },
        { type: 'p', text: 'El IIBA propone el Business Analysis Core Concept Model (BACCM), que relaciona seis conceptos: cambio, necesidad, solución, valor, stakeholders y contexto. La idea es que no se analicen de manera aislada, sino como partes de una misma situación. Cada concepto se traduce en una pregunta de analista:' },
        { type: 'table', headers: ['Concepto', 'Pregunta del analista'], rows: [
          ['Cambio', '¿Qué está cambiando?'],
          ['Necesidad', '¿Por qué hace falta cambiarlo?'],
          ['Stakeholders', '¿Quién está involucrado?'],
          ['Contexto', '¿En qué contexto ocurre?'],
          ['Valor', '¿Qué valor esperamos obtener?'],
          ['Solución', '¿Qué solución podría responder a esa necesidad?'],
        ] },
        { type: 'h3', text: 'Una primera regla profesional' },
        { type: 'box', kind: 'atencion', title: null, text: 'No diseñes la solución antes de entender el problema. Esto no significa que nunca podamos hablar de tecnología durante el análisis. Significa que debemos poder distinguir entre “esto es lo que necesitamos resolver” y “esta es una manera posible de resolverlo”.' },
        { type: 'box', kind: 'practica', nivel: 'CONOCER', title: 'Antes de aceptar la propuesta', text: 'Un cliente dice: “Quiero una aplicación móvil para que los empleados puedan cargar las horas trabajadas.” Escribí cinco preguntas que harías antes de aceptar la propuesta. No preguntes todavía “¿React Native o Flutter?”: buscamos preguntas sobre el problema.' },
        { type: 'h3', text: 'Un pedido más difícil' },
        { type: 'box', kind: 'el-caso', title: null, text: 'El dueño vuelve con otro pedido: “Necesito que la aplicación cancele automáticamente los turnos cuando un empleado está ausente.”' },
        { type: 'p', text: 'Antes de diseñar nada, habría que descubrir:\n¿Cómo se informa una ausencia?\n¿Quién decide qué turnos se cancelan?\n¿Todos los servicios requieren a ese empleado?\n¿Hay otros empleados disponibles?\n¿Qué ocurre con los clientes afectados? ¿Se puede reprogramar?\n¿Hay servicios que no puedan reasignarse?\n¿Qué reglas determinan la disponibilidad?\n¿Qué información necesita el sistema para tomar esa decisión?' },
        { type: 'p', text: 'El problema ya no parece “hacer una pantalla de cancelación”. Aparecen personas, procesos, reglas, información, decisiones y restricciones. Para ordenarlos, primero necesitamos entender el sistema en el que todo eso ocurre.' },
      ],
      fuentes: ['IIBA — Business Analysis Core Concept Model (BACCM).'],
    },
    {
      id: '02',
      title: '¿Qué es realmente un sistema?',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Si el pedido no es el problema, necesitamos entender dónde ocurre el problema. Eso nos lleva a la pregunta más básica del volumen.' },
        { type: 'p', text: 'En análisis de sistemas, “sistema” no debería significar automáticamente “software”. Un sistema puede comprender personas, procesos, información, tecnología, reglas, recursos y relaciones. Qué elementos consideramos parte del sistema depende del propósito del análisis y de la frontera que tracemos.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un sistema no se entiende mirando solamente sus componentes. También hay que observar las relaciones entre ellos, el propósito que persiguen y el entorno en el que operan.' },
        { type: 'h3', text: '2.1 Sistema, elementos y relaciones' },
        { type: 'p', text: 'En ingeniería de sistemas, ISO/IEC/IEEE 15288:2023 entiende un sistema, en esencia, como una combinación de elementos que interactúan, organizados para lograr uno o más propósitos declarados. La norma lo trata desde una perspectiva de ciclo de vida y contempla los elementos necesarios para operarlo y sostenerlo en su entorno previsto. Por eso, qué constituye “el sistema” depende del contexto y del propósito.' },
        { type: 'p', text: 'Esto explica por qué dos profesionales pueden dibujar fronteras diferentes sobre una misma organización y ambos estar haciendo un análisis válido: quizás están respondiendo preguntas distintas.' },
        { type: 'h3', text: '2.2 Subsistema y composición' },
        { type: 'p', text: 'Un sistema puede contener otros sistemas o subsistemas. El lavadero puede estudiarse como una organización completa; pero para analizar la asignación de turnos podemos considerar un subsistema de gestión de agenda, mientras que para otro análisis podríamos incluir facturación, inventario y atención al cliente.' },
        { type: 'box', kind: 'atencion', title: null, text: '“Subsistema” no significa necesariamente “microservicio”. Es una relación conceptual de composición. Un subsistema puede ser humano, organizacional, físico, lógico o tecnológico.' },
        { type: 'h3', text: '2.3 El entorno' },
        { type: 'p', text: 'El sistema no existe en el vacío. El entorno incluye factores externos que influyen en su funcionamiento: personas, organizaciones, normas, infraestructura, otros sistemas, condiciones físicas y restricciones del contexto. OpenStax, por ejemplo, incluye el entorno como uno de los elementos de un sistema de información y señala que factores como la ubicación, la red y el contexto de uso pueden afectar cómo opera.' },
        { type: 'h3', text: '2.4 La frontera del sistema' },
        { type: 'p', text: 'La frontera es una decisión analítica: marca qué vamos a tratar como parte del sistema y qué vamos a considerar externo. SEBoK, citando a Peter Checkland, la define como una distinción que hace un observador para separar lo que toma como sistema de su entorno.' },
        { type: 'p', text: '¿Qué estamos incluyendo dentro de nuestro análisis y qué estamos dejando afuera?' },
        { type: 'p', text: 'Por ahora alcanza con el concepto. En el capítulo 08, cuando ya conozcamos a las personas, los procesos y las reglas del lavadero, vamos a trazar esa frontera.' },
        { type: 'h3', text: '2.5 Entradas, transformación y salidas' },
        { type: 'p', text: 'Una primera representación útil consiste en observar qué entra, qué transformación ocurre y qué sale. En el lavadero:' },
        { type: 'table', headers: ['Entrada', 'Transformación', 'Salida'], rows: [
          ['Solicitud de turno Datos del cliente Servicio elegido', 'Validar disponibilidad Aplicar reglas Registrar asignación', 'Turno confirmado Agenda actualizada Notificación'],
        ] },
        { type: 'p', text: 'Esta representación todavía no explica todo el sistema, pero ayuda a formular preguntas y a detectar información faltante.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Qué entra, qué pasa, qué sale', text: 'Para el lavadero, identificá cinco entradas, tres transformaciones y cuatro salidas. Después preguntate: ¿qué elemento del entorno puede modificar el resultado sin pertenecer al sistema de gestión de turnos?' },
      ],
      fuentes: [
        'ISO/IEC/IEEE 15288:2023 — Systems and software engineering — System life cycle processes.',
        'SEBoK — System Boundary, basado en Checkland, Systems Thinking, Systems Practice.',
        'OpenStax — Foundations of Information Systems, capítulo 1.',
      ],
    },
    {
      id: '03',
      title: 'Sistemas de información: cuando información y organización se encuentran',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ya sabemos qué es un sistema en general. Ahora acotamos: cuando el sistema gira alrededor de la información, ¿qué lo compone?' },
        { type: 'p', text: 'Un sistema de información no es simplemente una aplicación. OpenStax lo presenta como un conjunto de componentes interconectados que permite recopilar, procesar, almacenar y distribuir datos e información para apoyar decisiones, coordinación, control, análisis y visualización dentro de una organización.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'El software puede formar parte de un sistema de información sin ser el sistema de información completo.' },
        { type: 'h3', text: '3.1 Cinco componentes que conviene mirar' },
        { type: 'p', text: 'Personas: quienes usan, administran, mantienen o toman decisiones.\nDatos: hechos y registros que el sistema necesita procesar y conservar.\nProcedimientos: reglas y formas de realizar actividades.\nHardware: dispositivos e infraestructura física.\nSoftware: aplicaciones y programas que procesan o gestionan información.' },
        { type: 'p', text: 'La utilidad de esta mirada es práctica: cuando alguien pide “un sistema”, podemos preguntar qué personas participan, qué datos existen, qué procedimientos se quieren cambiar y qué tecnología ya forma parte del contexto. En el lavadero, por ejemplo, la planilla y el WhatsApp ya son parte del sistema de información actual, aunque nadie los llame así.' },
        { type: 'h3', text: '3.2 Control y retroalimentación' },
        { type: 'p', text: 'En el 2.5 vimos entrada, transformación y salida. OpenStax suma dos elementos más: el control, que verifica que el sistema funcione como se espera, y la retroalimentación (feedback), que permite que la experiencia y los problemas detectados alimenten cambios posteriores.' },
        { type: 'box', kind: 'el-caso', title: null, text: 'Un empleado detecta que una reserva fue asignada incorrectamente. Ese hecho no es solamente “un error de usuario”: puede ser feedback sobre una regla, una interfaz, un proceso o un dato que el sistema necesita revisar.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Mirar sin abrir el código', text: 'Tomá una aplicación que uses habitualmente. Sin mirar su código, identificá: personas, datos, procedimientos, software, hardware, entradas, procesos, salidas, controles y feedback.' },
      ],
      fuentes: ['OpenStax — Foundations of Information Systems, 1.1 Introduction to Information Systems.'],
    },
    {
      id: '04',
      title: 'El contexto importa',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Los componentes de un sistema de información se parecen mucho de una organización a otra. Lo que cambia —y lo cambia todo— es el contexto.' },
        { type: 'p', text: 'Dos sistemas con funcionalidades parecidas pueden necesitar soluciones muy diferentes porque operan en contextos distintos. El contexto condiciona objetivos, reglas, recursos, riesgos, restricciones y expectativas.' },
        { type: 'h3', text: '4.1 El mismo software no significa el mismo sistema' },
        { type: 'p', text: 'Una agenda para un lavadero, una clínica y un salón de belleza puede compartir conceptos como clientes, turnos y disponibilidad. Pero las consecuencias de una cancelación, la información requerida, los roles, las regulaciones y las reglas de negocio pueden ser radicalmente diferentes.' },
        { type: 'p', text: '¿Qué cosas del contexto podrían hacer que una solución que funciona en un lugar sea inadecuada en otro?' },
        { type: 'p', text: 'Algunos factores que conviene relevar:\nnormativa\ntamaño de la organización y cantidad de usuarios\ninfraestructura disponible\nnivel de alfabetización digital\ndependencias con otros sistemas\nriesgos y costos\nprocesos existentes\nobjetivos del negocio' },
        { type: 'h3', text: '4.2 El contexto no es decoración' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'El contexto se convierte en restricciones, reglas y requisitos.' },
        { type: 'p', text: 'Si una aplicación se utilizará en un entorno con mala conectividad, eso puede convertirse en una restricción. Si el proceso depende de una normativa, esa normativa puede generar reglas. Si una decisión debe quedar auditada, la trazabilidad pasa a ser relevante.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Tablets sin buena señal', text: 'El lavadero quiere usar tablets en el área de trabajo, pero allí la señal Wi-Fi es inestable. ¿Qué preguntas harías antes de decidir cómo funcionará la agenda?' },
      ],
      fuentes: [
        'OpenStax — Foundations of Information Systems, 1.1.',
        'ISO/IEC/IEEE 15288:2023 — perspectiva de sistema en su entorno previsto.',
      ],
    },
    {
      id: '05',
      title: '¿Quiénes participan?',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'El contexto está hecho, en buena parte, de personas. Antes de hablar de procesos, necesitamos saber quiénes están involucrados y qué les importa.' },
        { type: 'p', text: 'Un sistema puede afectar a muchas personas aunque no todas utilicen directamente el software. Para analizarlo necesitamos identificar a quienes tienen interés, responsabilidad, influencia, conocimiento o impacto relacionado con el problema. OpenStax define stakeholder como una persona o grupo con interés o preocupación respecto de una decisión de negocio, y señala que puede ser interno o externo a la organización.' },
        { type: 'box', kind: 'atencion', title: null, text: 'No preguntes solo “¿quién usa el sistema?” También preguntá quién decide, quién paga, quién recibe resultados, quién mantiene el proceso, quién puede verse afectado y quién conoce reglas que quizás todavía no están documentadas.' },
        { type: 'h3', text: '5.1 El mapa inicial del lavadero' },
        { type: 'table', headers: ['Stakeholder', 'Relación', 'Qué necesitamos saber'], rows: [
          ['Cliente', 'Solicita turno', 'Necesidades, datos, expectativas'],
          ['Encargado', 'Administra la agenda', 'Reglas, excepciones, decisiones'],
          ['Empleado', 'Ejecuta el servicio', 'Disponibilidad, estados, restricciones'],
          ['Dueño', 'Define objetivos', 'Indicadores, costos, prioridades'],
          ['Proveedor de pagos o mensajería', 'Presta un servicio externo del que el proceso podría depender', 'Datos que intercambia, contratos, límites'],
        ] },
        { type: 'h3', text: '5.2 Stakeholder no es lo mismo que usuario' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una persona puede ser clave para el sistema sin tocarlo nunca.' },
        { type: 'p', text: 'El dueño puede no usar nunca el sistema y, aun así, ser un stakeholder clave. Un cliente puede usarlo una vez al mes y tener requisitos importantes. El encargado puede utilizarlo todo el día y tener necesidades completamente diferentes.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Ampliar el mapa', text: 'Para el lavadero, listá al menos seis stakeholders. Para cada uno, anotá qué necesita, qué puede decidir, qué información posee y qué riesgo aparece si no lo escuchamos.' },
      ],
      fuentes: [
        'OpenStax — Foundations of Information Systems, 4.1 Systems Analysis and Design for Application Development.',
        'IIBA — BACCM (concepto de stakeholder).',
      ],
    },
    {
      id: '06',
      title: 'Los procesos que hacen funcionar al negocio',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ya sabemos quiénes participan. Ahora necesitamos saber qué hacen: cómo se encadena el trabajo que produce resultados.' },
        { type: 'p', text: 'Una organización no funciona porque tenga pantallas: funciona porque realiza actividades que producen resultados. El software puede soportar, automatizar o transformar esas actividades.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Si entendés solamente las pantallas, todavía no entendés el proceso.' },
        { type: 'h3', text: '6.1 Del botón al proceso' },
        { type: 'p', text: 'En vez de preguntar solamente “¿qué botón necesita el usuario?”, preguntá:\n¿Qué evento inicia la actividad?\n¿Qué pasos ocurren y quién participa en cada uno?\n¿Qué información se utiliza?\n¿Qué decisión se toma?\n¿Qué resultado se produce?\n¿Qué excepciones aparecen?' },
        { type: 'box', kind: 'el-caso', title: 'Reservar un turno, paso a paso', text: 'Evento: el cliente solicita un turno → verificar disponibilidad → seleccionar servicio → asignar horario → registrar turno → confirmar al cliente.' },
        { type: 'h3', text: '6.2 Procesos y reglas no son lo mismo' },
        { type: 'p', text: 'El proceso describe cómo se desarrolla una actividad. Una regla establece una condición, política o restricción que debe respetarse durante esa actividad. Ambos conceptos se relacionan, pero no son intercambiables: en el paso “asignar horario”, asignar es parte del proceso; no superponer dos vehículos es una regla.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'El proceso actual en siete pasos', text: 'Escribí el proceso actual de reserva de turnos del lavadero en 7 pasos. Después marcá con dos colores cuáles son actividades y cuáles dependen de una regla.' },
      ],
      fuentes: [
        'OMG — Business Process Model and Notation (BPMN), especificación oficial (profundización).',
        'OpenStax — Foundations of Information Systems.',
      ],
    },
    {
      id: '07',
      title: 'Las reglas que nadie escribió',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Detrás de cada proceso hay condiciones que lo gobiernan. Muchas de ellas nunca se escribieron.' },
        { type: 'p', text: 'Muchas organizaciones funcionan gracias a reglas que viven en la experiencia de las personas: “ese servicio necesita dos empleados”, “si llueve, no hacemos lavado exterior”. Son reglas de negocio aunque nadie las haya documentado.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una regla de negocio puede existir aunque no esté escrita. El trabajo del analista incluye hacerla visible, validarla y determinar cómo debe representarse. Las reglas que descubras acá serán la base de requisitos, validaciones y modelos de datos.' },
        { type: 'h3', text: '7.1 Regla, decisión y procedimiento' },
        { type: 'p', text: 'No todo conocimiento operativo es una regla: puede ser una decisión humana, un procedimiento o una costumbre. Y una aclaración de vocabulario: en la literatura de reglas de negocio, una restricción no es algo distinto de una regla, sino un tipo de regla. El Business Rules Manifesto y la especificación SBVR de la OMG distinguen, entre otras, las reglas que definen conceptos (reglas de definición) de las que gobiernan conductas mediante obligaciones o prohibiciones (reglas de comportamiento).' },
        { type: 'h3', text: '7.2 Ejemplos del lavadero' },
        { type: 'table', headers: ['Enunciado', 'Qué es', 'Por qué'], rows: [
          ['“No se puede reservar un horario ya ocupado.”', 'Regla de comportamiento (prohibición)', 'Impide un estado: dos turnos en el mismo horario y recurso.'],
          ['“Los turnos de más de 90 minutos requieren confirmación.”', 'Regla de comportamiento (obligación)', 'Exige una acción cuando se cumple una condición.'],
          ['“Un turno corresponde a un único vehículo.”', 'Regla de definición', 'Define qué es un turno; forma parte del concepto.'],
          ['“El encargado decide si acepta una excepción.”', 'Decisión humana', 'No se automatiza; puede estar acotada por una política.'],
          ['“Siempre llamamos al cliente cuando falta un empleado.”', 'Procedimiento', 'Describe cómo se actúa; puede estar respaldado por una política.'],
        ] },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: '¿Regla o costumbre?', text: 'El encargado dice: “Si un cliente llega más de 15 minutos tarde, perdemos el turno.” ¿Es una regla? ¿Qué preguntas necesitás hacer para no convertir una costumbre en una regla automática?' },
      ],
      fuentes: [
        'Business Rules Group — Business Rules Manifesto.',
        'OMG — Semantics of Business Vocabulary and Business Rules (SBVR).',
      ],
    },
    {
      id: '08',
      title: 'El límite del sistema',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'En el capítulo 02 presentamos la frontera como concepto. Ahora que conocemos el contexto, las personas, los procesos y las reglas del lavadero, podemos trazarla.' },
        { type: 'p', text: 'Una de las decisiones más importantes del análisis es determinar qué pertenece al sistema que estamos estudiando y qué queda en el entorno. La frontera no es necesariamente una pared física: es una decisión de modelado.' },
        { type: 'h3', text: '8.1 Fronteras diferentes para preguntas diferentes' },
        { type: 'p', text: 'Podemos estudiar “el sistema de turnos” incluyendo solamente la gestión de reservas. Pero si queremos analizar pagos, quizás necesitemos incluir el proceso de cobro y su integración con un proveedor externo. Si estudiamos la organización completa, la frontera vuelve a cambiar.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'No hay una única vista correcta: la frontera adecuada depende de la pregunta que queremos responder.' },
        { type: 'h3', text: '8.2 ¿Qué queda afuera?' },
        { type: 'p', text: 'Definir el afuera es tan importante como definir el adentro. Un sistema externo puede ser crítico aunque no forme parte de nuestra solución: una pasarela de pago, un servicio de mensajería, un proveedor de mapas o una API de terceros.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Trazar el límite', text: 'Dibujá un rectángulo con el título “Gestión de turnos del lavadero”. Colocá adentro: clientes, agenda, reglas, empleados y base de datos. Después revisá cada elemento: ¿pertenece realmente al sistema que estás definiendo o es parte del contexto que el sistema debe considerar? Justificá cada decisión.' },
      ],
      fuentes: [
        'SEBoK — System Boundary; definición basada en Checkland.',
        'ISO/IEC/IEEE 15288:2023.',
      ],
    },
    {
      id: '09',
      title: 'El mismo sistema, diferentes perspectivas',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Trazar un límite ya implica elegir un punto de vista. Este capítulo hace explícito algo que venía apareciendo: cada persona mira el sistema desde un lugar distinto.' },
        { type: 'p', text: 'Un analista rara vez puede comprender un sistema desde una sola mirada. El cliente piensa en objetivos. El empleado, en tareas. El desarrollador, en comportamiento. El responsable de seguridad, en riesgos. El dueño, en costos.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una diferencia de perspectiva no implica que alguien esté equivocado. Puede significar que están observando partes distintas del mismo sistema.' },
        { type: 'h3', text: '9.1 Perspectivas del lavadero' },
        { type: 'table', headers: ['Perspectiva', 'Pregunta dominante'], rows: [
          ['Cliente', '¿Puedo conseguir el horario que necesito?'],
          ['Empleado', '¿Qué trabajos tengo asignados y cuándo?'],
          ['Encargado', '¿Cómo evito conflictos y administro excepciones?'],
          ['Dueño', '¿La operación funciona mejor y con menos pérdidas?'],
          ['Desarrollador', '¿Qué comportamiento debe implementar el sistema?'],
          ['Analista', '¿Cómo conecto necesidades, procesos, reglas, información y solución?'],
        ] },
        { type: 'p', text: 'La idea de que cada stakeholder tiene intereses propios (concerns) que requieren vistas distintas del mismo sistema está formalizada en ISO/IEC/IEEE 42010, el estándar de descripción de arquitecturas. La vas a reencontrar en el volumen de arquitectura.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Dos clics o revisión manual', text: 'El cliente quiere “reservar en dos clics”, pero el encargado necesita revisar manualmente algunos turnos. ¿Cómo investigarías el conflicto sin decidir de antemano quién tiene razón?' },
        { type: 'p', text: 'Esta capacidad prepara el terreno para requisitos: distintas perspectivas producen necesidades, restricciones y criterios diferentes que deben hacerse explícitos.' },
      ],
      fuentes: [
        'ISO/IEC/IEEE 42010:2022 — Software, systems and enterprise — Architecture description.',
        'IIBA — BACCM (stakeholders y valor).',
      ],
    },
    {
      id: '10',
      title: 'Del problema a una primera visión de solución',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Tenemos todas las piezas. Ahora sí podemos empezar a hablar de solución, con cuidado.' },
        { type: 'p', text: 'Después de comprender contexto, actores, procesos, reglas y fronteras, podemos formular una visión inicial de solución. La palabra clave es inicial: todavía no estamos diseñando la arquitectura ni el modelo de datos definitivo.' },
        { type: 'p', text: 'La secuencia de trabajo es, además, el recorrido que hicimos en este volumen:' },
        { type: 'p', text: 'Problema → contexto → stakeholders → procesos → reglas → información → alcance → necesidades → alternativas de solución' },
        { type: 'h3', text: '10.1 ¿Cuándo podemos empezar a hablar de solución?' },
        { type: 'p', text: 'Cuando tenemos suficiente comprensión para explicar qué problema queremos resolver, para quién, en qué contexto, con qué restricciones y qué resultado esperamos. Eso no significa que toda incertidumbre haya desaparecido.' },
        { type: 'h3', text: '10.2 La solución como hipótesis' },
        { type: 'p', text: 'Una solución inicial puede tratarse como una hipótesis: una propuesta que debe contrastarse con las necesidades y restricciones descubiertas. Esto evita que una tecnología elegida demasiado pronto se convierta en una camisa de fuerza para el análisis. En términos del BACCM, una solución vale en la medida en que satisface una necesidad y aporta valor en un contexto.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Una buena solución no es la que tiene más tecnología. Es la que responde al problema y al contexto con decisiones que podemos explicar.' },
        { type: 'h3', text: '10.3 Primera visión de Turnify' },
        { type: 'box', kind: 'el-caso', title: 'Turnify, versión inicial', text: '“Un sistema que permita gestionar la disponibilidad y asignación de turnos del lavadero, reduciendo conflictos de agenda y proporcionando a clientes, empleados y encargados la información necesaria para operar el proceso.”' },
        { type: 'p', text: 'Todavía faltan preguntas. ¿Qué servicios existen? ¿Cómo se calculan las duraciones? ¿Qué recursos limitan la capacidad? ¿Qué pasa con las cancelaciones? ¿Qué notificaciones se necesitan? ¿Quién puede modificar un turno? Esas preguntas nos llevan al próximo volumen: requisitos.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Tu propia visión', text: 'Redactá una visión inicial de solución para Turnify en no más de tres líneas. Después escribí diez preguntas abiertas que todavía impedirían comenzar una implementación seria.' },
      ],
      fuentes: ['IIBA — BACCM (necesidad, solución y valor).'],
    },
  ],
  cierre: {
    desafioIntegrador: {
      title: 'mirar antes de construir',
      body: [
        { type: 'p', text: 'Es momento de demostrar todo junto, con un caso nuevo y sin red.' },
        { type: 'box', kind: 'el-caso', title: 'Una empresa que quiere “una app moderna con IA”', text: 'Una empresa administra turnos mediante WhatsApp, una planilla y llamadas telefónicas. Quiere “una app moderna con IA”. El dueño afirma que el principal problema es que los empleados se olvidan de cargar los turnos. Los empleados dicen que el problema es que los clientes cambian horarios todo el tiempo. Los clientes se quejan de que a veces llegan y el turno no figura.' },
        { type: 'box', kind: 'atencion', title: null, text: 'No diseñes la app todavía. Construí primero el mapa del sistema.' },
      ],
      entregables: [
        { text: 'Contexto: describí la organización y el problema sin proponer tecnología.', capRef: ['01', '04'] },
        { text: 'Objetivos: separá objetivos del negocio de funcionalidades posibles.', capRef: '01' },
        { text: 'Stakeholders: identificá al menos seis y explicá su relación.', capRef: '05' },
        { text: 'Procesos: describí el proceso actual de reserva y modificación.', capRef: '06' },
        { text: 'Reglas: identificá al menos ocho reglas o restricciones que deberían investigarse.', capRef: '07' },
        { text: 'Información: listá los datos que parecen necesarios y quién los utiliza.', capRef: '03' },
        { text: 'Alcance: proponé una primera frontera del sistema y justificá qué queda afuera.', capRef: '08' },
        { text: 'Problemas: diferenciá síntomas, causas posibles y efectos.', capRef: ['01', '09'] },
        { text: 'Preguntas abiertas: formulá al menos quince preguntas que todavía no tienen respuesta.', capRef: null },
        { text: 'Primera visión: recién ahora, proponé una solución de alto nivel.', capRef: '10' },
      ],
      autoevaluacion: {
        headers: ['Nivel', 'Podés…', 'Indicador'],
        rows: [
          ['Conocer', 'reconocer conceptos', 'Distinguís sistema, entorno, stakeholder, proceso y regla.'],
          ['Aplicar', 'usarlos en un caso', 'Podés construir un mapa inicial del problema.'],
          ['Analizar', 'tomar decisiones justificadas', 'Podés explicar por qué una frontera, pregunta o perspectiva es relevante.'],
        ],
      },
    },
    mapaDeSalida: {
      ideas: [
        { text: 'Una solución tecnológica es una propuesta para responder a una necesidad; no reemplaza el análisis de esa necesidad.', capRef: '01' },
        { text: 'Un sistema no es sinónimo de software.', capRef: '02' },
        { text: 'La frontera del sistema es una decisión de análisis.', capRef: ['02', '08'] },
        { text: 'Entradas, transformaciones, salidas, controles y feedback ayudan a construir una primera comprensión.', capRef: ['02', '03'] },
        { text: 'El contexto modifica la forma en que debemos entender y resolver un problema.', capRef: '04' },
        { text: 'Los stakeholders no son solamente usuarios.', capRef: '05' },
        { text: 'Los procesos describen cómo se realiza el trabajo.', capRef: '06' },
        { text: 'Las reglas de negocio condicionan decisiones y comportamientos, aunque nadie las haya escrito.', capRef: '07' },
        { text: 'Una misma situación puede observarse desde diferentes perspectivas.', capRef: '09' },
        { text: 'El objetivo del analista no es eliminar toda incertidumbre de entrada, sino convertirla en preguntas, modelos, decisiones y conocimiento compartido.', capRef: '10' },
      ],
      puente: {
        title: 'Puente al próximo volumen',
        text: 'Ahora que sabemos mirar el sistema, el siguiente paso es aprender a convertir esa comprensión en requisitos claros, verificables y trazables.',
      },
    },
    respuestasOrientativas: [
      {
        capId: '01',
        titulo: 'Antes de aceptar la propuesta',
        nivel: 'Conocer',
        respuesta: [
          '¿Cómo registran actualmente las horas?',
          '¿Quién necesita esa información?',
          '¿Para qué se utiliza?',
          '¿Qué problemas genera el proceso actual?',
          '¿Qué debería poder hacer un empleado y qué un supervisor?',
        ],
      },
      {
        capId: '02',
        titulo: 'Qué entra, qué pasa, qué sale',
        nivel: 'Aplicar',
        respuesta: [
          'Entradas: solicitud de turno, datos del cliente, datos del vehículo, servicio elegido, disponibilidad de empleados.',
          'Transformaciones: validar disponibilidad, aplicar reglas de asignación, registrar el turno.',
          'Salidas: turno confirmado, agenda actualizada, notificación al cliente, listado de trabajos del día.',
          'Entorno: el clima (si llueve no hay lavado exterior), un corte de luz o de internet, un feriado.',
        ],
      },
      {
        capId: '03',
        titulo: 'Mirar sin abrir el código',
        nivel: 'Analizar',
        respuesta: [
          'Depende de la aplicación elegida. Una forma de verificar tu análisis: ¿encontraste al menos un control (por ejemplo, una validación o un límite) y un mecanismo de feedback (calificaciones, reclamos, reportes)? Si no, probablemente estás mirando solo las pantallas.',
        ],
      },
      {
        capId: '04',
        titulo: 'Tablets sin buena señal',
        nivel: 'Aplicar',
        respuesta: [
          '¿Qué tareas deben funcionar sin conexión?',
          '¿Cuánto tiempo puede tolerarse información desactualizada?',
          '¿Existe otra conexión disponible?',
          '¿Qué pasa si dos personas registran cambios mientras están desconectadas?',
          '¿Qué información debe sincronizarse primero?',
        ],
      },
      {
        capId: '05',
        titulo: 'Ampliar el mapa',
        nivel: 'Aplicar',
        respuesta: [
          'Además de cliente, encargado, empleado y dueño, podrían aparecer: quien lleva la administración o la contabilidad, clientes corporativos con flotas, proveedores de pagos o mensajería y el municipio (habilitaciones, uso de agua). Ejemplo de riesgo: si no escuchamos a administración, los turnos pueden no reflejar cómo se cobra y factura.',
        ],
      },
      {
        capId: '06',
        titulo: 'El proceso actual en siete pasos',
        nivel: 'Aplicar',
        respuesta: [
          'El cliente escribe por WhatsApp. (actividad)',
          'El encargado abre la planilla. (actividad)',
          'Verifica si el horario está libre. (regla: no superponer turnos)',
          'Considera cuánto dura el servicio pedido. (regla: duración por servicio)',
          'Propone un horario. (actividad)',
          'El cliente confirma. (actividad)',
          'El encargado anota el turno y avisa al empleado. (actividad; regla: asignar según disponibilidad)',
        ],
      },
      {
        capId: '07',
        titulo: '¿Regla o costumbre?',
        nivel: 'Analizar',
        respuesta: [
          '¿Se aplica siempre o depende del día y la demanda?',
          '¿Quién la estableció y hay excepciones (por ejemplo, clientes frecuentes)?',
          '¿Qué pasa con el turno perdido: se cobra, se reprograma, se libera?',
          '¿Se le avisa al cliente?',
          '¿El sistema debería aplicarla solo o avisarle al encargado para que decida?',
        ],
      },
      {
        capId: '08',
        titulo: 'Trazar el límite',
        nivel: 'Analizar',
        respuesta: [
          'La agenda y las reglas quedan adentro. Clientes y empleados son actores del entorno que interactúan con el sistema: sus datos sí están adentro, las personas no. La base de datos es una decisión de implementación; en esta etapa conviene hablar de “información de turnos”.',
        ],
      },
      {
        capId: '09',
        titulo: 'Dos clics o revisión manual',
        nivel: 'Analizar',
        respuesta: [
          'Entrevistar a ambos por separado; averiguar qué turnos requieren revisión y por qué; medir cuántos son; explorar alternativas (reserva inmediata para servicios simples y revisión solo para los complejos). La pregunta no es quién gana, sino qué regla explica la revisión.',
        ],
      },
    ],
    bibliografia: [
      'Business Rules Group. Business Rules Manifesto.',
      'IIBA — The Business Analysis Standard / Business Analysis Core Concept Model (BACCM).',
      'ISO/IEC/IEEE 15288:2023 — Systems and software engineering — System life cycle processes.',
      'ISO/IEC/IEEE 42010:2022 — Software, systems and enterprise — Architecture description.',
      'OMG — Business Process Model and Notation (BPMN), especificación oficial.',
      'OMG — Semantics of Business Vocabulary and Business Rules (SBVR).',
      'OpenStax — Foundations of Information Systems, especialmente 1.1 Introduction to Information Systems y 4.1 Systems Analysis and Design for Application Development.',
      'SEBoK — Systems Engineering Body of Knowledge, entrada System Boundary; definición basada en Checkland, P. (1981). Systems Thinking, Systems Practice. Wiley.',
      'ISO/IEC/IEEE 29148:2018 — Requirements engineering. Base del próximo volumen.',
      'Sommerville, I. Software Engineering, 10.ª ed. Pearson.',
    ],
  },
}
