export default {
  id: '03',
  title: 'Casos de uso, historias de usuario y criterios de aceptación',
  subtitle: 'Del requisito a un comportamiento que se pueda discutir y verificar',
  ficha: {
    proposito: 'Representar comportamiento de forma que pueda discutirse, construirse y verificarse, eligiendo entre historias de usuario, casos de uso y criterios de aceptación.',
    publico: 'Personas que ya escriben requisitos y necesitan bajarlos a comportamientos concretos.',
    competencias: 'Conocer, aplicar y analizar: historias centradas en valor; actores, objetivos, flujos, alternativas y excepciones; criterios observables; escenarios Dado–Cuando–Entonces; tamaño de historias; relación entre artefactos y pruebas.',
    casoTransversal: 'Turnify. Partimos de los requisitos iniciales del Vol. 02 (TRN-FR-001 a TRN-FR-003) y los convertimos en comportamiento.',
    metodo: 'Cada capítulo parte de una situación, introduce un concepto, lo aplica al caso y termina con una práctica.',
    lugarEnElTronco: '03 · Fundamentos. Requiere los Vol. 01 y 02.',
    nivel: null,
    requiere: 'Vol. 01 y 02',
    preparaPara: 'UML · procesos · modelado · testing · diseño',
  },
  recorrido: [
    { chapterId: '01', title: 'Del requisito al comportamiento', pregunta: '¿Qué significa convertir una necesidad en algo observable?' },
    { chapterId: '02', title: 'Historias de usuario', pregunta: '¿Cómo expresamos valor desde la perspectiva de un actor?' },
    { chapterId: '03', title: 'Casos de uso', pregunta: '¿Cómo describimos una interacción paso a paso?' },
    { chapterId: '04', title: 'Flujos alternativos y excepciones', pregunta: '¿Qué ocurre cuando el camino normal no alcanza?' },
    { chapterId: '05', title: 'Criterios de aceptación', pregunta: '¿Cómo sabemos si lo construido cumple?' },
    { chapterId: '06', title: 'Dado–Cuando–Entonces', pregunta: '¿Cómo expresamos criterios como escenarios verificables?' },
    { chapterId: '07', title: 'Historias que se puedan trabajar', pregunta: '¿Cuándo una historia es demasiado grande, chica o técnica?' },
    { chapterId: '08', title: 'Historias, casos de uso y requisitos', pregunta: '¿Cómo se relacionan sin ser lo mismo?' },
    { chapterId: '09', title: 'De la representación a la prueba', pregunta: '¿Cómo conectamos aceptación, verificación y testing?' },
    { chapterId: '10', title: 'Especificación conductual de Turnify', pregunta: '¿Podemos reunir todo en un caso real?' },
  ],
  intro: {
    title: 'Sobre este volumen',
    body: [
      { type: 'p', text: 'Un requisito puede estar bien escrito y aun así ser demasiado abstracto para que un equipo pueda construirlo, probarlo o discutir sus límites. Este volumen trabaja una capa intermedia: representar qué necesita hacer una persona o un sistema, en qué contexto, con qué resultado esperado y bajo qué condiciones.' },
      { type: 'box', kind: 'idea-clave', title: 'Tres ideas que atraviesan el volumen', text: 'Una historia de usuario no reemplaza el análisis. Un caso de uso no es una lista de pantallas. Un criterio de aceptación no es decoración: hace observable el resultado esperado.' },
      { type: 'h3', text: 'El recorrido' },
      { type: 'p', text: 'El volumen va de la historia (el para qué) al caso de uso (cómo se interactúa) y a los criterios (cuándo está bien), y termina reuniendo las tres piezas en una especificación de comportamiento de Turnify.' },
      { type: 'h3', text: 'Cómo leer este cuadernillo' },
      { type: 'p', text: 'Los recuadros cumplen la misma función que en los volúmenes anteriores:' },
      { type: 'table', headers: ['Recuadro', 'Función'], rows: [
        ['IDEA CLAVE', 'La idea que tenés que llevarte del capítulo. Hay una sola por capítulo.'],
        ['EL CASO', 'Turnify y el lavadero: el ejemplo que acompaña toda la colección.'],
        ['PRACTICÁ', 'Un ejercicio, marcado con su nivel: conocer, aplicar o analizar. Las respuestas orientativas están al final.'],
        ['ATENCIÓN', 'Un error frecuente o una confusión que conviene evitar.'],
      ] },
      { type: 'p', text: 'Para vincular los artefactos usamos identificadores: HU para historias, CU para casos de uso y CA para criterios, que se suman a los TRN- del Vol. 02. Las definiciones remiten a una fuente citada al final de cada capítulo; los ejemplos y ejercicios son elaboración didáctica propia, y las reglas de Turnify no deben leerse como requisitos de un sistema real.' },
    ],
  },
  chapters: [
    {
      id: '01',
      title: 'Del requisito al comportamiento',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'En el Vol. 02 llegamos a requisitos verificables. Ahora necesitamos ver cómo se manifiestan cuando alguien usa el sistema.' },
        { type: 'p', text: 'En el volumen anterior trabajamos la necesidad, la clasificación de requisitos, su calidad y su verificabilidad. Ahora damos un paso más: representar cómo se manifiesta un requisito en una interacción, una funcionalidad o un resultado observable.' },
        { type: 'box', kind: 'el-caso', title: '"Que los clientes puedan sacar turnos"', text: 'El dueño del lavadero dice: "Necesito que los clientes puedan sacar turnos." Todavía no sabemos qué significa "sacar un turno": ¿elegir servicio?, ¿elegir horario?, ¿registrarse?, ¿recibir confirmación?, ¿qué pasa si el horario deja de estar disponible?' },
        { type: 'h3', text: '1.1 Tres preguntas antes de escribir' },
        { type: 'p', text: '¿Quién necesita hacer algo?' },
        { type: 'p', text: '¿Qué objetivo intenta alcanzar?' },
        { type: 'p', text: '¿Qué resultado permitiría decir que el objetivo se logró?' },
        { type: 'p', text: 'Cada pregunta anticipa una herramienta del volumen: el quién y el objetivo son el centro de las historias (cap. 02) y de los casos de uso (cap. 03); el resultado es la materia de los criterios de aceptación (cap. 05).' },
        { type: 'h3', text: '1.2 Representar no es diseñar' },
        { type: 'p', text: 'Una representación útil puede describir comportamiento sin decidir todavía la tecnología, la arquitectura o la interfaz. "El cliente selecciona un horario disponible" expresa un comportamiento observable; "usar un endpoint POST /appointments" ya pertenece a otra capa. Es la misma distinción entre requisito y diseño del Vol. 02 (cap. 01), ahora aplicada al comportamiento.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Describí lo que se observa, no cómo se construye. Si la representación empieza a llenarse de frameworks, endpoints, tablas o componentes de interfaz, probablemente estás especificando la solución antes de terminar de entender el comportamiento.' },
        { type: 'box', kind: 'practica', nivel: 'CONOCER', title: 'Tres preguntas', text: 'Aplicá las tres preguntas del 1.1 a este pedido del encargado: "Quiero que me avisen si cambia algún turno."' },
      ],
      fuentes: [],
    },
    {
      id: '02',
      title: 'Historias de usuario',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'La primera pregunta era quién necesita algo y para qué. La historia de usuario es la forma más breve de responderla.' },
        { type: 'p', text: 'IIBA define la historia de usuario (user story) como una declaración pequeña y concisa de una funcionalidad o cualidad necesaria para entregar valor a un stakeholder. Su utilidad está en abrir una conversación sobre una necesidad, no en contener toda la especificación.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La historia es una invitación a conversar, no una mini-especificación.' },
        { type: 'h3', text: '2.1 La forma clásica' },
        { type: 'p', text: 'La plantilla "Como [rol], quiero [objetivo], para [beneficio]" ayuda a recordar tres cosas: quién, qué necesita y para qué.' },
        { type: 'table', headers: ['Parte', 'Pregunta', 'En Turnify'], rows: [
          ['Como…', '¿Quién obtiene valor?', 'Como cliente del lavadero'],
          ['quiero…', '¿Qué objetivo busca?', 'quiero reservar un turno'],
          ['para…', '¿Qué valor obtiene?', 'para asegurarme un horario conveniente.'],
        ] },
        { type: 'p', text: 'Ron Jeffries resumió el uso de las historias en tres C: la tarjeta (la frase breve), la conversación (donde se descubre el detalle) y la confirmación (los criterios que permiten saber si se cumplió). La tercera C es la que trabajamos en los capítulos 05 y 06.' },
        { type: 'h3', text: '2.2 Lo que una historia no necesita' },
        { type: 'p', text: 'No necesita describir cada campo de pantalla.' },
        { type: 'p', text: 'No debería fijar la tecnología de implementación.' },
        { type: 'p', text: 'Puede necesitar conversación, reglas y criterios adicionales.' },
        { type: 'p', text: 'Puede descomponerse si resulta demasiado grande (cap. 07).' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Separar valor y tecnología', text: 'Reescribí: "Como usuario, quiero una pantalla React con calendario y selector de horarios conectado a Supabase." Separá el valor de la decisión técnica.' },
      ],
      fuentes: ['IIBA — BABOK Guide, Glosario: user story.', 'Cohn, M. — User Stories Applied.'],
    },
    {
      id: '03',
      title: 'Casos de uso',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'La historia dice qué se quiere y para qué. Cuando la interacción tiene varios pasos, reglas y desvíos, necesitamos algo más detallado.' },
        { type: 'p', text: 'Un caso de uso describe una interacción observable entre uno o más actores y una solución para alcanzar un objetivo específico. Es especialmente útil cuando la interacción tiene varios pasos, reglas, alternativas o excepciones que conviene hacer explícitas. La forma de escribirlos que usamos acá sigue la tradición de Alistair Cockburn.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un caso de uso describe una conversación entre actor y sistema para alcanzar un objetivo.' },
        { type: 'h3', text: '3.1 Los elementos' },
        { type: 'table', headers: ['Elemento', 'Qué representa'], rows: [
          ['Actor', 'Quién o qué interactúa con la solución para ese objetivo.'],
          ['Objetivo', 'El resultado que el actor intenta conseguir.'],
          ['Precondición', 'Lo que debe ser cierto antes de comenzar.'],
          ['Flujo principal', 'La secuencia normal que conduce al objetivo.'],
          ['Flujos alternativos', 'Variaciones que todavía permiten alcanzar el objetivo (cap. 04).'],
          ['Excepciones', 'Situaciones en las que el objetivo no puede alcanzarse (cap. 04).'],
          ['Postcondición', 'Lo que queda cierto al terminar con éxito.'],
        ] },
        { type: 'h3', text: '3.2 CU-01 · Reservar turno' },
        { type: 'table', headers: ['Campo', 'Valor'], rows: [
          ['Actor principal', 'Cliente'],
          ['Objetivo', 'Asegurar un horario para un servicio.'],
          ['Precondición', 'Existen servicios con horarios publicados.'],
          ['Postcondición', 'El turno queda confirmado y el horario deja de estar disponible.'],
          ['Origen', 'TRN-FR-001 y TRN-FR-002 (Vol. 02).'],
        ] },
        { type: 'table', headers: ['Paso', 'Actor', 'Acción'], rows: [
          ['1', 'Cliente', 'Solicita reservar un turno.'],
          ['2', 'Sistema', 'Muestra los servicios disponibles.'],
          ['3', 'Cliente', 'Selecciona un servicio.'],
          ['4', 'Sistema', 'Muestra los horarios disponibles para ese servicio.'],
          ['5', 'Cliente', 'Selecciona un horario, ingresa sus datos y confirma.'],
          ['6', 'Sistema', 'Verifica que el horario siga disponible y que los datos estén completos, y registra el turno.'],
          ['7', 'Sistema', 'Informa la confirmación al cliente.'],
        ] },
        { type: 'box', kind: 'atencion', title: null, text: 'El caso de uso no describe la interfaz pixel por pixel. Su foco es la interacción necesaria para alcanzar el objetivo y las condiciones que la afectan. "Selecciona un horario" no dice si es un calendario, una lista o un mensaje de WhatsApp.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Tu primer caso de uso', text: 'Escribí el caso de uso "Consultar agenda del día" para el encargado: actor, objetivo, precondición, postcondición y un flujo principal de entre cuatro y seis pasos.' },
      ],
      fuentes: ['IIBA — BABOK Guide, Glosario: use case, actor.', 'IIBA — Eliciting Requirements With Use Case.'],
    },
    {
      id: '04',
      title: 'Flujos alternativos y excepciones',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'El flujo del CU-01 describe el día en que todo sale bien. El análisis empieza de verdad cuando preguntamos qué pasa los otros días.' },
        { type: 'p', text: 'Un análisis pobre describe únicamente el camino feliz. En sistemas reales, gran parte del trabajo consiste en decidir qué ocurre cuando algo cambia, falla o contradice una regla.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La diferencia está en el objetivo. En un flujo alternativo, el actor todavía puede alcanzar su objetivo por otro camino. En una excepción, no puede.' },
        { type: 'h3', text: '4.1 Los desvíos del CU-01' },
        { type: 'p', text: 'Cada desvío se numera con el paso donde ocurre y una letra: 6a es el primer desvío del paso 6.' },
        { type: 'table', headers: ['Paso', 'Situación', 'Tipo', 'Pregunta de análisis'], rows: [
          ['4a', 'El servicio no tiene horarios disponibles.', 'Alternativo', '¿Se le ofrece otra fecha u otro servicio?'],
          ['6a', 'Faltan datos obligatorios.', 'Alternativo', '¿Qué dato falta y cuándo se detecta?'],
          ['6b', 'El horario se ocupó entre el paso 4 y el 6.', 'Alternativo', '¿Qué debe ver el cliente? ¿Vuelve al paso 4?'],
          ['6c', 'El sistema no puede registrar el turno.', 'Excepción', '¿Qué se le informa? ¿Queda algún rastro del intento?'],
          ['7a', 'Falla el envío de la confirmación.', 'Alternativo', 'El turno ya existe: ¿se reintenta el aviso?, ¿por otro medio?'],
        ] },
        { type: 'p', text: 'Fijate en el 7a: aunque algo falló, el cliente consiguió su turno, así que no es una excepción del caso de uso. Y el 6b es la situación de concurrencia que el Vol. 02 marcó como capaz de cambiar la arquitectura: el caso de uso la hace visible sin resolverla todavía.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Cancelar turno', text: 'Escribí el caso de uso "Cancelar turno" para el cliente: un flujo principal, dos flujos alternativos y una excepción, numerados por paso. No diseñes todavía la pantalla.' },
      ],
      fuentes: ['Cockburn, A. — Writing Effective Use Cases.', 'IIBA — BABOK Guide, Glosario: use case.'],
    },
    {
      id: '05',
      title: 'Criterios de aceptación',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ya sabemos qué se quiere y cómo se interactúa. Falta acordar cuándo está bien: la tercera C de la historia.' },
        { type: 'p', text: 'IIBA define los criterios de aceptación como condiciones asociadas a requisitos, productos o entregables que deben cumplirse para lograr la aceptación de un stakeholder. En el Vol. 02 (cap. 07) los usamos para verificar requisitos; acá los asociamos a historias y casos de uso.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un buen criterio permite que dos personas razonables observen el sistema y lleguen a la misma conclusión sobre si se cumple.' },
        { type: 'h3', text: '5.1 Criterios para las historias de Turnify' },
        { type: 'table', headers: ['Historia', 'Criterios de aceptación'], rows: [
          ['Como cliente, quiero reservar un turno para asegurarme un horario conveniente.', 'El turno queda registrado con servicio, horario y datos del cliente. El cliente ve una confirmación con fecha, hora y servicio. No se confirma un horario que ya no está disponible.'],
          ['Como cliente, quiero cancelar mi turno para liberar el horario si no puedo asistir.', 'Si faltan más de [X] horas para el turno, pasa a estado cancelado y el horario vuelve a estar disponible. X a definir con el dueño. Si faltan menos de [X] horas, el sistema no cancela e informa el motivo.'],
        ] },
        { type: 'p', text: 'Los criterios están escritos en lenguaje natural. En el próximo capítulo vamos a ver cómo darles forma de escenario.' },
        { type: 'h3', text: '5.2 Características de un buen criterio' },
        { type: 'p', text: 'Es claro y específico.' },
        { type: 'p', text: 'Describe una condición observable.' },
        { type: 'p', text: 'Permite determinar si se cumple o no.' },
        { type: 'p', text: 'No depende de detalles de implementación.' },
        { type: 'p', text: 'Cubre los resultados esperados y, cuando hay reglas, las situaciones en que no se cumplen.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: '¿Criterio o deseo?', text: 'Evaluá estos criterios para "reservar turno" y reescribí los que no sirvan: "La reserva funciona bien." "La confirmación es rápida." "El cliente recibe un aviso con la fecha y la hora del turno."' },
      ],
      fuentes: ['IIBA — BABOK Guide, Glosario: acceptance criteria; técnica Acceptance and Evaluation Criteria.', 'Atlassian — What is Acceptance Criteria?'],
    },
    {
      id: '06',
      title: 'Dado–Cuando–Entonces',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Algunos criterios se entienden mejor como una pequeña escena: una situación, algo que pasa y un resultado.' },
        { type: 'p', text: 'El formato Dado–Cuando–Entonces (Given–When–Then) expresa un criterio como escenario: una condición inicial, un evento y un resultado esperado. Surgió en el desarrollo guiado por comportamiento (BDD), donde además se usa para automatizar pruebas.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un escenario es un criterio con contexto: sin el "dado", el resultado no se puede juzgar.' },
        { type: 'table', headers: ['Parte', 'Significado', 'En Turnify'], rows: [
          ['Dado', 'El contexto o condición inicial.', 'Dado un horario disponible para el servicio elegido,'],
          ['Cuando', 'La acción o el evento.', 'cuando el cliente confirma la reserva,'],
          ['Entonces', 'El resultado observable esperado.', 'entonces el turno queda confirmado y el cliente ve la confirmación.'],
        ] },
        { type: 'box', kind: 'atencion', title: null, text: 'Esto no es un curso de automatización. Gherkin y BDD llevan este formato mucho más lejos. Acá lo usamos como herramienta de análisis y comunicación.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Tres escenarios', text: 'Escribí tres escenarios para "reservar turno": uno exitoso, uno donde el horario deja de estar disponible (desvío 6b del CU-01) y uno donde falta un dato obligatorio (6a).' },
      ],
      fuentes: ['North, D. — "Introducing BDD".', 'IIBA — técnica Acceptance and Evaluation Criteria.'],
    },
    {
      id: '07',
      title: 'Historias que se puedan trabajar',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Con historias, casos y criterios ya podemos representar comportamiento. Pero no toda historia bien formada sirve para trabajar.' },
        { type: 'p', text: 'Una historia puede ser correcta y aun así resultar poco útil si es enorme, demasiado pequeña, dependiente de otras o difícil de verificar. La heurística INVEST propone seis preguntas para revisarla:' },
        { type: 'table', headers: ['Criterio', 'Pregunta'], rows: [
          ['Independiente (Independent)', '¿Puede entenderse y trabajarse sin una dependencia innecesaria?'],
          ['Negociable (Negotiable)', '¿Es una conversación sobre necesidad y valor, no un contrato técnico cerrado?'],
          ['Valiosa (Valuable)', '¿Se puede explicar qué valor aporta y a quién?'],
          ['Estimable (Estimable)', '¿Hay información suficiente para que el equipo aproxime el trabajo?'],
          ['Pequeña (Small)', '¿Tiene un tamaño razonable para el contexto del equipo?'],
          ['Verificable (Testable)', '¿Tiene criterios que permitan saber si se cumplió?'],
        ] },
        { type: 'box', kind: 'idea-clave', title: null, text: 'INVEST no convierte una historia en buena: es una lista de preguntas para detectar problemas y abrir conversación.' },
        { type: 'h3', text: '7.1 Señales de una historia demasiado grande' },
        { type: 'p', text: 'Incluye varios objetivos distintos.' },
        { type: 'p', text: 'Tiene una lista extensa de criterios no relacionados.' },
        { type: 'p', text: 'No puede demostrarse como una unidad coherente.' },
        { type: 'p', text: 'Obliga a describir muchas reglas de negocio independientes.' },
        { type: 'h3', text: '7.2 Cómo partirla' },
        { type: 'p', text: 'El caso de uso ayuda a partir historias: se puede separar por objetivo (reservar, cancelar), por paso del flujo, por regla de negocio o dejando el camino principal en una historia y los flujos alternativos en otras.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Partir una historia', text: 'Partí esta historia en historias más pequeñas y justificá el criterio de corte: "Como cliente, quiero reservar, cancelar y reprogramar mis turnos y recibir avisos de todos los cambios."' },
      ],
      fuentes: ['Wake, B. — "INVEST in Good Stories, and SMART Tasks".', 'Cohn, M. — User Stories Applied.'],
    },
    {
      id: '08',
      title: 'Historias, casos de uso y requisitos',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Ya conocemos cada herramienta por separado. Toca ver cómo conviven sin pisarse.' },
        { type: 'p', text: 'No son sinónimos. Pueden representar partes relacionadas del mismo problema, pero cumplen funciones diferentes.' },
        { type: 'table', headers: ['Artefacto', 'Foco', 'Nivel típico', 'Útil para'], rows: [
          ['Requisito', 'Necesidad o condición que debe satisfacerse.', 'Variable', 'Especificar y gestionar necesidades.'],
          ['Historia de usuario', 'Necesidad u objetivo desde un stakeholder.', 'Conciso', 'Conversación, priorización y refinamiento.'],
          ['Caso de uso', 'Interacción actor–solución para un objetivo.', 'Detallado', 'Analizar flujos, alternativas y excepciones.'],
          ['Criterio de aceptación', 'Condición verificable de aceptación.', 'Específico', 'Determinar si el resultado cumple.'],
        ] },
        { type: 'box', kind: 'idea-clave', title: null, text: 'No existe una única representación correcta para todos los problemas. La elección depende del contexto, del nivel de detalle necesario y de cómo trabaja el equipo.' },
        { type: 'p', text: 'Una misma necesidad puede tener un requisito formal, una historia para el backlog, un caso de uso para analizar el comportamiento y criterios de aceptación para verificar un incremento. Eso no significa que haya que producir los cuatro siempre.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Elegir la herramienta', text: '¿Qué representación priorizarías en cada caso? (a) La regla "no puede haber dos turnos en el mismo horario". (b) El encargado necesita ver la agenda del día. (c) La reserva, con todos sus desvíos.' },
      ],
      fuentes: ['Wiegers, K. y Beatty, J. — Software Requirements.', 'IIBA — BABOK Guide, Glosario.'],
    },
    {
      id: '09',
      title: 'De la representación a la prueba',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Una representación que no se puede comprobar queda en el papel. Este capítulo la conecta con la verificación.' },
        { type: 'p', text: 'El análisis gana fuerza cuando deja de ser un documento aislado y se conecta con la verificación y la validación, que distinguimos en el Vol. 02 (cap. 07). Los criterios de aceptación son el puente entre lo que se espera y lo que se observa.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Cada criterio de aceptación debería poder convertirse en al menos un escenario de prueba.' },
        { type: 'table', headers: ['Necesidad', 'Representación', 'Verificación'], rows: [
          ['Reservar un horario disponible', 'HU + criterios', 'Escenario exitoso'],
          ['No permitir doble reserva', 'Regla + CU-01 (6b) + criterio', 'Dos intentos sobre el mismo horario'],
          ['Cancelar dentro del plazo', 'CU + criterio', 'Cancelar antes del límite'],
          ['Rechazar la cancelación tardía', 'Flujo alternativo + criterio', 'Intentar cancelar después del límite'],
        ] },
        { type: 'h3', text: '9.1 Trazabilidad mínima' },
        { type: 'p', text: 'En el Vol. 02 (cap. 09) vimos la cadena completa. Para un proyecto pequeño no hace falta una matriz gigantesca, pero sí poder responder: ¿de dónde salió esta necesidad?, ¿qué comportamiento la representa?, ¿cómo la verificamos?, ¿qué cambia si el requisito cambia?' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Una mini cadena', text: 'Elegí tres requisitos de Turnify del Vol. 02 y construí para cada uno la cadena: requisito → historia o caso de uso → criterio → escenario de prueba.' },
      ],
      fuentes: ['ISO/IEC/IEEE 29148:2018 — Requirements engineering.', 'IIBA — técnica Acceptance and Evaluation Criteria.'],
    },
    {
      id: '10',
      title: 'Especificación conductual de Turnify',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Es momento de reunir historia, caso de uso y criterios sobre el caso.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La historia dice para qué; el caso de uso, cómo se interactúa; los criterios, cuándo está bien.' },
        { type: 'h3', text: 'HU-01 · Reservar turno' },
        { type: 'p', text: 'Como cliente del lavadero, quiero elegir un servicio y un horario disponible para reservar un turno y asegurarme la atención. Origen: TRN-FR-001 y TRN-FR-002. Interacción: CU-01.' },
        { type: 'table', headers: ['Criterio', 'Dado', 'Cuando', 'Entonces'], rows: [
          ['CA-01.1 Reserva exitosa', 'Un servicio con horarios disponibles', 'El cliente elige un horario y confirma', 'El turno queda confirmado con servicio, horario y datos del cliente, y el cliente ve la confirmación.'],
          ['CA-01.2 Horario ocupado', 'Un horario que se ocupó después de mostrarse', 'El cliente confirma', 'El sistema no confirma, informa que el horario ya no está disponible y muestra otros.'],
          ['CA-01.3 Datos incompletos', 'Falta un dato obligatorio', 'El cliente confirma', 'El sistema no registra el turno e indica qué dato falta.'],
        ] },
        { type: 'h3', text: 'HU-02 · Cancelar turno' },
        { type: 'p', text: 'Como cliente, quiero cancelar mi turno dentro del plazo permitido para liberar el horario si ya no puedo asistir. El valor de X sigue abierto (cap. 05): queda visible en lugar de inventarlo.' },
        { type: 'table', headers: ['Criterio', 'Dado', 'Cuando', 'Entonces'], rows: [
          ['CA-02.1 Cancelación válida', 'Un turno vigente con más de [X] horas de anticipación', 'El cliente lo cancela', 'El turno pasa a cancelado y el horario vuelve a estar disponible.'],
          ['CA-02.2 Cancelación tardía', 'Un turno con menos de [X] horas de anticipación', 'El cliente intenta cancelarlo', 'El sistema no cancela e informa el motivo.'],
          ['CA-02.3 Turno inexistente', 'No hay un turno vigente que se pueda identificar', 'El cliente intenta cancelar', 'El sistema informa que no puede realizar la cancelación.'],
        ] },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Dos personas, un horario', text: 'El dueño agrega: "Si dos personas intentan reservar el mismo horario al mismo tiempo, solo una puede quedarse con él." Sin escribir código, identificá requisito, regla, historia (si corresponde), criterio, prueba y pregunta abierta.' },
      ],
      fuentes: [],
    },
  ],
  cierre: {
    desafioIntegrador: {
      title: 'Desafío integrador: reservar, cancelar y recibir avisos',
      body: [
        { type: 'p', text: 'La empresa de los desafíos anteriores ahora quiere una plataforma de turnos para varios servicios.' },
        { type: 'box', kind: 'el-caso', title: '"Queremos que el cliente pueda reservar, cancelar y recibir avisos"', text: 'Es el pedido completo. Todo lo demás lo vas a tener que descubrir.' },
      ],
      entregables: [
        { text: 'Escribí tres historias de usuario.', capRef: '02' },
        { text: 'Elegí una y desarrollá su caso de uso.', capRef: '03' },
        { text: 'Incluí al menos un flujo alternativo, una excepción y una situación de concurrencia.', capRef: '04' },
        { text: 'Identificá al menos tres reglas de negocio que condicionen el comportamiento.', capRef: 'Vol. 01, cap. 07' },
        { text: 'Escribí cuatro criterios de aceptación.', capRef: '05' },
        { text: 'Transformá dos criterios en escenarios Dado–Cuando–Entonces.', capRef: '06' },
        { text: 'Revisá tus historias con INVEST y partí las que sean demasiado grandes.', capRef: '07' },
        { text: 'Relacioná cada historia con al menos una forma de verificación.', capRef: '09' },
        { text: 'Indicá qué información todavía necesitás preguntar al stakeholder.', capRef: null },
      ],
      autoevaluacion: {
        headers: ['Nivel', 'Podés…', 'Indicador'],
        rows: [
          ['Conocer', 'distinguir artefactos', 'No confundís requisito, historia, caso de uso y criterio de aceptación.'],
          ['Aplicar', 'representar comportamiento', 'Escribís historias centradas en valor, casos de uso con desvíos y criterios observables.'],
          ['Analizar', 'elegir y cuestionar', 'Detectás historias demasiado grandes, elegís la representación adecuada y formulás preguntas cuando la información no alcanza.'],
        ],
      },
    },
    mapaDeSalida: {
      ideas: [
        { text: 'Representar comportamiento no es diseñar la solución.', capRef: '01' },
        { text: 'Una historia de usuario expresa quién, qué y para qué, y abre una conversación.', capRef: '02' },
        { text: 'Un caso de uso describe la interacción entre actor y sistema para alcanzar un objetivo.', capRef: '03' },
        { text: 'Los flujos alternativos todavía alcanzan el objetivo; las excepciones no.', capRef: '04' },
        { text: 'Un criterio de aceptación es una condición observable sobre la que hay acuerdo.', capRef: '05' },
        { text: 'Dado–Cuando–Entonces convierte un criterio en un escenario con contexto.', capRef: '06' },
        { text: 'INVEST ayuda a detectar historias difíciles de trabajar, y el caso de uso ayuda a partirlas.', capRef: '07' },
        { text: 'Requisitos, historias, casos y criterios se complementan; no hace falta producirlos todos siempre.', capRef: '08' },
        { text: 'Cada criterio debería poder convertirse en al menos un escenario de prueba.', capRef: '09' },
      ],
      puente: {
        title: 'Puente al próximo volumen',
        text: 'El comportamiento ya está más claro. El siguiente paso es representarlo visualmente: actores, actividades, relaciones, estados y estructuras, con modelos que permitan comunicar el sistema con distintos niveles de detalle.',
      },
    },
    respuestasOrientativas: [
      {
        capId: '01',
        titulo: 'Tres preguntas',
        nivel: 'Conocer',
        respuesta: [
          'Quién: el encargado.',
          'Objetivo: enterarse a tiempo de los cambios para reorganizar el trabajo.',
          'Resultado: falta definirlo. ¿Qué cuenta como "cambio"? ¿Cuánto tiempo después es "a tiempo"? Son preguntas para la conversación.',
        ],
      },
      {
        capId: '02',
        titulo: 'Separar valor y tecnología',
        nivel: 'Aplicar',
        respuesta: [
          '"Como cliente, quiero consultar los horarios disponibles para elegir un turno que pueda reservar." React, el calendario y Supabase son decisiones de diseño: pueden registrarse aparte, pero no pertenecen a la historia.',
        ],
      },
      {
        capId: '03',
        titulo: 'Consultar agenda del día',
        nivel: 'Aplicar',
        respuesta: [
          'Actor: encargado. Objetivo: conocer los trabajos del día. Precondición: el encargado está identificado. Postcondición: el encargado vio los turnos del día (la consulta no modifica datos). Flujo: 1) el encargado solicita la agenda del día; 2) el sistema muestra los turnos con horario, servicio, cliente y empleado asignado; 3) el encargado selecciona un turno; 4) el sistema muestra su detalle.',
        ],
      },
      {
        capId: '04',
        titulo: 'Cancelar turno',
        nivel: 'Aplicar',
        respuesta: [
          'Flujo principal: 1) el cliente identifica su turno; 2) el sistema lo muestra; 3) el cliente solicita cancelar; 4) el sistema verifica el plazo, cancela y libera el horario; 5) el sistema confirma la cancelación.',
          'Alternativo 1a: el cliente no encuentra su turno; el sistema ofrece buscarlo por otro dato.',
          'Alternativo 5a: falla el aviso de confirmación; la cancelación vale igual y se reintenta el aviso.',
          'Excepción 4a: la cancelación está fuera de plazo; el sistema no cancela e informa el motivo.',
        ],
      },
      {
        capId: '05',
        titulo: '¿Criterio o deseo?',
        nivel: 'Analizar',
        respuesta: [
          '"Funciona bien" no es observable. "Es rápida" no dice cuánto: por ejemplo, "la confirmación se muestra en menos de 2 segundos". El tercero es observable, aunque conviene precisar por qué medio se envía el aviso.',
        ],
      },
      {
        capId: '06',
        titulo: 'Tres escenarios',
        nivel: 'Aplicar',
        respuesta: [
          'Éxito: dado un horario disponible, cuando el cliente confirma, entonces el turno queda confirmado y el cliente ve la confirmación.',
          'Horario ocupado: dado un horario que se ocupó después de mostrarse, cuando el cliente confirma, entonces el sistema no confirma e informa que ya no está disponible.',
          'Dato faltante: dado que falta el teléfono del cliente, cuando confirma, entonces el sistema no registra el turno e indica qué falta.',
        ],
      },
      {
        capId: '07',
        titulo: 'Partir una historia',
        nivel: 'Aplicar',
        respuesta: [
          'Por objetivo: una historia para reservar, otra para cancelar, otra para reprogramar y otra para los avisos. Los avisos, a su vez, podrían partirse por evento (reserva, cancelación, cambio). Reprogramar puede esperar si reservar y cancelar ya resuelven lo principal.',
        ],
      },
      {
        capId: '08',
        titulo: 'Elegir la herramienta',
        nivel: 'Analizar',
        respuesta: [
          '(a) Una regla de negocio con criterios de aceptación: no es un objetivo de un actor. (b) Una historia de usuario con criterios alcanza: la interacción es simple. (c) Un caso de uso: los desvíos son justamente lo que hay que analizar.',
        ],
      },
      {
        capId: '09',
        titulo: 'Una mini cadena',
        nivel: 'Aplicar',
        respuesta: [
          'Por ejemplo: TRN-FR-002 → CU-01, desvío 6b → CA-01.2 → prueba: dos clientes intentan confirmar el mismo horario y se comprueba que solo uno queda confirmado.',
        ],
      },
      {
        capId: '10',
        titulo: 'Dos personas, un horario',
        nivel: 'Analizar',
        respuesta: [
          'Requisito: El sistema no deberá confirmar más de un turno para el mismo horario y recurso (es TRN-FR-002 del Vol. 02).',
          'Regla: Un horario no puede tener simultáneamente dos turnos confirmados incompatibles.',
          'Historia: No hace falta una historia nueva: la concurrencia no es un objetivo de un actor. Conviene agregarla como criterio de HU-01.',
          'Criterio: Dado un único horario disponible, cuando dos clientes lo confirman al mismo tiempo, entonces como máximo uno obtiene un turno confirmado y el otro recibe un aviso.',
          'Prueba: Ejecutar dos confirmaciones simultáneas sobre el mismo horario y comprobar el estado final.',
          'Pregunta abierta: ¿Se le puede "reservar temporalmente" el horario a quien lo está eligiendo? ¿Por cuánto tiempo?',
        ],
      },
    ],
    bibliografia: [
      'IIBA — The Business Analysis Standard.',
      'IIBA — BABOK Guide, Apéndice A: Glosario. Entradas: acceptance criteria, actor, use case, user story.',
      'IIBA — Business Analysis Technique: Acceptance and Evaluation Criteria.',
      'IIBA — Eliciting Requirements With Use Case.',
      'Cohn, M. (2004). User Stories Applied: For Agile Software Development. Addison-Wesley.',
      'Wiegers, K. y Beatty, J. (2013). Software Requirements, 3.ª ed. Microsoft Press.',
      'Atlassian — What is Acceptance Criteria?',
      'ISO/IEC/IEEE 29148:2018 — Requirements engineering.',
      'Cockburn, A. (2000). Writing Effective Use Cases. Addison-Wesley.',
      'Jeffries, R. (2001). "Essential XP: Card, Conversation, Confirmation".',
      'North, D. (2006). "Introducing BDD".',
      'Wake, B. (2003). "INVEST in Good Stories, and SMART Tasks".',
      'OMG — Unified Modeling Language (UML). Base del próximo volumen.',
      'IIBA — User Story: Useful Technique But Not Always Optimal?; Tips for writing user stories (serie).',
      'Atlassian — User Stories With Examples and a Template.',
    ],
  },
}
