export default {
  id: '04',
  title: 'Modelado de sistemas con UML y BPMN',
  subtitle: 'Representar para entender, comunicar y tomar decisiones',

  ficha: {
    proposito: 'Elegir y construir el modelo adecuado para cada pregunta, y mantener coherentes los modelos entre sí.',
    publico: 'Personas que ya describen comportamiento con palabras y necesitan representarlo visualmente.',
    competencias: 'Conocer, aplicar y analizar: vistas de estructura, comportamiento, interacción y procesos; diagramas UML básicos; BPMN a nivel de análisis; consistencia entre modelos.',
    casoTransversal: 'Turnify. Los diagramas del volumen representan lo que ya especificamos: CU-01, HU-01 y HU-02 del Vol. 03 y los requisitos TRN del Vol. 02.',
    metodo: 'Cada capítulo parte de una pregunta, presenta un tipo de modelo, lo dibuja para Turnify y termina con una práctica.',
    lugarEnElTronco: '04 · Fundamentos. Requiere los Vol. 01 a 03.',
    nivel: null,
    requiere: 'Vol. 01 a 03',
    preparaPara: 'dominio · datos · arquitectura · diseño · testing',
  },

  recorrido: [
    { chapterId: '01', title: 'Modelar para pensar', pregunta: '¿Por qué modelamos y qué hace útil a un modelo?' },
    { chapterId: '02', title: 'Elegir la vista', pregunta: '¿Qué modelo responde la pregunta que tengo?' },
    { chapterId: '03', title: 'UML como lenguaje', pregunta: '¿Qué es UML y cómo se organizan sus diagramas?' },
    { chapterId: '04', title: 'Casos de uso y actores', pregunta: '¿Quién interactúa con el sistema y con qué objetivos?' },
    { chapterId: '05', title: 'Diagramas de actividad', pregunta: '¿Cómo fluye el trabajo, con decisiones y paralelismo?' },
    { chapterId: '06', title: 'Diagramas de secuencia', pregunta: '¿Quién le envía qué a quién, y en qué orden?' },
    { chapterId: '07', title: 'Clases y dominio', pregunta: '¿Qué conceptos, atributos y relaciones forman el dominio?' },
    { chapterId: '08', title: 'Máquinas de estados', pregunta: '¿Cómo cambia un turno ante los eventos?' },
    { chapterId: '09', title: 'BPMN', pregunta: '¿Cómo modelamos el proceso de negocio de punta a punta?' },
    { chapterId: '10', title: 'Integración de modelos', pregunta: '¿Cuentan todos los modelos la misma historia?' },
  ],

  intro: {
    title: 'Sobre este volumen',
    body: [
      { type: 'p', text: 'Modelar no significa llenar una entrega de diagramas. Un modelo es una representación deliberada de una parte del sistema, construida para responder una pregunta. UML ofrece una familia de lenguajes gráficos para visualizar, especificar y documentar sistemas; BPMN se orienta específicamente a representar procesos de negocio.' },
      { type: 'box', kind: 'idea-clave', title: null, text: 'Antes de dibujar, preguntá qué querés comunicar. Un diagrama sin pregunta puede ser correcto y, aun así, inútil.' },
      { type: 'h2', text: 'El recorrido' },
      { type: 'p', text: 'Los tres primeros capítulos enseñan a elegir; del 04 al 09 se construye un modelo por capítulo, siempre sobre la reserva de un turno; el 10 comprueba que todos cuenten la misma historia.' },
      { type: 'h2', text: 'Cómo leer este cuadernillo' },
      { type: 'p', text: 'Los recuadros cumplen la misma función que en los volúmenes anteriores:' },
      {
        type: 'table',
        headers: ['Recuadro', 'Qué significa'],
        rows: [
          ['IDEA CLAVE', 'La idea que tenés que llevarte del capítulo. Hay una sola por capítulo.'],
          ['EL CASO', 'Turnify y el lavadero: el ejemplo que acompaña toda la colección.'],
          ['PRACTICÁ', 'Un ejercicio, marcado con su nivel: conocer, aplicar o analizar. Las respuestas orientativas están al final.'],
          ['ATENCIÓN', 'Un error frecuente o una confusión que conviene evitar.'],
        ],
      },
      { type: 'p', text: 'Los diagramas fueron elaborados para este cuadernillo y muestran un subconjunto de la notación: la necesaria para análisis. Este volumen no pretende cubrir toda la especificación UML ni todos los elementos de BPMN. Las definiciones remiten a una fuente citada al final de cada capítulo.' },
    ],
  },

  chapters: [
    {
      id: '01',
      title: 'Modelar para pensar',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'En los Vol. 01 a 03 describimos Turnify con palabras y tablas. Algunas cosas se entienden mejor dibujadas.' },
        { type: 'p', text: 'Un modelo reduce parte de la complejidad para hacer visible algo que nos interesa. El modelo no es el sistema: es una representación con propósito, alcance y nivel de detalle. De hecho, ya hiciste uno: el rectángulo con el que trazaste la frontera del lavadero en el Vol. 01 (cap. 08) era un modelo.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un modelo es útil si responde una pregunta que el texto responde peor.' },
        { type: 'p', text: 'Martin Fowler distingue tres usos de UML: como boceto para pensar y conversar, como plano detallado para construir y como lenguaje de programación. En análisis, el uso más frecuente es el primero, y es el que practica este volumen.' },
        { type: 'box', kind: 'atencion', title: null, text: 'No todo necesita modelarse. Modelar por obligación produce documentación que nadie consulta. Modelá cuando la representación ayude a descubrir, explicar, decidir o verificar.' },
        { type: 'box', kind: 'practica', nivel: 'CONOCER', title: 'Tu primer modelo', text: 'Volvé al rectángulo del Vol. 01 (cap. 08). ¿Qué pregunta respondía? ¿Qué pregunta no podía responder?' },
      ],
      fuentes: ['Fowler, M. — UML Distilled.'],
    },
    {
      id: '02',
      title: 'Elegir la vista',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Si cada modelo responde una pregunta, lo primero es saber qué pregunta tenemos.' },
        { type: 'p', text: 'Una misma realidad puede observarse desde perspectivas diferentes, como vimos con los stakeholders en el Vol. 01 (cap. 09). Antes de abrir una herramienta de diagramación, escribí la pregunta.' },
        {
          type: 'table',
          headers: ['Si querés saber…', 'Podés empezar con…', 'Cap.'],
          rows: [
            ['Qué queda dentro y fuera del sistema', 'Mapa de contexto', 'Vol. 01'],
            ['Quién interactúa con el sistema y para qué', 'Diagrama de casos de uso', '04'],
            ['Qué actividades ocurren, en qué orden y quién las hace', 'Diagrama de actividad', '05'],
            ['Qué mensajes se intercambian y en qué orden', 'Diagrama de secuencia', '06'],
            ['Qué conceptos forman el dominio y cómo se relacionan', 'Modelo de dominio (clases)', '07'],
            ['Cómo cambia un turno a lo largo de su vida', 'Máquina de estados', '08'],
            ['Cómo se organiza un proceso entre participantes', 'BPMN', '09'],
          ],
        },
        { type: 'box', kind: 'idea-clave', title: null, text: 'La pregunta elige el modelo, no al revés.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Dos vistas para cancelar', text: 'Para “cancelar un turno”, elegí dos modelos diferentes y explicá qué pregunta responde cada uno. No vale decir solamente “porque UML lo pide”.' },
      ],
      fuentes: [],
    },
    {
      id: '03',
      title: 'UML como lenguaje',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Casi todos los modelos de la tabla anterior pertenecen a un mismo lenguaje. Conviene conocer su mapa antes de recorrerlo.' },
        { type: 'p', text: 'UML (Unified Modeling Language) es un lenguaje estandarizado por el OMG para visualizar, especificar y documentar modelos. Su versión vigente es la 2.5.1.' },
        { type: 'p', text: 'La especificación organiza los diagramas en dos grandes familias: los de estructura, que muestran qué elementos existen y cómo se relacionan, y los de comportamiento, que muestran qué ocurre. Los diagramas de interacción, como el de secuencia, son un subgrupo del comportamiento.' },
        {
          type: 'table',
          headers: ['Familia', 'En este volumen', 'Qué ayuda a comunicar'],
          rows: [
            ['Estructura', 'Clases (cap. 07)', 'Qué elementos existen y cómo se organizan.'],
            ['Comportamiento', 'Casos de uso (04), actividades (05), máquinas de estados (08)', 'Qué hace el sistema y cómo cambia.'],
            ['Comportamiento · interacción', 'Secuencia (06)', 'Cómo colaboran los participantes a lo largo del tiempo.'],
          ],
        },
        { type: 'p', text: 'Hay más diagramas (de componentes, de despliegue, de comunicación, entre otros). Los dejamos para los volúmenes de arquitectura.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'UML no es una metodología de desarrollo: es un lenguaje de modelado. Una metodología decide cuándo y para qué usar cada modelo; UML solo define cómo expresarlo.' },
      ],
      fuentes: ['OMG — Unified Modeling Language Specification, v2.5.1.', 'Fowler, M. — UML Distilled.'],
    },
    {
      id: '04',
      title: 'Casos de uso y actores',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'En el Vol. 03 escribimos el CU-01 paso a paso. El diagrama de casos de uso muestra todos los objetivos juntos, sin los pasos.' },
        { type: 'p', text: 'El caso de uso parte del objetivo de un actor. El diagrama no reemplaza la descripción del Vol. 03: la complementa con una vista de conjunto, útil para discutir alcance.' },
        { type: 'p', text: 'El diagrama tiene cuatro elementos: los actores (roles externos), el límite del sistema (el rectángulo, que es la frontera del Vol. 01 ahora dibujada), los casos de uso (objetivos) y las asociaciones (las líneas que indican quién participa en qué).' },
        { type: 'p', text: 'Figura 4.1 — Casos de uso de Turnify.' },
        { type: 'p', text: 'Los actores son los mismos de toda la colección: cliente, encargado y empleado. El caso “Revisar reserva pendiente” nace de la alternativa que planteamos en el Vol. 02 (cap. 08): algunos servicios requieren revisión del encargado. El servicio de mensajería muestra que un actor no tiene que ser una persona. A propósito, no usamos «include» ni «extend»: en esta etapa complican más de lo que aclaran.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'El diagrama muestra objetivos y alcance; la descripción del caso de uso, los pasos.' },
        { type: 'box', kind: 'atencion', title: null, text: '“Iniciar sesión”, “ver botón” o “abrir pantalla” no son objetivos. Describen mecanismos o pasos. Preguntá qué objetivo habilitan: nadie entra a Turnify para iniciar sesión.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: '¿Y el dueño?', text: 'El dueño no aparece en la figura 4.1. ¿Debería? Si agregás un caso de uso para él, ¿cuál sería su objetivo? Justificá tu decisión.' },
      ],
      fuentes: ['OMG — UML 2.5.1, Use Cases.', 'Vol. 03, cap. 03 (CU-01).'],
    },
    {
      id: '05',
      title: 'Diagramas de actividad',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'El diagrama de casos de uso dice qué objetivos existen. Para ver cómo fluye uno de ellos, necesitamos otro modelo.' },
        { type: 'p', text: 'Un diagrama de actividad representa el flujo de control entre acciones, con sus decisiones, recorridos alternativos y paralelismos. Las particiones (las columnas) muestran quién realiza cada acción.' },
        { type: 'p', text: 'Sus elementos: el nodo inicial (círculo lleno) y el final (círculo con borde); las acciones (rectángulos redondeados); la decisión, un rombo con preguntas que elige una salida, y la fusión (merge), un rombo sin preguntas que reúne caminos; y la bifurcación (fork) y la unión (join), barras que dividen el flujo en ramas simultáneas y esperan a que todas terminen.' },
        { type: 'p', text: 'Figura 5.1 — Actividad de “Reservar turno” (CU-01).' },
        { type: 'p', text: 'La vuelta desde “¿El horario sigue libre?” es el desvío 6b del Vol. 03; la decisión sobre la revisión hace aparecer el estado pendiente (cap. 08); y la bifurcación final muestra que informar al cliente y actualizar la agenda no dependen una de otra.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Cada rombo debería llevar una pregunta que alguien pueda responder con la información disponible.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Agregar un desvío', text: 'La figura 5.1 no muestra el desvío 6a (faltan datos obligatorios). Describí en texto qué decisión agregarías, dónde y a qué acción volvería el flujo.' },
      ],
      fuentes: ['OMG — UML 2.5.1, Activities.'],
    },
    {
      id: '06',
      title: 'Diagramas de secuencia',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'La actividad muestra qué pasa. La secuencia muestra quién le dice qué a quién, y cuándo.' },
        { type: 'p', text: 'El diagrama de secuencia representa interacciones ordenadas en el tiempo: el tiempo corre hacia abajo y cada flecha es un mensaje. Ayuda a pasar de un objetivo a una conversación concreta entre participantes sin definir todavía una arquitectura.' },
        { type: 'p', text: 'Figura 6.1 — Secuencia de “Reservar turno” a nivel de análisis.' },
        { type: 'p', text: 'El recuadro alt agrupa caminos alternativos, y solo uno ocurre: el horario ocupado (desvío 6b), el servicio con revisión o el servicio sin revisión. Los participantes son los mismos actores del capítulo 04 más Turnify, tratado como una sola caja.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'A nivel de análisis, el sistema es una caja: importa qué mensajes recibe y envía, no cómo se organiza por dentro.' },
        { type: 'box', kind: 'atencion', title: null, text: 'dividir Turnify en “servicio de reservas”, “disponibilidad” o “notificador” ya es diseño, una decisión que corresponde al Vol. 07.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Secuencia de una cancelación', text: 'Describí en texto la secuencia de “Cancelar turno” con cliente, Turnify y servicio de mensajería. Incluí un fragmento alt para la cancelación fuera de plazo (CA-02.2 del Vol. 03).' },
      ],
      fuentes: ['OMG — UML 2.5.1, Interactions.'],
    },
    {
      id: '07',
      title: 'Clases y dominio',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Los modelos anteriores nombran turnos, servicios y clientes. Es momento de ponerse de acuerdo sobre qué son y cómo se relacionan.' },
        { type: 'p', text: 'Un modelo de clases puede representar conceptos, atributos, operaciones y relaciones. En análisis se usa sobre todo como modelo de dominio: conceptos del negocio con sus atributos y relaciones, sin operaciones. Su valor principal es construir un vocabulario común y hacer visibles relaciones y reglas.' },
        { type: 'p', text: 'Figura 7.1 — Modelo de dominio de Turnify.' },
        {
          type: 'table',
          headers: ['Concepto', 'En la figura 7.1'],
          rows: [
            ['Clase conceptual', 'Turno, Servicio, Cliente, Vehículo, Empleado.'],
            ['Atributos', 'Turno: fechaHora y estado.'],
            ['Asociación', 'Un cliente reserva turnos.'],
            ['Multiplicidad', 'Un cliente puede tener cero o muchos turnos (0..*); cada turno es de un solo servicio (1).'],
            ['Restricción', 'La regla de la nota: no puede haber dos turnos confirmados en el mismo horario y recurso (TRN-FR-002).'],
          ],
        },
        { type: 'p', text: 'La asociación “Turno para 1 Vehículo” es la regla de definición del Vol. 01 (cap. 07) —un turno corresponde a un único vehículo— expresada como multiplicidad.' },
        { type: 'box', kind: 'atencion', title: null, text: 'No pongas “cliente” como atributo de Turno si ya existe la asociación. Sería decir lo mismo dos veces, y la versión como atributo se parece más a una columna de base de datos que a un concepto del dominio.' },
        { type: 'h3', text: '7.1 Tipos de relación' },
        {
          type: 'table',
          headers: ['Relación', 'Pregunta'],
          rows: [
            ['Asociación', '¿Qué conceptos se relacionan?'],
            ['Generalización', '¿Existe una relación de tipo y subtipo relevante?'],
            ['Composición', '¿La parte deja de existir si desaparece el todo?'],
            ['Agregación', '¿Hay una relación todo–parte sin esa dependencia?'],
          ],
        },
        { type: 'p', text: 'No uses composición porque “se ve más técnica”: la relación debe representar una decisión que puedas explicar. Con la agregación, además, la propia especificación reconoce que su significado varía según el ámbito; ante la duda, una asociación simple suele alcanzar.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Un modelo de dominio habla del negocio, no de tablas ni de pantallas.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'Dos vehículos por turno', text: 'En el Vol. 02 (cap. 09) la empresa decidía que un turno podía involucrar dos vehículos. ¿Qué cambiarías en la figura 7.1? ¿Qué otra regla se vería afectada?' },
      ],
      fuentes: ['Larman, C. — Applying UML and Patterns.', 'OMG — UML 2.5.1, Classification.'],
    },
    {
      id: '08',
      title: 'Máquinas de estados',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'En el modelo de dominio, “estado” era un atributo más de Turno. Algunos atributos merecen su propio modelo.' },
        { type: 'p', text: 'Algunos conceptos se entienden mejor observando cómo cambian. Una máquina de estados muestra los estados posibles de un objeto, los eventos que lo hacen cambiar y las condiciones (entre corchetes) que deben cumplirse.' },
        { type: 'p', text: 'Figura 8.1 — Estados de un turno.' },
        { type: 'p', text: 'Los turnos arrancan en Pendiente o en Confirmado según el servicio requiera revisión, igual que en la figura 5.1. La condición [faltan más de X horas] es la misma X que quedó abierta en el Vol. 03. Y “No presentado” depende de la tolerancia que discutimos en el Vol. 01 (cap. 07, “15 minutos tarde”), que todavía hay que validar como regla.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Cada transición es una regla de negocio dibujada. Si no sabés qué evento dispara un cambio, encontraste una pregunta para el stakeholder.' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'Transiciones que faltan', text: '¿Puede un turno cancelado volver a confirmado? ¿Dónde entraría “reprogramar”? ¿Qué pasa si el encargado nunca revisa un turno pendiente? Escribí las preguntas que harías al dueño.' },
      ],
      fuentes: ['OMG — UML 2.5.1, State Machines.'],
    },
    {
      id: '09',
      title: 'BPMN: modelar procesos de negocio',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'UML mira el sistema. Para mirar el proceso completo, incluido lo que pasa fuera del software, existe otra notación.' },
        { type: 'p', text: 'BPMN (Business Process Model and Notation) es una notación estandarizada para representar procesos de negocio. ISO/IEC 19510 plantea como objetivo que sea comprensible para usuarios de negocio, analistas y responsables técnicos, y que funcione como puente entre el diseño de los procesos y su implementación.' },
        {
          type: 'table',
          headers: ['Elemento', 'Pregunta que responde'],
          rows: [
            ['Pool y carril (lane)', '¿Qué participante realiza el proceso y qué rol interno hace cada trabajo?'],
            ['Evento (círculo)', '¿Qué inicia, interrumpe o termina algo?'],
            ['Tarea (rectángulo)', '¿Qué trabajo se realiza?'],
            ['Compuerta (gateway, rombo)', '¿Dónde se decide, divide o reúne el flujo?'],
            ['Flujos de secuencia y de mensajes', '¿En qué orden ocurre el trabajo (línea continua) y qué se intercambia entre participantes (punteada)?'],
          ],
        },
        { type: 'p', text: 'Figura 9.1 — Proceso de reserva del lavadero.' },
        { type: 'p', text: 'El cliente es un pool cerrado: solo importan sus mensajes con el lavadero. El carril del encargado muestra algo que la actividad no mostraba: la revisión es trabajo de una persona.' },
        { type: 'box', kind: 'idea-clave', title: null, text: 'BPMN mira el proceso de negocio; UML, el sistema. Se complementan, no se reemplazan.' },
        { type: 'box', kind: 'practica', nivel: 'APLICAR', title: 'El camino del rechazo', text: 'La figura 9.1 supone que el encargado siempre aprueba. Describí qué agregarías para el caso en que rechaza la reserva: ¿qué compuerta, qué tarea y qué mensaje al cliente?' },
      ],
      fuentes: ['OMG — Business Process Model and Notation (BPMN), v2.0.2.', 'ISO/IEC 19510:2013.'],
    },
    {
      id: '10',
      title: 'Integración de modelos',
      refrescoConceptos: null,
      body: [
        { type: 'p', text: 'Tenemos seis modelos de la misma reserva. Ahora hay que comprobar que no se contradigan.' },
        { type: 'p', text: 'Los modelos se vuelven realmente útiles cuando pueden explicarse entre sí. Cada uno debería poder rastrearse hasta algo que ya especificamos en los volúmenes anteriores.' },
        {
          type: 'table',
          headers: ['Origen', 'Modelo', 'Pregunta siguiente'],
          rows: [
            ['Requisito (Vol. 02)', 'Casos de uso', '¿Qué objetivo representa?'],
            ['Caso de uso (Vol. 03)', 'Actividad', '¿Cómo fluye el comportamiento?'],
            ['Caso de uso (Vol. 03)', 'Secuencia', '¿Quién colabora y en qué orden?'],
            ['Vocabulario del negocio', 'Dominio', '¿Qué conceptos participan?'],
            ['Regla de negocio (Vol. 01)', 'Estados o actividad', '¿Qué comportamiento condiciona?'],
            ['Proceso (Vol. 01)', 'BPMN', '¿Cómo se realiza el trabajo de punta a punta?'],
          ],
        },
        { type: 'box', kind: 'idea-clave', title: null, text: 'Los modelos deben contar la misma historia desde perspectivas diferentes.' },
        { type: 'h3', text: '10.1 Un ejemplo de coherencia' },
        { type: 'p', text: 'Seguí el estado pendiente por todo el volumen: nace de un atributo del dominio (Servicio.requiereRevisión, figura 7.1), provoca una decisión en la actividad (figura 5.1) y un camino alternativo en la secuencia (figura 6.1), es un estado de la máquina (figura 8.1) y se convierte en trabajo de una persona en el BPMN (figura 9.1). Si cualquiera de esos modelos lo ignorara, tendríamos una inconsistencia.' },
        { type: 'h3', text: '10.2 Preguntas de revisión' },
        { type: 'p', text: '¿Todos los actores del diagrama de casos de uso tienen sentido en el contexto?' },
        { type: 'p', text: '¿Las actividades representan realmente el proceso?' },
        { type: 'p', text: '¿La secuencia respeta las reglas identificadas?' },
        { type: 'p', text: '¿Las clases representan conceptos del dominio y no tablas o pantallas?' },
        { type: 'p', text: '¿Los estados son compatibles con las reglas?' },
        { type: 'box', kind: 'practica', nivel: 'ANALIZAR', title: 'La cadena completa', text: 'Para “Reservar turno”, armá la cadena usando los identificadores de la colección: requisito (TRN) → historia (HU) → caso de uso (CU) → figuras de este volumen → criterios de aceptación (CA).' },
      ],
      fuentes: [],
    },
  ],

  cierre: {
    desafioIntegrador: {
      title: 'Desafío integrador: recursos especiales',
      body: [
        { type: 'p', text: 'En el Vol. 02 quedó abierta una pregunta: ¿qué es un “recurso”? El dueño finalmente responde.' },
        { type: 'box', kind: 'el-caso', title: 'Una regla nueva', text: 'Algunos servicios requieren recursos especiales, como la máquina de tapizados. Un recurso solo puede asignarse a un turno compatible y no puede usarse al mismo tiempo en dos reservas.' },
      ],
      entregables: [
        { text: 'Definí actores y objetivos y actualizá la figura 4.1.', capRef: '04' },
        { text: 'Ampliá la actividad de “Reservar turno” con una decisión sobre el recurso.', capRef: '05' },
        { text: 'Describí una secuencia con al menos cuatro participantes.', capRef: '06' },
        { text: 'Agregá el recurso al modelo de dominio con sus relaciones y multiplicidades.', capRef: '07' },
        { text: 'Definí los estados posibles del recurso.', capRef: '08' },
        { text: 'Representá el proceso de negocio en BPMN a nivel conceptual.', capRef: '09' },
        { text: 'Indicá una inconsistencia que podría aparecer entre los modelos.', capRef: '10' },
        { text: 'Escribí tres preguntas abiertas para el stakeholder.', capRef: null },
      ],
      autoevaluacion: {
        headers: ['Nivel', 'Podés…', 'Indicador'],
        rows: [
          ['Conocer', 'leer modelos', 'Distinguís UML de BPMN y reconocés los elementos de cada diagrama.'],
          ['Aplicar', 'construir modelos', 'Elegís el modelo según la pregunta y lo construís para un caso concreto.'],
          ['Analizar', 'revisar consistencia', 'Detectás contradicciones entre modelos y exceso o falta de detalle.'],
        ],
      },
    },

    mapaDeSalida: {
      ideas: [
        { text: 'Un modelo es una representación con propósito: responde una pregunta.', capRef: '01' },
        { text: 'La pregunta elige el modelo, no al revés.', capRef: '02' },
        { text: 'UML es un lenguaje, no una metodología; organiza sus diagramas en estructura y comportamiento.', capRef: '03' },
        { text: 'El diagrama de casos de uso muestra objetivos y alcance; la descripción, los pasos.', capRef: '04' },
        { text: 'Las actividades muestran flujo, decisiones y paralelismo; las particiones, quién hace qué.', capRef: '05' },
        { text: 'A nivel de análisis, la secuencia trata al sistema como una caja.', capRef: '06' },
        { text: 'El modelo de dominio habla del negocio, no de tablas ni de pantallas.', capRef: '07' },
        { text: 'Cada transición de estado es una regla de negocio dibujada.', capRef: '08' },
        { text: 'BPMN mira el proceso de negocio, incluido el trabajo fuera del software.', capRef: '09' },
        { text: 'Los modelos deben contar la misma historia desde perspectivas diferentes.', capRef: '10' },
      ],
      puente: {
        title: 'Puente al próximo volumen',
        text: 'Ya podemos representar el sistema desde distintas perspectivas. El próximo paso es entender los datos: cómo se estructuran, cómo se consultan y qué decisiones aparecen cuando el modelo de dominio de la figura 7.1 debe convertirse en información persistente.',
      },
    },

    respuestasOrientativas: [
      {
        capId: '01',
        titulo: 'Tu primer modelo',
        nivel: 'Conocer',
        respuesta: ['Respondía qué queda dentro y fuera del sistema de gestión de turnos. No podía responder en qué orden ocurren las cosas, quién hace cada tarea ni cómo cambia un turno: para eso están los modelos de este volumen.'],
      },
      {
        capId: '02',
        titulo: 'Dos vistas para cancelar',
        nivel: 'Aplicar',
        respuesta: ['Por ejemplo, una máquina de estados responde desde qué estados se puede cancelar y qué pasa después; una secuencia responde qué mensajes se intercambian con el cliente y con el servicio de mensajería.'],
      },
      {
        capId: '04',
        titulo: '¿Y el dueño?',
        nivel: 'Analizar',
        respuesta: ['Depende de su objetivo. Si necesita ver indicadores (conflictos evitados, turnos atendidos), podría aparecer con un caso “Consultar indicadores”. Si no interactúa con Turnify, no es actor: sigue siendo un stakeholder clave, como vimos en el Vol. 01 (cap. 05).'],
      },
      {
        capId: '05',
        titulo: 'Agregar un desvío',
        nivel: 'Aplicar',
        respuesta: ['Después de “Elegir horario, ingresar datos y confirmar”, una decisión “¿Están los datos completos?”: por “no”, una acción “Indicar datos faltantes” que vuelve a la acción del cliente; por “sí”, continúa a “¿El horario sigue libre?”.'],
      },
      {
        capId: '06',
        titulo: 'Secuencia de una cancelación',
        nivel: 'Aplicar',
        respuesta: [
          'Cliente → Turnify: solicitar cancelación (turno).',
          'Turnify: verificar plazo.',
          'alt fuera de plazo: Turnify → Cliente: informar que no se puede cancelar.',
          'alt dentro de plazo: Turnify → Mensajería: enviar aviso; Mensajería → Cliente: confirmación de la cancelación.',
        ],
      },
      {
        capId: '07',
        titulo: 'Dos vehículos por turno',
        nivel: 'Aplicar',
        respuesta: ['La multiplicidad de “Turno para Vehículo” pasa de 1 a 1..2. Se ve afectada la regla de definición del Vol. 01 (“un turno corresponde a un único vehículo”) y, probablemente, la duración del turno.'],
      },
      {
        capId: '08',
        titulo: 'Transiciones que faltan',
        nivel: 'Analizar',
        respuesta: [
          '¿Un turno cancelado puede reactivarse o hay que crear uno nuevo?',
          '¿Reprogramar es un evento sobre Confirmado o una cancelación seguida de una reserva nueva?',
          '¿Cuánto tiempo puede quedar un turno en Pendiente? ¿Qué pasa si vence?',
        ],
      },
      {
        capId: '09',
        titulo: 'El camino del rechazo',
        nivel: 'Aplicar',
        respuesta: ['Después de “Revisar reserva”, una compuerta “¿Aprueba?”. Por “no”: una tarea de envío “Informar rechazo”, con un flujo de mensajes hacia el pool del cliente, y un evento de fin. Por “sí”: sigue hacia la compuerta que lleva a “Confirmar turno”.'],
      },
      {
        capId: '10',
        titulo: 'La cadena completa',
        nivel: 'Analizar',
        respuesta: ['TRN-FR-002 → HU-01 → CU-01 → figuras 4.1, 5.1, 6.1, 7.1 y 8.1 → CA-01.1 y CA-01.2.'],
      },
      {
        capId: 'desafio-integrador',
        titulo: 'Desafío integrador',
        nivel: null,
        respuesta: [
          'Actores — Cliente y encargado; el recurso no es un actor, es un concepto del dominio.',
          'Conceptos — Turno, Servicio, Recurso y Cliente; Servicio “requiere” 0..* Recurso.',
          'Regla — Un recurso no puede estar asignado a dos turnos incompatibles en el mismo intervalo.',
          'Estados del recurso — Disponible, reservado, en uso, fuera de servicio.',
          'Decisión — ¿Existe un recurso compatible disponible para ese horario?',
          'Inconsistencia posible — La secuencia podría confirmar el turno antes de verificar el recurso, mientras la actividad lo verifica primero.',
        ],
      },
    ],

    bibliografia: [
      'Object Management Group (2017). Unified Modeling Language Specification, versión 2.5.1.',
      'Object Management Group (2014). Business Process Model and Notation (BPMN), versión 2.0.2.',
      'ISO/IEC 19510:2013 — Information technology — Object Management Group Business Process Model and Notation.',
      'Fowler, M. (2004). UML Distilled, 3.ª ed. Addison-Wesley.',
      'Larman, C. (2004). Applying UML and Patterns, 3.ª ed. Prentice Hall.',
      'Ambler, S. W. The Object Primer. Cambridge University Press.',
      'OMG — recursos oficiales de UML (uml.org).',
      'Este volumen enseña un conjunto seleccionado de modelos útiles para análisis. La selección responde al objetivo de la colección: formar criterio para decidir qué representar, por qué y con qué nivel de detalle. Los diagramas, ejemplos y ejercicios son elaboración didáctica propia.',
    ],
  },
}
